### ISSUE TITLE
[Feature Request] add division to .med file

### ISSUE THREAD

**Issue by theGreatWhiteShark** [muse-sequencer/muse#1040]
**Is your feature request related to a problem? Please describe.**
In order to increase the temporal resolution in the Arranger all that is required is to change the `division` parameter in `~/.config/MusE/MusE/MusE-seq.cfg` to a higher value. E.g. 6000 to be able to cut at zero crossings. When changed AFAICS most things work just fine (apart from glitches when scroll-zooming at the lowest resolution). (In some parts of the code base the original 384 is hard-coded. So, there still might be some things that can go wrong).

Problem with changing this global parameter is that the song length is stored in `.med` files and is expecting a certain division in order to be valid. With other values MusE won't be able to handle the song properly.

**Describe the solution you'd like**
It would be nice to incorporate the `division` parameter into the `.med` file. If that value and its global counterpart differ, the song length would be updated and stored together with the "new" global division.

Maybe the `division` could even be exposed in the Preferences. 

**Describe alternatives you've considered**
Another way to fix the song length is to add e.g. a WAV file larger than the current length. But this is kinda cumbersome.

**Comment by terminator356** [comment]
Hi. First, the division setting is accessible through the Global Settings > Midi Tab > Midi Resolution drop-down list.
It defaults to 384 with a fresh installation, but it can be changed from 48 to 15360. The available values
 are very specific because in-between values won't work properly. (They must be divisible by 3 for example).

Some months ago I completely overhauled the division setting and everything related to it.
The available values in our editor 'snap' boxes directly depend on the available divisions.
Previously they were hard-coded and not working well at all with different divisions. That has all been fixed now.
See the ChangeLog at 08.09.2020 for the extensive changes made.

There should not be any more such hard-coded '384' values in the code, except maybe at a few crucial spots.
If you know of any such places please let me know and I will investigate and correct if required.

(One result of the fixes: When importing midi files, everything should 'just work' because all timing values
 are adjusted to fit the current midi division setting. It even works with special midi files that use linear time
 instead of musical time!)


The midi division setting can be seen as roughly equivalent to our audio sample rate setting.
All audio timing derives from the audio sample rate setting, and we store in the song file the sample rate
 that the song was **created with**, so that upon reloading, if the song's sample rate does not match 
 MusE's current sample rate setting, then sample rate conversion is performed on all the waves in the song,
 so that the song and any waves in it or added later 'just work'.

So... while I was fixing the midi division stuff, I noticed we did not store in the song file the midi division
 that the song was created with. That would be **crucial** for knowing if the song was created with 
 a different midi division than what MusE is currently running with, so that appropriate conversions
 in midi note lengths could occur, similar to how the audio sample rate conversions take place
 if the song's sample rate does not match MusE's current sample rate setting.

So, **I added the song's midi division setting to the .med song file.** 
It is the xml tag "midiDivision".
This was a good very important necessary step.
However, I **did not finish** the task yet :-(
In our song loading code in songfile.cpp Song::read(), I have not yet implemented the code that would
 re-adjust all the midi note lengths.
In Song::read() at the "midiDivision" xml tag handler, I have the following comment:

`                        else if (tag == "midiDivision") {`
`                              // TODO: Compare with current global setting and convert the`
`                              //  song if required - similar to how the song vs. global`
`                              //  sample rate ratio is handled. Ignore for now.`
`                              xml.parseInt();`
`                            }`

Tim.

**Comment by theGreatWhiteShark** [comment]
Ah, okay. I mistook the `midiDivision` and the `division` for two distinct config parameters as there are both `MusEGlobal::config.midiDivision` and `MusEGlobal::config.division` (and while fiddling with the MIDI division parameter I somehow missed the changes). But I did overlooked the Undo Operation writing one of them into the other.  Sorry for the noise.

> There should not be any more such hard-coded '384' values in the code, except maybe at a few crucial spots.
If you know of any such places please let me know and I will investigate and correct if required.

`ack '[^0-9]384[^0-9]' src/muse/` gives a number of instances. These may be of relevance:

```
src/muse/midiedit/pianoroll.cpp
409:        (_minXMag * MusEGlobal::config.division) / 384,
1863:  const int min = (_minXMag * MusEGlobal::config.division) / 384;

src/muse/midiedit/scoreedit.cpp
1583:    last_len=384;

src/muse/midiedit/drumedit.cpp
516:        (_minXMag * MusEGlobal::config.division) / 384,
2287:  const int min = (_minXMag * MusEGlobal::config.division) / 384;

src/muse/widgets/musewidgetsplug.cpp
46:int division   = 384;
207:      384,                          // division;
224:      384,                          // division for smf export
244:      384,                          // gui division

src/muse/waveedit/waveedit.cpp
1145:  //const int min = (_minXMag * MusEGlobal::config.division) / 384;

src/muse/function_dialogs/setlen.cpp
33:int Setlen::len = 384;

src/muse/arranger/arranger.cpp
450:        (_minXMag * MusEGlobal::config.division) / 384,
1519:  const int min = (_minXMag * MusEGlobal::config.division) / 384;

src/muse/master/masteredit.cpp
224:        (_minXMag * MusEGlobal::config.division) / 384,
497:  const int min = (_minXMag * MusEGlobal::config.division) / 384;

```
