### ISSUE TITLE
muse-sequencer.org hijacked? advertises cakewalk, garageband etc

### ISSUE THREAD

**Issue by Windfisch** [muse-sequencer/muse#1042]
https://muse-sequencer.org/ seems to be grabbed by a domain grabber and serves ads for other DAWs :/.
What happened there, is there anything we can do against it :/?

**Comment by oldcastlehq** [comment]
I think rename/rebrand is a good idea. But don't forget there is another Mu Lab already. I'm not sure if another 'mu' is the way to go :-)

**Comment by oldcastlehq** [comment]
Hey. Is the idea still up?

**Comment by cezaryece** [comment]
It is sometimes very frustrating while I search something related with MusE and for first few pages of result all is about "Muse"...
 
Well... "muse" is very nice to rewrite to something looking or sound very close.
Muses
Remuse
Moosie
MJuice

Just choose something...

**Comment by terminator356** [comment]
One more thing: What about this entire github project?
How could we proceed to rebrand it with as little disruption as possible to users?

**Comment by fpesari** [comment]
> One more thing: What about this entire github project? How could we proceed to rebrand it with as little disruption as possible to users?

Github allows setting a redirect, so that all links to this repo will lead to the new repo.

I also agree that asking Werner Schweer is a good idea.

**Comment by oldcastlehq** [comment]
Brainstorming here. 

It seems that life is getting in the way of MusE main developers and this is how it is. Our priorities change thought time :-) Honestly, I think if this project doesn't find a way to reinvent itself, the chances of becoming a zombieware are high. IMHO, only rebranding it, is not enough. We need new blood here. Apart from rebrand it, I would suggest the main developers release a kind of open letter (or just a post at linuxmusicians.com is fine too) to the Linux developers/audio community calling for new people to help run/take over the project. Sure, anyone can fork it and do that by itself, but I think it would be nice if the main people behind MusE initiate that. Any thoughts?

**Comment by terminator356** [comment]
We've always had trouble attracting coders. We're just not that big and well organized I suppose.

Development on MusE has been slow the last year or so.
@kybos who did all the great UI changes, and much more, seems to have disappeared.
The team was really humming along great, then Covid came, then I suddenly got very busy in life,
 then MusE fell rather silent after he disappeared. We don't know if he is OK.
Ominously, his github contributions profile basically completely stops at last year  :-(

In my case, I am still coding for MusE. I am still very much committed to it.
The problem is that some of the tasks I have chosen are **extremely** complex and are
 taking a very very long time to complete.
Thus it _appears_ that MusE is a zombie at the moment but not quite,
 there is still more to come, at least from me as long as I can help it.

Ah, life changes, and hits you in the head sometimes, eh?

**Comment by Windfisch** [comment]
MusE is a niche tool for a niche target group. The intersection set between coders and musicians isn't that large, and MusE is the smallest of Rosegarden, LMMS and MusE. Also, there is Reaper, which is not open source but Just Works[tm].

I am watching the project for more than a decade now, and yes: developers come and go. MusE has been dormant when I, a guy who just finished school and has not started university yet, arrived, bringing back life to it. Once university started to demand more time, MusE fell asleep* again, until another contributor appeared (and disappeared). 
And the next contributor will find MusE some day.

(*: except for the constant background noise of Tim slowly but steadily bringing stuff forward :D Hi Tim *waves*)

Tbh, if making MusE a widely known and used project is your goal, you'd first have to do some sort of "market analysis". What can MusE offer what others can't. And why does this matter. Most people use the free version of Reaper and just don't care about OSS. Why should they?

I think if you want to make MusE Great Again[tm], you will need a goal. Why *is* MusE great? Think about that.



On an unrelated side note, I just fired up muse4 after *years*. Holy! That thing has seen worse days. It actually looks quite good these days, and IIRC, the user experience has also improved quite a bit. And glad that I still can see my beloved old score editor :3.
(Unfortunately, my "thinking of the past experience" was rudely interrupted by MusE segfaulting after I clicked some button. It might have been the "Show/Hide Midi Tracks" button. Otoh, it's like the old days XD).

Great work overall guys, and great to see @terminator356 still working on MusE!

**Comment by oldcastlehq** [comment]
I would be more than happy to help on that. There are a lot to do and some actions are needed quite soon. However, I don't know "who is in charge" here, or how many developers we actually have now. But it would be easier if we "all" have a chat or at least exchange some emails.

> On an unrelated side note, I just fired up muse4 after _years_. Holy! That thing has seen worse days. It actually looks quite good these days, and IIRC, the user experience has also improved quite a bit. And glad that I still can see my beloved old score editor :3. (Unfortunately, my "thinking of the past experience" was rudely interrupted by MusE segfaulting after I clicked some button. It might have been the "Show/Hide Midi Tracks" button. Otoh, it's like the old days XD).

A lot happened after releasing v4. The changes made by @kybos were great. I think, MusE should release version 4.1, otherwise we still need to keep using the appimage.

**Comment by fpesari** [comment]
I need to be careful about making new commitments but MusE is for sure the music-related project I'd like to contribute to the most. I already added some stuff to the Italian translation (you can find what I did so far in [my fork](https://github.com/fpesari/muse/) but it's not ready to merge yet) and I'd like to contribute something in terms of code too but for now, with the premise that I know that ideas are cheap, here are some:
- Make MusE more modular, splitting at the very least the excellent sequencer and the score editor (if not the Mixer and Wave Editor) into separate components which could be used as standalone programs. The rationale for this is that `non` is unmaintained and currently all usable FLOSS DAWs use the monolithic approach. MusE is already more modular than most DAWs, IMHO. MusE's sequencer stands out while the Score Editor and the Wave Editor could use some work. There is no lightweight MIDI-oriented FLOSS notation editor that I currently know of (`nted` is abandoned and Rosegarden is lightweight but monolithic), the Score Editor could benefit from improvements which, if standalone, could come from the whole FLOSS audio community (and not just MusE users), since a lightweight MIDI-oriented notation editor is desperately needed (even the famous REAPER has a functional one that's not super easy to use, IMHO, so even non-FLOSS users could need one). This would not lead to fragmentation: once split, components would just become subprojects in the MusE codebase and everything would work the same
- Hire a designer. MusE does not look bad but it lacks a designer's touch and finding ones willing to work for free is hard, especially within the context of desktop programs. We can make a fundraiser for this and hire a Freelancer for a reasonable sum. [Stargate](https://stargateaudio.github.io/s-gallery/) did it on Fiverr (IIRC) and I think the result is pretty good
- Improve the website with a showcase. I know for sure that my friend @StaffanMelin has made many tracks which have been released on streaming services and have received a lot of positive feedback but he's not the only one, there is also MusE's own @spamatica and others who use it to make good music. I suspect that many people get the impression that MusE is a "toy" which can't produce real-world songs...but if it's not true already, why not prove it? :smiley: Also the current website has unrelated backgrounds (a sunset, a brick wall and a railway...why?), old screenshots, top links which all lead to Github, old videos (one about version 2.2) and other stuff which might put off users. I am not a web designer and I am not criticizing the work of who very kindly made the current website, I am just saying a more focused website (even one using a premade template for a static site generator like [Hugo](https://gohugo.io/)) IMHO would attract more users to the program
- Finally, I agree with the rebranding because MusE is sadly a generic name which is also linked to MuseScore. When MusE is suggested, some people might think that it's a shorthand for MuseScore. Also, IIRC MuseScore is getting DAW capabilities, so in a way it's becoming a competitor to MusE and that could only increase confusion. I am glad that nobody really brought up the ideological war of which program came first and I think that kind of reasoning to be a dead end. I think a rebranding would really make this program stand out on its own and that's the important thing, IMHO. Throwing one out there, something with "Lyre" in it (like Lyrebird, a bird named after the Lyre) would make sense because it would acknowledge MusE's history and there are not any famous music programs I know of with Lyre in their name.

**Comment by oldcastlehq** [comment]
Great points @fpesari. From a marketing and branding perspective, it would make sense to start working from your points from bottom up. Rebranding and "organizing" this project, IMHO should be the top priority. Once we got our "new house",  it would be easier to attract more people to the project. If you think of, there are so many things that we need to get it done. Name, logo, tagline, brand voice, colour palette, visual identity, website, social media, wiki, documentation, forum, and much more. It's a lot of work that most of us will do during our spare time. So, again, it would be nice to start having talks with the decision makers.

**Comment by StaffanMelin** [comment]
Those are interesting ideas! It is great that you guys want to get involved!

I would first and foremost, if we could raise money, make sure that Tim (@terminator356) got them! :)

Maybe we could arrange some kind of digital meeting with people who are interested in working for MusE? @spamatica and @terminator356, what do you think?

**Comment by oldcastlehq** [comment]
> Maybe we could arrange some kind of digital meeting with people who are interested in working for MusE? @spamatica and @terminator356, what do you think?

That would be great indeed!

**Comment by fpesari** [comment]
If you want to organize it, please share the link on LinuxMusicians too but not in the MusE forum (as non-MusE users might be interested in contributing too).

As a platform, I suggest a FLOSS browser-based one like Jitsi Meet or the underrated EduMeet (which works better on older PCs, in my experience).

**Comment by StaffanMelin** [comment]
We'll see what @spamatica and @terminator356 thinks and have time for! :)

**Comment by oldcastlehq** [comment]
> If you want to organize it, please share the link on LinuxMusicians too but not in the MusE forum (as non-MusE users might be interested in contributing too).

Good idea.

**Comment by spamatica** [comment]
Hi everybody! As usual I apologize for not being around for the discussion.

As has been noted, MusE has a long history of being a bit step-motherly treated. As I consider myself being in charge (mainly due to being around the longest) I am a big part of that. Simply put, I divide myself over too many things, and MusE seldom gets the priority…

We had really good progress for the 4.0 release cycle almost entirely due to the addition of Kybos and his vision of improving the workflow and visuals. All of which I think have worked out very well. It does however look like Kybos has left the project so we are again back to a trickle of changes. Which basically leaves us at two people, me that is barely around and Tim that does work a lot on MusE but usually very long term changes.

This does put MusE in an unfair position where you can see the potential that would make MusE a bigger player but it's out of reach. Not to say MusE can't be used, I have probably made more songs than anyone with it. But it does require a bit of the user due to bugs and unintuitive bahaviour.

For me the end game of making MusE a bigger player is to attract a bigger community.  Big enough that it is sustainable without relying on individual persons. Getting there is however a lot of work and may not be possible in our nieche.

BUT, making a public online-meeting could be a thing, to check if there is any interest in a bigger group of people? I can help a bit but I would be very glad if someone else took the lead on setting up such a thing.

**Comment by StaffanMelin** [comment]
Thank you @spamatica, for this and all your work!

I'll check with Tim. Then I can try to set something up in the coming weeks! :)

**Comment by StaffanMelin** [comment]
The discussion continues here:
[](https://linuxmusicians.com/viewtopic.php?f=61&t=24343)
