### ISSUE TITLE
Can't open saved file - MusE crashes

### ISSUE THREAD

**Issue by StaffanMelin** [muse-sequencer/muse#1047]
When I open a song previously created in MusE (version about 2 months old, compiled from source), MusE crashes and I get the following in the terminal:

```
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 5517, resource id: 20783960, major code: 40 (TranslateCoords), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 7673, resource id: 20785263, major code: 40 (TranslateCoords), minor code: 0
Setting project path to /home/staffan/Documents/projects/music/dreams_of_seagulls/dreams_of_seagulls_supernova
INFO: Requested timer frequency:1024 actual:1000
Segmentation fault
```
Troublesome song is attached.

Running on Debian 11 Bullses/XFCE
[dreams_of_seagulls_supernova.med.zip](https://github.com/muse-sequencer/muse/files/7242689/dreams_of_seagulls_supernova.med.zip)
4.

**Comment by spamatica** [comment]
Good news is that I can recreate the crash.

Bad news is that it seems the crash happens deep inside Surge.

(gdb) backtrace
#0  0x00007ff10f336a64 in  () at /usr/lib/lv2/Surge.lv2/Surge.so
#1  0x00007ff10f1d31f8 in  () at /usr/lib/lv2/Surge.lv2/Surge.so
#2  0x00007ff10f1d4996 in  () at /usr/lib/lv2/Surge.lv2/Surge.so
#3  0x00007ff10f1d520d in  () at /usr/lib/lv2/Surge.lv2/Surge.so
#4  0x00007ff10f3381bb in  () at /usr/lib/lv2/Surge.lv2/Surge.so
#5  0x000055a08652baec in lilv_instance_run(LilvInstance*, uint32_t) (instance=0x55a0941b9c30, sample_count=512) at /usr/include/lilv-0/lilv/lilv.h:1704
#6  0x000055a08653fc59 in MusECore::LV2SynthIF::getData(MusECore::MidiPort*, unsigned int, int, unsigned int, float**) (this=
    0x55a09447a1e0, pos=0, ports=2, nframes=512, buffer=0x7ff10dabcee0) at /home/ddskrjo/dev/muse/src/muse/lv2host.cpp:4829
#7  0x000055a0864ad33a in MusECore::SynthI::getData(unsigned int, int, unsigned int, float**) (this=

It is hard to tell what causes the misbehavior since it is beyond our own scope.

There are some workarounds to get up and running again:
1. start muse with LV2 synths disabled (-2), delete one or more of the Surge instances save it and try to load that.
2. since the *.med files are readable it is possible to remove the configuration block for one or more of the synths. But it is questionable if this has any merit over 1.

I tried 1. and for me the project started running when I removed the Strings instance.
Now, it is quite possible that I see a different crash, Surge is a really cool synth but I have found it to take version compatibility on the light side.. anecdotal evidence so I might be wrong.
Workaround 1. is still your best way forward at this point.

**Comment by StaffanMelin** [comment]
Thanks a lot for looking into this @spamatica!

I followed your advice and started with -2, and had no problem opening the project, great tip!

As Surge seems to be a VST3-only project now, I seriously thinking about abandoning it as my go-to synth. Or is VST3 supported in MusE?

**Comment by StaffanMelin** [comment]
BTW Should I close this issue as it is a Surge bug?
