### ISSUE TITLE
MusE moves parts when clicking "Use mastertrack tempo"

### ISSUE THREAD

**Issue by StaffanMelin** [muse-sequencer/muse#1052]
"Use mastertrack tempo" is off.

I click "Use mastertrack tempo" as I want to change tempo later in song.

Audio parts are moved in the Arranger. See images, pre and post.

"Global" tempo was 130 bpm before clicking. After it was 33 bpm (I think I used this before in the song).

I can undo and then everything reverts back to how it was before.

I solved it by placing the marker at 0, setting the tempo back to 130. Then changing it where I wanted it too (after to sound clips).

Compiled master from 2 days ago running on Debian 11.

Pre:
![pre](https://user-images.githubusercontent.com/33361311/137395568-6cdd07fe-457e-4fff-a15b-700b75aec172.jpg)

Post:
![post](https://user-images.githubusercontent.com/33361311/137395576-47809c50-8a78-4e0e-acb9-45acdd4e7b58.jpg)

**Comment by terminator356** [comment]
Hi! This behavior is normal for MusE, currently.
All midi parts are in units of _musical_ time (bars, beats, ticks).
So they do not move when tempo is changed.
But all wave parts are in units of _linear_ time (minutes, seconds, frames).
So when tempo is changed, they move around because the _linear_ time at which they start,
 and their length, changes with tempo.

The way to solve this is to make wave parts in units of _musical_ time. Just like midi parts.
Sounds easy? Not so fast. We can certainly make the part boxes in _musical_ time,
 but the actual waves need to be **time-stretched** to fit the boxes.
Since MusE's birth we had no time-stretching ability, so the behavior has been left
 this way for a very long time.

However, a few years ago I did in fact add time-stretching.
You can now **stretch waves** within the Wave Editor.
That was a necessary, and quite adventurous, first step.

The next step is to give time-stretch ability to the actual parts.
When that is done, all wave parts can then be switched to _musical_ time,
 and MusE will rock - what you see is what you'll get. Wave parts will 
 automatically stretch the sound waves to match the tempo.
This too is not as easy as it sounds. Inevitably this typically necessitates
 the use of 'beat-matching' software.

Florian (user windfisch) actually made his own branch with time stretching
 and beat matching, different than the way I did it.

I anticipate soon(ish) rather than later, I'll begin work on this wave part stuff.
Actually I did recently. I have a branch with a lot of complex changes,
 but it got really muddy. I think I need to try again, maybe from a different angle.

Tim.

**Comment by terminator356** [comment]
To summarize why once and for all fixing those wave parts to be in musical time
 is so very important:

Currently, once you add waves to MusE, your song's tempo is 'written in stone' -
 the tempo is governed by the tempo of the waves, because although you can
 change MusE's tempo to match the midi parts to the waves, you **cannot** 
 change the wave tempos to match MusE's midi tempo :-(

But when part time-stretching is finally added, this problem will (mostly) go away.

Tim.

**Comment by terminator356** [comment]
> An workable partial solution could be, as you mentioned, to consider wave parts as existing in musical time, and not stretch them, just move them

I fully agree, we really ought to do that. At the very least allow the wave parts to stay where they are,
 even though their tempo won't change. Then we would at least be prepared for the time stretching when added.
It's a big job for sure, as many sections are still hard-coded to work with the waves in linear time.
Thanks for the Reason tip.

**Comment by StaffanMelin** [comment]
That sounds very cool, and will make it possible to move to a domain where MIDI data and wave files are not that different.

Non destructive "live stretching". Awesome.

If I remember correctly, you had that quality option in Reason too. Hmmm...I think it was a setting about how to handle stretching audio, giving the algorithm a clue about the content, preserving formants or something...

But for now, just making parts stay in their right place, would be great.

In my case, I could easily handle it by setting the original tempo at bar 1 (0). The tempo changes occured after all recorded wave parts. I always stay clear of recording audio at the wrong tempo. Or at least, try to! :)
