### ISSUE TITLE
MusE 4.0 build error: ‘midiPorts’ is not a member of ‘MusEGlobal’

### ISSUE THREAD

**Issue by GvMariani** [muse-sequencer/muse#1063]
**Describe the bug**
The building of MusE 4.0 fails while processing muse-4.0/muse/components/confmport.cpp.
There are various messages in the log (full log of a failed build attached):
* mostly "error: ‘midiPorts’ is not a member of ‘MusEGlobal’ "
* one time "error: ‘setPortExclusiveDefOutChan’ is not a member of ‘MusECore’ "
* a few warning about muse/track.h:55:7 "note: forward declaration of ‘class MusECore::MidiPort’ "
* various consequent errors about "invalid use of incomplete type ‘class MusECore::MidiPort’ ".

**To Reproduce**
1. Install the sources from here: https://github.com/muse-sequencer/muse/releases/download/4.0.0/muse-4.0.tar.gz.
2. Run the build (see the log for the command line).
3. See the errors.

**Expected behavior**
Build completing.

**Screenshots**
N/A

**Desktop:**
 - OS: Rosa Linux Fresh 2021.1 on x86_64
 - Desktop: KDE 5 (KDE 21.08.1, KF5 5.86.0, Qt5 5.15.2)

**Additional context**
[BuildError.txt](https://github.com/muse-sequencer/muse/files/7890932/BuildError.txt)

**Comment by spamatica** [comment]
Curious. 
I'm not that familiar with Rosa Linux, tried to install in a VM but it stranded on getting the Qt dependencies installed. If you could point me in the right direction I could try it for myself?

Looking at the sources midiPorts is defined in midiport.h. 
Maybe there is another midiport.h that gets pulled in..
What if you tried making the following change in cconfmport.cpp
change
#include "midiport.h"
to
#include "muse/midiport.h"

**Comment by GvMariani** [comment]
> Looking at the sources midiPorts is defined in midiport.h.
> Maybe there is another midiport.h that gets pulled in..
Exactly... it's present in jack devel files: /usr/include/jack/midiport.h... and you need jack devel files to build MusE.

But doing only the suggested change does not help: the build now fails in /muse/components/editevent.cpp...
The "#include "midiport.h"" statement is present in a lot of files under "muse" directory.

**Comment by GvMariani** [comment]
The attached patch fixes the build for me...
[muse-4.0.0-fix-midiport-header-conflict-with-jack.txt](https://github.com/muse-sequencer/muse/files/7916400/muse-4.0.0-fix-midiport-header-conflict-with-jack.txt)

**Comment by terminator356** [comment]
Hi, happy new year.

@GvMariani please look in the system package config file
 named "jack.pc", usually found in "/usr/lib64/pkgconfig/jack.pc"
 or "/usr/lib/pkgconfig/jack.pc".

My jack.pc file contains:
"includedir=/usr/include" and
"Cflags: -I/usr/include"

Your jack.pc file might contain:
"includedir=/usr/include/jack"  and / or
"Cflags: -I/usr/include/jack"

That is because all the build lines in your BuildError.txt file show this:
... -I/usr/include/jack ...
 while my build shows no such lines:

If that is the case, what should we do?
Hm, how did your jack.pc file get like that? AFAIK it is generally not a
 good idea to put the full path in the pc file, to avoid problems like this.
It is usually best to just put "/usr/include" in the pc file and force the
 coder to write "#include abc/abc.h" wherever needed in code.

For us the correct solution to cure all such problems may be to take
 all of the cmake "include_directories" lines in our top-level cmake file
 **which bring in external package include directories** such as:
"include_directories(${SAMPLERATE_INCLUDE_DIRS})"
"include_directories(${JACK_INCLUDE_DIRS})"
and move them **just past** the following line which brings in
 all of **our** directories, so that it looks something like this:

```
include_directories(
   .
   ${PROJECT_SOURCE_DIR}
   ${PROJECT_SOURCE_DIR}/libs/evdata
   ${PROJECT_SOURCE_DIR}/libs/memory
   ${PROJECT_SOURCE_DIR}/libs/midi_controller
   ${PROJECT_SOURCE_DIR}/libs/midnam
   ${PROJECT_SOURCE_DIR}/libs/mpevent
   ${PROJECT_SOURCE_DIR}/libs/plugin
   ${PROJECT_SOURCE_DIR}/libs/string
   ${PROJECT_SOURCE_DIR}/libs/sysex_helper
   ${PROJECT_SOURCE_DIR}/libs/time_stretch
   ${PROJECT_SOURCE_DIR}/libs/wave
   ${PROJECT_SOURCE_DIR}/libs/xml
   ${PROJECT_SOURCE_DIR}/muse
   ${PROJECT_SOURCE_DIR}/muse/function_dialogs
   ${PROJECT_SOURCE_DIR}/muse/widgets
   ${PROJECT_SOURCE_DIR}/muse/components
   ${PROJECT_SOURCE_DIR}/muse/instruments

   ${PROJECT_BINARY_DIR}
   ${PROJECT_BINARY_DIR}/muse
   ${PROJECT_BINARY_DIR}/muse/function_dialogs
   ${PROJECT_BINARY_DIR}/muse/widgets
   ${PROJECT_BINARY_DIR}/muse/components
   ${PROJECT_BINARY_DIR}/muse/instruments
   ${PROJECT_BINARY_DIR}/muse/ctrl
   )

# Mandatory packages, check already done:
include_directories(${JACK_INCLUDE_DIRS})

# Optional packages. Shall we check if found -  or is that
#  not required since the string would be blank anyway?:
if (ALSA_FOUND)
  include_directories(${ALSA_INCLUDE_DIRS})

```
This way the search should always look at our directories first.
It should be evident in the build output.

Usually when using external packages we already tend to
 use lines like "#include <abc/abc.h>" anyway whereas if we
 want our own file we might do "#include <abc.h>"
Therefore if we can get this path searching order correct
 we might continue to write things that way.

@spamatica I wonder if you have some time to try the idea.
If I start to work on it I will let you know.

Thanks.

**Comment by terminator356** [comment]
> @spamatica I wonder if you have some time to try the idea.

Or, if @GvMariani has time and would like to try, since that is
 the system to test on.

**Comment by GvMariani** [comment]
> Hm, how did your jack.pc file get like that? AFAIK it is generally not a
> good idea to put the full path in the pc file, to avoid problems like this.
> It is usually best to just put "/usr/include" in the pc file and force the
> coder to write "#include abc/abc.h" wherever needed in code.

It's a distro thing...
Rosa is carrying a patch to the jack .pc file and it adds to the Include line the full path: I don't know why that patch was added, though, nor I cannot say if it can dropped...

So I guess the solution your propose it's the right way... I will give it a try, in the next few days.

**Comment by GvMariani** [comment]
> Or, if @GvMariani has time and would like to try, since that is the system to test on.

Done.
I put the whole directory list in the main CMakeLists.txt file, before the comment "Begin MANDATORY packages" (line 284 if the original file)... and it builds successfully.

**Comment by terminator356** [comment]
Ah great stuff! That is easier than my suggestion. Just move the one line above all the rest.

**Comment by terminator356** [comment]
I have made the change. Re-open the issue if any more trouble.

Note that this fix is not perfect.
Sub-folders may add some of their own include directories and they will appear
 at the end of each build text section. I am not sure if we can easily fix that.
For example, the cmake file in our /muse folder adds several sub-directories of /muse
 to the search path, and they appear at the end of each build text section.
Also there are still a couple of "include_directories" lines in the top cmake file which should be
 moved up, for example our lv2Support directory part appears later in the cmake file.

There is some strange magic going on that I don't understand yet.
For example, for Qt, there are five lines like this near the top of our cmake file:
`include_directories (${Qt5Widgets_INCLUDE_DIRS})`
I checked the contents of those five "...INCLUDE_DIRS" strings and they are not empty:
`/usr/include/qt5//usr/include/qt5/QtWidgets/usr/include/qt5/QtGui/usr/include/qt5/QtCore/usr/lib64/qt5//mkspecs/linux-g++
`
But there are no such "-I" include lines in each build output section texts at all.
Instead there are strange lines that I do not recognize near the end of the build texts:
`-isystem /usr/include/qt5/QtWidgets`

Still, this fix should be OK for now.
Thanks for the report and testing!
Tim.
