### ISSUE TITLE
No Jack-Midi-Ports in Midi-Only mode

### ISSUE THREAD

**Issue by bernd100000** [muse-sequencer/muse#1075]
No Jack-Midi-Ports in Midi-Only mode

**To Reproduce**
1. run jackd with qjackctl 
2. start AppImage Muse 4.1 
3. Select 'preferences' in Menu 
4. select 'global preferences' 
5. select Audio 
6. set Audio Backend to 'Midi only' 
7. confirm 
8. restart Muse AppImage 4.1 
9. select 'preferences' in Menu 
10. select 'Midi Ports/Soft Synths' 
11. Create an jack-midi-device in usable devices area 
12. align the device to a port 
13. confirm 
14. see on connections in qjackctrl

 **Expected behavior**
![Kein Jack-Midi-Port_01](https://user-images.githubusercontent.com/8794953/172459501-458d334b-8499-4f81-b2ff-56257518a6fd.png)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: tried on Debian 11 and Ubuntu 22.04 
 - Desktop: KDE 

**Additional context**

**Comment by terminator356** [comment]
Hello. In midi-only mode there is no Jack audio or Jack midi. Only ALSA midi.
The reason that MusE even allows you to create and list such devices and ports in the dialog
 when there is no Jack midi, is because you may have an existing project that used Jack midi
 but you may want to open it without Jack (in midi-only mode) and still view the Jack devices/ports,
 or you may want to add Jack devices/ports while in midi-only mode so that later when you
 open the project with MusE's Jack driver, everything will be ready to connect (by doing some
 further connecting in the dialog).

The only minor problem I see is that we neglected to mark the Jack device's 'Status' 
 column as 'Unavailable' in midi-only mode which we should do. I can't recall why I didn't do that,
 maybe an oversight, maybe a technical reason...

And... 'midi-only' mode should perhaps be clarified and renamed as 'ALSA midi-only mode'
 since there is no Jack audio OR Jack midi support with this driver.

Tim.

**Comment by bernd100000** [comment]
Hello Tim 
your argumentation for me is not logic. Many sound-sources uses jack. So if you like to add midi soundsource, you have to start jack anyway. And this sources giving only jack-devices. One of the less programs using alsa is rosegarden. ardour is optional. ist seems very confused to start the jack-connection-kit to using alsa aonly. And I do not add instruments without to hear them. I wonder how you compose music. 

For me the name 'midi-only' associate, that I can use MusE as pure Midi-Editor and connect it with ardour, where I have much more possibilities for pure audio-material. so it produces less xruns. While MusE for me is currently a good Midieditor. But since the version 4 this opinion disappear. 

And for to add an instrument I don't switch in to an midi-only-mode, where I have to restart it. I see no logic in this step.
