### ISSUE TITLE
Behaviour of editing views.

### ISSUE THREAD

**Issue by donarturo11** [muse-sequencer/muse#1098]
Now, when I call list event, window is in dock, but if I call Pianoroll, normaly is opened in tab. I noticed if I call open Pianoroll in new window, until I won't change in preferences, has the same behaviour (open in tab).
What is expected behaviour. In my opinion, Event List should have the same behaviour as Pianoroll. About Pianoroll, if I have setted open Pianoroll in tab, default behaviour should be open in tab and calling open in new window should open in new window.

I propose to set Event List behaviour same as Pianoroll – open in tab or new window, not in dock, because is not so practical and comfortable (good solution was in MusE 3).
About Pianoroll, I think, that not opening in new window, if I have setted open in tab or opening always in new window if unsetted in my opinion is an unexpected behaviour.

**Comment by terminator356** [comment]
Yes, opening the Event List Editor in a tab instead of a dock sounds reasonable.
But I do not know how to change this behaviour.
The developer @kybos wrote all of the dock and tab code, and it is all quite new.
I would need to examine the code but I am quite busy at the moment. I will try to look at it later.
But you are welcome to try to fix it...

**Comment by donarturo11** [comment]
@terminator356 Thank you very much. So I'm going to work on Event List editor.

**Comment by donarturo11** [comment]
> But I do not know how to change this behaviour.
But I'll find it.
