### ISSUE TITLE
Windows version 

### ISSUE THREAD

**Issue by elkhalafy** [muse-sequencer/muse#1237]
Can you build muse for windows OS please??

Thanks

**Comment by terminator356** [comment]
It is not easy to do that.
Another developer is working on a Windows version at the moment.
But it may be some time before we see anything.
There are many obstacles before it can be achieved.

**Comment by elkhalafy** [comment]
So, its hard to see it or perhaps

I hope trying to build it for windows I hope so ..

**Comment by Wallby** [comment]
> It is not easy to do that. Another developer is working on a Windows version at the moment. But it may be some time before we see anything. There are many obstacles before it can be achieved.

Seems that person is @donarturo11? As in searching for commits containing the word "windows" shows win32 stuff, for example in the commit 7894c31.

**Comment by donarturo11** [comment]
The the most difficulty is audio/MIDI system. I successfully compiled with MinGW, but MusE does not start, with runned Jack for Windows too. Unfortunately because of personal things I had too few time to work with it.

**Comment by Wallby** [comment]
Was mostly curious to see if I could track progress somewhere. No pressure. I think it's cool that someone is taking the initiative.

**Comment by luginf** [comment]
@donarturo11 @terminator356 

I've managed to compile and start Muse.exe on Windows!

<img width="1916" height="1075" alt="Image" src="https://github.com/user-attachments/assets/a1e10865-3b48-498f-abeb-1144021c6c48" />

There are still a few errors (I can't record midi from my keyboard, there are jack problems), but I hope to get it work in the future! (I can't reopen the issue)

**Comment by Wallby** [comment]
@luginf Is that actual Windows XP? Or a theme? Does it compile on newer versions?

**Comment by luginf** [comment]
@Wallby I'll post a binary soon. It's not windows XP, it's windows seven. I don't use windows generally, it's the second boot of my main computer. 

So far I made it recognise my midi keyboard as input / output, but it still can't record midi (no midi signal recognised). But the audio input and record is working

<img width="941" height="491" alt="Image" src="https://github.com/user-attachments/assets/5ebb6660-e419-4510-bf9a-9ec36842ff58" />

There are some cracking in the audio, don't know if it's caused by a bad configuration or the code.

You can still test the audio if you wish, there building artefact is located at https://github.com/luginf/muse/actions/runs/33975341028/artifacts/9972350752 (maybe you'll have more luck with midi)

**Comment by Wallby** [comment]
> it's windows seven

Right. Been a long time since I used either.

**Comment by luginf** [comment]
@elkhalafy There is now a working windows version of MusE 4, feel free to try it, despise its limitations (no vst):
https://github.com/luginf/muse/releases/tag/windows-port-v0.1

**Midi is working**: I could record and replay midi on my own midi keyboard, and also use a VST from Savihost and LoopMidi.

I've opened a pull request (it also spotted a few other bugs in MusE):
https://github.com/muse-sequencer/muse/pull/1343
