### ISSUE TITLE
normalize audio clips in arranger [sf#3607443]

### ISSUE THREAD

**Issue by Windfisch** [muse-sequencer/muse#335]
Submitted by danboid on 2013-03-09 20:40:34

Under both Ardour and qtractor it is possible to quickly normalize one or many audio clips via its context menu or a shortcut key when working within their main windows, whats called the arranger in MusE.

Presently it seems you can only normalise an audio clip under MusE by individually opening each one, selecting the appropriate part (or all) of the clip then choosing 'Normalize Selection' from the Functions menu. It'd be great if MusE allowed the quick normalizing of selected audio clips in the arranger.

Thanks!

**Comment by danboid** [comment]
Any thoughts on this guys? I do this all the time under other DAWs so I normally assign the 'n' key to it so I can select many audio clips and normalize them all in one tap. It seems under git you still have to do this individually by opening each audio clip in the wave editor.

**Comment by danvd** [comment]
Hi @danboid,

I think it can be done, - not a problem. Would you help to test this?

Regards,
Andrew

**Comment by danboid** [comment]
That's good to hear. It has been one of the main missing features of Muse for me so I'd be happy to test it.

Thanks Andrew!

**Comment by danvd** [comment]
Hi @danboid,

Normalize wave part from arranger view now implemented and working. Check master and write your results :)

Regards,
Andrew

**Comment by danboid** [comment]
Thanks v.much Andrew! I should be able to test it out tonight with any luck

:D

**Comment by danboid** [comment]
Hi  Andrew

I've just tried git but normalize only works on individual wave parts currently. If I CTRL click to select multiple  audio files and choose 'Normalize wave part' it only normalizes the first wave that was selected. 

If you can fix this so it works with multiple audio clips it might make sense to adjust the menu label to just 'Normalize' so that it makes sense when operating on one or many items.

Thanks

**Comment by danvd** [comment]
Hi @danboid 

Ok, done. You can check it now :)

**Comment by danboid** [comment]
OK, that's working how I wanted now. :)

The icing on the cake would be if you could also make Normalize bindable in the arranger keyboard shortcuts for max convenience and completeness.

Thanks Andrew!

**Comment by spamatica** [comment]
Hi Dan,

control question about workflow.

I was on this a year or so ago but didn't finish it up mainly since I
wanted it to make the same normalization on all the parts you select, which
made it significantly more complex.
Is this something you'd expect? Maybe I was overthinking it.

I didn't check how Andrew implemented it but since he was so fast I expect
the code does them individually. Even though he is _really_ fast :)

/Robert

2015-07-02 10:43 GMT+02:00 danboid <notifications@github.com>:

**Comment by danboid** [comment]
Hi Robert

Yes, that'd be more than I require. I don't think I've ever normalized to anything other than 0 dB so the way Andrew has done it is fine for my needs.

Thanks guys!

**Comment by danvd** [comment]
Hi Robert,Dan

Now normalization works in one undo transaction on *all* wave parts selected, or, if nothing was selected, only one under cursor is normalized.

P.S. If there is a need to set normalize level in decibels before starting process, I can also make it.

P.P.S. Dan, what key combination will be more usable for binding?

Regards,
Andrew

**Comment by danboid** [comment]
Hi Andrew

Sounding good!

I'd prefer n, N or CTRL+N roughly in that order if any of those are available.

Thanks again!

**Comment by danvd** [comment]
I made ALT+N binding, because others with 'N' key are already used.
Also events in QApplication::notify were received twice (it seems, that it's only qt 5 issue) - I also fixed this.

Changes are in master now.

/Andrew

**Comment by danboid** [comment]
Great stuff Andrew!

Thanks again! :)
