### ISSUE TITLE
completely dockable UI, multiple view presets

### ISSUE THREAD

**Issue by Windfisch** [muse-sequencer/muse#345]
everything should be dockable, like with cakewalk sonar.

multiple view presets for switching around views

**Comment by budislav** [comment]
Main goal for my previous project has been to kill floating windows in Zynaddsubfx and making it user-friendly as much as possible.
http://budislavtvp.deviantart.com/art/ZynAddSubFX-UI-Concept-2014-455890191
https://github.com/budislav/ZynAddSubFx-GUI-Design
Thanks to Mark McCurry this mockup is in development phase and you are welcome:
https://github.com/fundamental/zyn-ui-two

This mockup is made with Pencil. Probably some windows  are missing but logic is clear. Muse have many windows, so tabs are necessary. Some of tabs should be dockable to other parts so there should be multiple view presets for switching around views somewhere in toolbar on the top. Sections should be separated clearly. This system is first step for making a user-friendly UI.

![dockable ui](https://cloud.githubusercontent.com/assets/3619927/6554629/36c6fe44-c65e-11e4-8315-bdf99a6cefe4.png)

**Comment by spamatica** [comment]
Hello Budislav,

Let me first say your gui design for Zyn is really wonderful. I hope Mark manages to implement it all.

Also many thanks for working on enhancing MusEs GUI. I need to spend some time with your mockup and see that I understand the full purpose and workflow. 
You said this is a first step, are you expecting to add more to this mockup?

**Comment by budislav** [comment]
"Let me first say your gui design for Zyn is really wonderful. I hope Mark manages to implement it all."
Thank you. Mark is doing his best, but this is not easy task.

Yes, I will work on new UI if someone will work on programing, otherwise this would be waste of time. I am planning to design all icons and graphic, but first someone should make new UI workflow  because old one does not make sense. I think that tabbed system would be the best solution for complex UI like Muse. After that we need to reorganize all options inside. On the end we would need a new icon set and GUI kit.

**Comment by budislav** [comment]
Fully redesigned mixer. I noticed a lot of mistakes in this particular window and tried to fix everything. Same mixer but pro look :) 
What do you think?

New
![mixer](https://cloud.githubusercontent.com/assets/3619927/6724456/9c8e96c8-cdf8-11e4-8c34-eb664d3e3a7c.png)
Old
![mixer old](https://cloud.githubusercontent.com/assets/3619927/6724458/a2029e92-cdf8-11e4-85ed-c0112a40b47f.png)

**Comment by spamatica** [comment]
Hi Budislav and thanks! Looks very nice :)
I forwarded this to the developer mailinglist. As you said, someone needs to take up working on the code before this is worthwhile, and I fear it is a lot of coding.

**Comment by danvd** [comment]
Wow! If nodoby don't mind, I want to code it :). I like this style!

**Comment by budislav** [comment]
Awesome! In that case I will continue to improving Muse GUI :) 
It must be more user-friendly and graphic should look nice (contrast, colors, icons, font size, ...). It is just important to have a plan and working on it. New Zyn will be ready maybe for one year and there is just one guy working on it. See a progress http://fundamental-code.com/wiki/blog/
Muse is already written in qt, right? This should be easier but I can not say that I am not programmer. If I disassemble this design, you will notice a pattern, you need to make one style for buttons, sliders, backgrounds, scrollbars, level meters and all of that will just repeating through whole interface.

**Comment by spamatica** [comment]
Hi Budislav,
Sounds like a lot of fun, especially if Andrew wants to dive into this. 
Do understand though that we are several people working on MusE and I don't want us to make drastic changes unless we agree we want do move in this direction.
As I mentioned before my own main issue is moving the gui to dock all windows. The reason MusE works as it does may not make sense but it is a traditional approach. And I would very much like to understand how you envision your solution would work.
What strikes me directly is the bottom dock with one of each type of editors. Does this mean that the piano roll should always show the currently selected part if applicable?

I started a thread on the mailing list also.

Thanks

**Comment by budislav** [comment]
Sorry for delay,
I understand you at all, this is a big job and you all need to agree with something like this. 
"As I mentioned before my own main issue is moving the gui to dock all windows. " 
I also think that this is the most important, without docked windows making a style does not have much sense.
"Does this mean that the piano roll should always show the currently selected part if applicable?"
Pianoroll tab should be opened when user double click on any part from trackdata. If user after that open any other tab and after that pianoroll, it should show the last selected part inside.

"I started a thread on the mailing list also."
If you do not mind, I prefer this kind of communication more because of very bad experience with mailing lists.

**Comment by budislav** [comment]
All windows except of main window will lose menu bar, so there will be only one menu bar in whole UI. Also file tools, global song tools and some of edit tools. We do not want double functions.

![](http://www.muse-sequencer.org/pic/wiki/main_window_filetools.png)

![](http://www.muse-sequencer.org/pic/wiki/main_window_globalsongtools.png)

![](http://www.muse-sequencer.org/pic/wiki/main_window_edittools.png)

**Comment by budislav** [comment]
Tracks

New
![tracks-01](https://cloud.githubusercontent.com/assets/3619927/6841220/ee5298fe-d386-11e4-97f3-f925a9c4f611.png)

Old
![tracks old](https://cloud.githubusercontent.com/assets/3619927/6841252/7b976686-d387-11e4-8494-b4cbb555d1e3.png)

**Comment by spamatica** [comment]
Closing this as the energy is long gone. If something is done along these lines it requires a new initiative.
