### ISSUE TITLE
bankselect doesen't work 

### ISSUE THREAD

**Issue by bernd100000** [muse-sequencer/muse#354]
I've tryed to select an other sf-bank with msb and lsb to qsynth. nothing run. I have tryed in rosegarde, it runs.

**Comment by derselbst** [comment]
not sure whether this is still an issue. may be closed, since bank selection works fine in cba5dd823290190a26a9e8228c91ce6fd936133b

make sure you've set *synth.midi-bank-select* option from fluidsynth to *mma* as described in [fluidsynth-api](http://fluidsynth.sourceforge.net/api/index.html#CreatingSynth)
