### ISSUE TITLE
Option to Clear Midi port list upon startup

### ISSUE THREAD

**Issue by spamatica** [muse-sequencer/muse#357]
Pasted from Linux musician forum.

Can I offer a suggestion? I'd like to clear all the list of MIDI ports/devices from the list upon starting up MusE. Can you provide an option for that?

I like to keep things organized with a blank slate. The workaround is to stop all the JACK-MIDI clients, which means exit ZynAddSubFX, stop ALSA MIDI Bridge, and everything until all the MIDI connections are all cleared up under the Device Name column (yes, even 10+ LV2/VST plugins in Carla). I like having a clean slate to work with, adding any MIDI connections as I need to. Managing the list of MIDI connections after all the MIDI connections have been enumerated will become tedious to work with.

--Grayson Peddie

**Comment by terminator356** [comment]
Hello, not sure if you got my reply a few months ago.
I am implementing this request, but it revealed a number of problems.
Here in my local working branch, the option has long since been added.
But it is the other problems which it revealed, that I am working on.
Hopefully soon the work will be done (and my efforts work OK) and I will commit 
 to a test branch which everyone can try and later can be merged with master.
Check the developer mailing list once in a while, as I post my results.
Thanks. Tim.

**Comment by terminator356** [comment]
Hi. This ability has now been in the git master for a few months.
You can disable the auto-population of Jack midi ports with command-line
 option "-F".
In addition the ALSA devices can now be loaded/unloaded at will in
 the Midi Configuration Dialog. It effectively starts/stops the entire ALSA
 driver, completely.
Note that ALSA devices cannot be 'created' or 'removed' - they are 
 just 'there' when the ALSA driver is running.

I will close this now. If any bugs let us know.
Tim.
