### ISSUE TITLE
ALSA MIDI input broken

### ISSUE THREAD

**Issue by danboid** [muse-sequencer/muse#387]
My USB MIDI keyboard is seen by amidi:

$ amidi -l
Dir Device    Name
IO  hw:2,0,0  USB Oxygen 49 MIDI 1

and it also works fine with qtractor but muse git isn't finding it.

I've not tried to use Muse in quite a while now but IIRC you used to make ALSA MIDI devices available under muse via Muse Settings -> MIDI ports. If I open the MIDI ports window then click on any ports 'device name' column, the only option I am given is 'Create JACK device'.

Alternately, if I create a MIDI track and then I click on the input routing icon, the pop-up menu says

"Warning: No Input devices!"

**Comment by danboid** [comment]
I am presuming that ALSA MIDI gets enabled in a default builld? If not, it really should be.

**Comment by danboid** [comment]
I've enabled the JACK ALSA MIDI bridge or whatever its called and MIDI works.

If Muse is JACK MIDI only now, why does the MIDI devices window have a (greyed out) 'Add ALSA' MIDI button? Is that supposed to have been or will it be removed?

I'd prefer ALSA and JACK MIDI support if possible.

**Comment by spamatica** [comment]
We changed this at one point, 2.1 maybe, so JACK midi is the default and
ALSA midi must be enabled. Currently this is only done with a command line
switch -A.
The reason for not having both enabled is that you get duplicates in the
device list for each alsa device.

I know this is a bit confusing and I'm open to suggestions on how to handle
this better.

2015-11-18 20:46 GMT+01:00 danboid <notifications@github.com>:

**Comment by terminator356** [comment]
On November 18, 2015 11:53:36 AM spamatica wrote:
> We changed this at one point, 2.1 maybe, so JACK midi is the default and
> ALSA midi must be enabled. Currently this is only done with a command line
> switch -A.
> The reason for not having both enabled is that you get duplicates in the
> device list for each alsa device.

Correct. It is not a good idea to have both listed at once.

Note that currently the -A switch simply ADDS ALSA devices to the list
 along with Jack Midi devices.

As noted above, that is not really a good idea, to mix them.

So I WILL be making a minor fix:
With the -A switch, ONLY ALSA devices will be auto-populated at startup.

You may still create Jack Midi devices as you wish, but they will no longer
 automatically appear alongside ALSA devices, using the -A switch.

> 
> I know this is a bit confusing and I'm open to suggestions on how to handle
> this better.

Same here.

> 2015-11-18 20:46 GMT+01:00 danboid <notifications@github.com>:
> > I've enabled the JACK ALSA MIDI bridge or whatever its called and MIDI
> > works.
> > 
> > If Muse is JACK MIDI only now, why does the MIDI devices window have a
> > (greyed out) 'Add ALSA' MIDI button? Is that supposed to have been or will
> > it be removed?

Because currently you cannot create your own MusE ALSA devices.
They are just 'there'.

However I am working on this, as you can tell by the 'Add ALSA' button.

ALSA and Jack Midi are two VERY different beasts in MusE.

I am trying to unify it more, though.

----
Technical info:
ALSA allows you to create just ONE client, and access the entire outside
 ALSA world using ADDRESSES with this just one client.

This is the mode we currently use.
Thus you currently cannot 'create' more clients, there is just the 'one'.

But after inquiring for advice on ALSA dev lists, I've decided to 
 think about allowing MULTIPLE ALSA clients in MusE.

Thus you would have a choice in how you work with ALSA in MusE -
 single or multiple clients.
Our ALSA support would become more similar to our Jack Midi support,
 allowing you to create your own MusE ALSA devices.

Displaying these outside world 'addresses' is another matter.
I envision it as similar to how we display Jack Midi ports.

I am working on schemes...
----

Tim.

**Comment by terminator356** [comment]
On November 18, 2015 03:32:39 PM you wrote:
> On November 18, 2015 11:53:36 AM spamatica wrote:
> > We changed this at one point, 2.1 maybe, so JACK midi is the default and
> > ALSA midi must be enabled. Currently this is only done with a command line
> > switch -A.
> > The reason for not having both enabled is that you get duplicates in the
> > device list for each alsa device.
> 
> Correct. It is not a good idea to have both listed at once.

Ehm, clarification:

Not a good idea to have BOTH ALSA and Jack Midi MusE devices
 pointing to the SAME physical device or application port.

However, for applications or physical devices that DO NOT use Jack midi
 and only support ALSA, being able to list both ALSA and Jack Midi
 devices in MusE is certainly desirable !

So after reexamining that 'Add ALSA' button I now realize your
 original frustration - it SHOULD just add something or offer a list,
 even WITHOUT having to specify the -A switch.

So hang in there, work was already continuing in that midi configuration
 dialog anyway, I'll see what I can come up with to ease the pain.

Tim.

**Comment by terminator356** [comment]
On November 18, 2015 09:34:38 PM Tim wrote:
> So after reexamining that 'Add ALSA' button I now realize your
>  original frustration - it SHOULD just add something or offer a list,
>  even WITHOUT having to specify the -A switch.
> 
> So hang in there, work was already continuing in that midi configuration
>  dialog anyway, I'll see what I can come up with to ease the pain.

Hookay... Check it out now in the GIT master:

The MusE ALSA Midi driver can now be started and stopped at will :-)

From the Midi Configuration dialog, click the 'add ALSA' button on or off.

*Bonus: When announcing my recent merges I totally forgot to mention this:
Besides Jack ports, ALSA ports and devices are also now PERSISTENT.
That is, unplug an ALSA USB midi device and we remember it.

Should you desire to purge such 'unavailable' ALSA devices, click 'remove'.


Be aware that ALSA midi and Jack midi behave quite different in MusE.
You currently can't create or rename your own ALSA devices - they are
 'just there' and they 'just work' automatically appearing and disappearing
 from the list, through the magic of ALSA.


Few quirks: 
May have to press 'add ALSA' twice at first depending on -A switch. 
Working on meaning of -A switch and port list filling.
Working on multiple selections in the list. 
'Unavailable' device state sometimes when it's really 'Closed' or 'OK'. 
(Try the device anyway, reassign it to a port, or hit that button again.)

Tested: Pretty darn stable loading and saving with persistence, 
 and playing and recording all while toggling the 'add ALSA' button !


Have mercy... it's brand new.

Tim.

**Comment by danboid** [comment]
Thanks for the update Tim!
