### ISSUE TITLE
LV2  effects listed under 'Add Synth' menu

### ISSUE THREAD

**Issue by danboid** [muse-sequencer/muse#390]
Why is there a 'LV2 (effects)' sub-menu of the 'Add Synth' context menu? Seeing as most LV2 FX cannot generate a sound by themselves they're not synths are they?

**Comment by terminator356** [comment]
On November 18, 2015 05:01:13 PM danboid wrote:
> Why is there a 'LV2 (effects)' sub-menu of the 'Add Synth' context menu?
> Seeing as most LV2 FX cannot generate a sound by themselves they're not
> synths are they?
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/muse-sequencer/muse/issues/390

It's because they may accept midi, and we currently have no way
 to pass midi to a track's effects rack unit.
The only way currently is to make the effect a synth track so that
 it can be controlled by midi.
Creating a new menu heading "Add Effect" would not make sense I think,
 because technically at this point, the effects /are/ synth tracks.
Unless we want to create a new kind of track: "Effect Track".
Or rename our "Synth" Tracks to "Synth/Effect" Tracks...

Instead, I am examining new ways to pass midi (and audio) controls 
 to and from the rack effects, possibly including a new type of route: 
Control Route

This would also allow routing the control OUTPUTS from an effect or synth
 to some other control input.
Like working with compressor side-chaining and so on.

Tim.

**Comment by danboid** [comment]
Thanks for the explanation Tim but then why are there no LADSPA FX under the 'Add Synth' menu then too?

**Comment by terminator356** [comment]
On November 18, 2015 05:58:19 PM danboid wrote:
> Thanks for the explanation Tim but then why are there no LADSPA FX under the
> 'Add Synth' menu then too?
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/muse-sequencer/muse/issues/390#issuecomment-157923072

LADSPA does not use midi.

That's why DSSI was invented  ;-)

And then LV2.

So we get away with simply putting LADSPA effects in the effects racks,
 with no separate tracks required.

Tim.

**Comment by danboid** [comment]
Oh yeah! I forgot that LADSPA is audio only.

Makes sense now so I think I'll close this one.

Thanks Tim!
