### ISSUE TITLE
vertical zooming

### ISSUE THREAD

**Issue by danboid** [muse-sequencer/muse#391]
It would be nice to be able to easily vertically scale (ie zoom in and out of) all the tracks in the arranger.

Ideally there should be a mini vertical zoom scrollbar to match the one we already have for the horizontal axis in the arranger and it should have a suitable mouse/keyboard binding too. 

CTRL & scroll wheel zooms horizontally so it would make sense to me if SHIFT & CTRL (or ALT & CTRL) and scroll wheel controlled the vertical zoom.

**Comment by terminator356** [comment]
On November 18, 2015 05:31:14 PM danboid wrote:
> It would be nice to be able to easily vertically scale (ie zoom in and out
> of) all the tracks in the arranger.
> 
> Ideally there should be a mini vertical zoom scrollbar to match the one we
> already have for the horizontal axis in the arranger and it should have a
> suitable mouse/keyboard binding too.
> 
> CTRL & scroll wheel zooms horizontally so it would make sense to me if SHIFT
> & CTRL (or ALT & CTRL) and scroll wheel controlled the vertical zoom.
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/muse-sequencer/muse/issues/391

Agreed.
Adjusting the actual height of the tracks was the only thing
 holding me back when I did all that zooming stuff a while back.

One problem is that the zoom must be applied as a scaling /factor/
 to the track heights, /without/ altering the tracks' height properties, 
 otherwise their original heights are lost and cannot be returned to.
 
Tim.
