### ISSUE TITLE
Parts should be pasted into selected track, not necessarily the one it was copied from

### ISSUE THREAD

**Issue by danboid** [muse-sequencer/muse#410]
If I select a part in the arranger and copy it then select another track (and maybe a diiferent time too) muse currently pastes the new part into the same track it was copied from instead of pasting it into the currently selected track (at the playhead position) as you'd expect.

**Comment by danboid** [comment]
We should keep the arranger's copy / paste behavour as it is (ignoring the currently selecte track)  if the user is copying parts spanning multiple tracks, but when only copyiing a part (or parts) from one track, it should be pasted into the currently selected track.

**Comment by terminator356** [comment]
On November 25, 2015 09:58:49 AM danboid wrote:
> We should keep the arranger's copy / paste behavour as it is (ignoring the
> currently selecte track)  if the user is copying parts spanning multiple
> tracks, but when only copyiing a part (or parts) from one track, it should
> be pasted into the currently selected track.
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/muse-sequencer/muse/issues/410#issuecomment-159688127

Then the behaviour would become inconsistent.

The primary duty of a regular paste is to paste to the same track(s) 
 that were copied from.

There are many times when the track copied from is NOT the one currently
 selected. Therefore, /requiring/ users to select the desired paste-to track 
 /before/ pasting with normal Ctrl-V, is a hassle. 

The current behaviour was arrived at after many hours of song composition 
 with frustrating 'wrong pastes' to the wrong track simply because another 
 track happened to be selected.
 
Thus we have several paste options.
You just have to remember the right key combination - simply hold 
 the shift key along with Ctrl-V.

Note that it is not practical, or desirable, to /always/ automatically select 
 the track that a selected part is on.
Users may not /want/ the current selected track to change simply because
 for example they right-clicked a part and clicked 'copy'. 
So we don't alter the current selected track in that particular case, 
 or a few others. 
So the current Ctrl-V paste behaviour was the most reasonable solution.

Tim.

**Comment by danboid** [comment]
Ah OK!

I didn't know about SHIFT+CTRL+V pasting and that pastes how I want.

Thanks Tim!
