### ISSUE TITLE
audio import prob

### ISSUE THREAD

**Issue by danboid** [muse-sequencer/muse#414]
If I open muse then go to File -> Import wave file, choose an audio file that's not at the correct samplerate, say 'Yes' to converting it and then I use all the 'Create Project' defaults except for giving it a new project name, the file fails to be imported.

Whilst I'm thinking about it, I'd suggest we change this menu item to be called

"Import Audio File"

because it can import FLAC and ogg files as well as .wav files.

**Comment by danboid** [comment]
If I accept the default project name, audio import works.

**Comment by danvd** [comment]
Hi Dan,
`Whilst I'm thinking about it, I'd suggest we change this menu item to be called
"Import Audio File"
because it can import FLAC and ogg files as well as .wav files.`

This is done.

About the first question - I tried to import audio file with project name cleared and changed to something else - import continues with no errors.

Can you make a video of your case?

**Comment by danboid** [comment]
https://youtu.be/o1tP7jS8vpA

https://youtu.be/RKMMFJh5xdA

**Comment by danvd** [comment]
Got it. 
Problem is fixed now (test needed).

**Comment by danboid** [comment]
Yep, seems OK to me now!

Thanks Andrew!

**Comment by danvd** [comment]
Hi Dan,

So, what's next by priority?

**Comment by danboid** [comment]
Hi Andrew

If it's up to me I'd like to see  'Abort and restart recording shortcut' ie #384 implemented next.

Thanks for asking Andrew!
