### ISSUE TITLE
mixer clipping warning 'LED'

### ISSUE THREAD

**Issue by danboid** [muse-sequencer/muse#420]
The MusE mixer strips don't currently seem to have a little red 'LED' icon that shows you when a channel's input is clipping. Conventionally these get illuminated when the input exceeds 0dB and it gets toggled back to its off state (none-red / black) when you click it.

**Comment by danvd** [comment]
It's interesting, that 'clipping' code is commented in meter's source file. Don't know the reason yet, but will try to find it.

**Comment by terminator356** [comment]
On December 30, 2015 05:25:27 AM Andrew wrote:
> It's interesting, that 'clipping' code is commented in meter's source file.
> Don't know the reason yet, but will try to find it.
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/muse-sequencer/muse/issues/420#issuecomment-167998511

I think you mean the drawing 'clipper', which was an old Qt3 experiment 
 in double-buffered meter drawing.

If you add something, be careful of speed with the meters, 
 they're designed to be fast, and I noticed recently could be even faster.

Tim.

**Comment by danvd** [comment]
Thanks Tim for saving my time :). Ok. When I start I'll use profiler to check difference in performance.

**Comment by terminator356** [comment]
On December 30, 2015 08:10:16 AM Andrew wrote:
> Thanks Tim for saving my time :). Ok. When I start I'll use profiler to
> check difference in performance.
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/muse-sequencer/muse/issues/420#issuecomment-168025405


Sorry, slight correction: The clipper and the double-buffering
 are two different things that were experiments, both disabled.

They can be safely removed now after all this time has passed.

If I need to refer to the double-buffering code I'll just look it
 up in old branches. Qt4 introduced automatic double-buffering anyway.

**Comment by danvd** [comment]
Tim, are you planning to merge mixer_makeover with master? Clipping led changes will touch audio mixer strips code, but you've already made lots of changes here.

**Comment by terminator356** [comment]
On December 30, 2015 02:54:06 PM Andrew wrote:
> Tim, are you planning to merge mixer_makeover with master? Clipping led
> changes will touch audio mixer strips code, but you've already made lots of
> changes here.
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/muse-sequencer/muse/issues/420#issuecomment-168090395

Well, yes, if you guys like it so far.

I don't see any major problems moving forward, the idea seems good
 and workable so far, I hope? Noble at least?

I still need to show the strip in the arranger and drum editor and so on.

If I should merge sooner rather than later, or even merge at all,
 I'd like consensus to do so.

Robert?

Thanks.
Tim.

**Comment by danvd** [comment]
I vote for merge as quickly as you can ;). Hands up for progress and new features!

**Comment by spamatica** [comment]
Yep, I'm all for merging :)
And add back your sliders too Andrew :)

2015-12-31 7:59 GMT+01:00 Andrew <notifications@github.com>:

**Comment by danvd** [comment]
> And add back your sliders too Andrew :)
Hmm, I saw Tim also coded a remake of them in mixer_makeover, so waiting for his feedback too :)

**Comment by terminator356** [comment]
On January 1, 2016 07:26:35 AM Andrew wrote:
> > And add back your sliders too Andrew :)
> 
> Hmm, I saw Tim also coded a remake of them in mixer_makeover, so waiting for
> his feedback too :)
> 
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/muse-sequencer/muse/issues/420#issuecomment-168313015

Happy MusE year!
Any hang... ov... ers?


OK Will commit soon today...

For the volume sliders:
Yeah I did a major rework of our existing sliders,
 not the ones Andrew added. Still rough looking.

I will increase the markings on the scales.

We will settle on slider width and colours and so on.

I will try to add the ability to use a bitmap for the thumb
 like Andrew's, but...

You'll see that to save space I put the markings on /top/ of the thumb.
So I am trying to make a thumb that is at once 'clear' to let the scale 
show through, yet opaque enough to distinguish clearly.

In my mind, I had the idea of the look of a rectangular 'clear plastic '
 thumb which travels on /top/ of the scale like I've seen in some hardware.

Ah well, cosmetics. We can tweak it later. Should be workable in theory.

Tim.

**Comment by danboid** [comment]
Glad to hear this is happening in time for 3.0!

Hows it looking Tim?

**Comment by danboid** [comment]
git log makes it look like the new mixer code has been committed but the mixer in my latest build looks identical to the old one. Is this new mixer only (currently) revised under-the-hood, no UI changes yet?

**Comment by danvd** [comment]
the most noticable difference is that knobs are replaced with horizontal sliders.

BTW, some discussions are taking place at muse developer list. You can subscribe to it here:
https://lists.sourceforge.net/lists/listinfo/lmuse-developer

Tim likes to post to this list :)

**Comment by danboid** [comment]
I see!

Sorry I wasn't subscribed to the dev list until now! It didn't occur to me :)

**Comment by danvd** [comment]
Dan,
there can be several variants of 'clipping led'. The one I wan t to choose is a small text label with real-time updating peek numerical value, which changes background to red when absolute amplitude value of any sample exceeds 1.0

I want to start now, so if you think different, or simply don't like how I want to make it, please write your method :)

**Comment by danboid** [comment]
That sounds good to me!

Thanks Andrew!

**Comment by danvd** [comment]
Hi Dan, all,

Well, now new  'clipping led' code is ready for testing!

It was one of the most interesting things to implement - 95% of time was spent on drawing optimization :D. As a result - on my computer, mixer with > 20 audio strips produces no more than 1% CPU overhead in debug mode :).

So, happy testing. 
Waiting for your results.

Regards,
Andrew.

**Comment by danboid** [comment]
That's great news Andrew and I'm happy to hear you enjoyed writing it!

It's already past my bed time as tomorrow is only my second day at a new job so I should really be asleep already!

I'll test it tomorrow night.

Thanks again! :D

**Comment by danboid** [comment]
Excellent work Andrew!

That is one of my biggest issues with using MusE to record audio well and truly fixed in style! It was my birthday on Monday (the 4th) so I'm taking it as a slightly late but much appreciated birthday present! :D

**Comment by danvd** [comment]
Thanks, Dan,

I'm glad to hear this :). And happy belated birthday!

BTW, What's next?

**Comment by danboid** [comment]
Thanks Andrew!

I pre-empted your next question it seems! :D

**Comment by danvd** [comment]
Heh :). I have only 4 days remaining until my holidays will be over, so I wanted to make as much as possible until I'll return to work.

**Comment by danboid** [comment]
Good man!

It hasbeen a very productive 'holiday' for MusE! That's for sure!

I hope you actually had some time off to sit around doing nothing but relax, eat and stuff too!

You're a hero Andrew! :+1:

**Comment by terminator356** [comment]
On January 6, 2016 12:22:01 PM danboid wrote:
> Good man!
> 
> It hasbeen a very productive 'holiday' for MusE! That's for sure!
> 
> I hope you actually had some time off to sit around doing nothing but relax,
> eat and stuff too!
> 
> You're a hero Andrew! :+1:
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/muse-sequencer/muse/issues/420#issuecomment-169450264

Andrew would you mind if I reworked that ClipperLabel class?
ClipperLabel is not font, style, or external stylesheet friendly.

I believe we need to avoid embedding stylesheet code (at least stuff
 which is available through the API) although I know it is required 
 sometimes, as you showed with the scrolling menus.

Thanks.
Tim.

**Comment by danvd** [comment]
Hi Tim,

I don't mind, of course. Though can you say, what will be changed? Why I'm asking - I made images of numbers, comma, minus and 'infinity' to speed up drawing - and it really helped a lot.

But if you are talking only about stylesheets, it's ok, of course. But there is another thing: there are 2 versions of embedded numbers - black (for drawing on while background) and bold white (for red background), that's why I fixed the stylesheet - to make the label look equally on any theme. 
But anyway - I can make another pair of fonts specially for dark themes.

**Comment by danvd** [comment]
P.S. our time zones are somewhat far from each other, so ping latency is about one day - when you write - I'm sleeping :)

**Comment by terminator356** [comment]
On January 7, 2016 11:35:34 PM Andrew wrote:
> Hi Tim,
> 
> I don't mind, of course. Though can you say, what will be changed? Why I'm
> asking - I made images of numbers, comma, minus and 'infinity' to speed up
> drawing - and it really helped a lot.
> 
> But if you are talking only about stylesheets, it's ok, of course. But there
> is another thing: there are 2 versions of embedded numbers - black (for
> drawing on while background) and bold white (for red background), that's
> why I fixed the stylesheet - to make the label look equally on any theme.
> But anyway - I can make another pair of fonts specially for dark themes.
> 
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/muse-sequencer/muse/issues/420#issuecomment-169918239

One problem is we have adjustable font sizes in Settings
 and the control doesn't seem to honour them.

Another is that stylesheets might want to use their own colour scheme
 or drawing style and the control doesn't seem to mesh well with that.

I know, it's a tough thing to deal with - do we force a particular look
 on a control because that's the way we wanted it to look or do we allow
 some leeway for styles and style sheets to alter them.

I really didn't want to add yet another control in the strip.

So at the risk of upsetting you, I studied the problem intensively 
 yesterday and came up with this solution:

We draw the numbers /inside/ the meters - vertically at 90 degrees.
It just seemed an obvious thing - there is so much wasted space 
 in those meters.

I've already got it working here, small unobtrusive with the numbers
 being displayed in the red portion at the top of the meters.

And BTW that's /both/ meters so we get /both/ channels' peak readings,
 instead of the current single combined reading.

I hope this is OK with you, it's only removing the label but the rest
 of the work you did is OK - thanks for the embedded 'falling' timers BTW,
 and putting the clipped flag inside the Node code.

My concern long ago with using timers for each meter was that there 
 might be just too many of them, so I ran all of the 'falling code' from the 
 one single common heartbeat timer.
I hope there's no speed or resource penalty for using a lot of timers.

Eagerly awaiting reply. Thanks.
Tim.

PS My schedule is all over the place. It might be 12 PM or 5 AM !

**Comment by danvd** [comment]
Hi Tim,

I don't mind at all. If your implementation will be accepted by Dan, I'll of course accept it too :).

P.S. I'm reopening this issue now.

**Comment by danboid** [comment]
Tim's suggested re-working sounds good to me. I like the idea of having it alert on clipping for each channel separately for stereo tracks - I don't think I've seen that in a DAW before!

**Comment by terminator356** [comment]
On January 8, 2016 10:39:41 AM danboid wrote:
> Tim's suggested re-working sounds good to me. I like the idea of having it
> alert on clipping for each channel separately for stereo tracks - I don't
> think I've seen that in a DAW before!
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/muse-sequencer/muse/issues/420#issuecomment-170086037

Ahem.

Oh... I don't know, you take a look and decide what looks better. 

He he...

Originally I had a non-antialiased meter font for nice crisp white display.
But I had to accept working with stylesheets and made some
 crucial changes to get the Settings fonts to work, and thus now
 I cannot find a way to tell a stylesheet to use a non-antialiased font.

Argh. Any suggestions?


Anyway, I'm kind of joking about the meter text, really it's far better
 with the readout boxes, sorry for the noise Andrew ;-)

But, uh, want to keep it anyway? Make it switchable?

How about like this "hotel mode" ?  (Vertical upright.)

H
O
T
E
L

I did that once in an ASLA mixer I designed, with specific support 
 for the SBLive driver DSP designer and patch loader which I also 
 contributed to heavily several years ago.

Either way, vertical text sucks even if it is a lousy 3 meter numerals!
I'll probably remove it.

Cheers.
Tim.
