### ISSUE TITLE
Menu bug when clicking on menuitems

### ISSUE THREAD

**Issue by asbaklm** [muse-sequencer/muse#423]
When clicking on menuitems like File, Edit, Functions etc it sometimes requires two-clicks to obtain a response. This behaviour is erratic, and does not always occur. I'm not sure how to induce this behaviour but it happens from time to time. Report based on version compiled today from latest source in Mint 64 + Cinnamon window manager.

**Comment by terminator356** [comment]
On December 2, 2015 02:42:17 AM asbaklm wrote:
> When clicking on menuitems like File, Edit, Functions etc it sometimes
> requires two-clicks to obtain a response. This behaviour is erratic, and
> does not always occur. I'm not sure how to induce this behaviour but it
> happens from time to time. Report based on version compiled today from
> latest source in Mint 64 + Cinnamon window manager.
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/muse-sequencer/muse/issues/423

Yes, observed many times.
I've been trying to track this puppy but it's elusive.
I thought it may have something to do with our special
 popup menus, as it seems to happen predictably
 /after/ our popup has been closed by clicking away
 on empty space, but I'm still not sure.

Tim.

**Comment by terminator356** [comment]
On December 2, 2015 02:42:17 AM asbaklm wrote:
> When clicking on menuitems like File, Edit, Functions etc it sometimes
> requires two-clicks to obtain a response. This behaviour is erratic, and
> does not always occur. I'm not sure how to induce this behaviour but it
> happens from time to time. Report based on version compiled today from
> latest source in Mint 64 + Cinnamon window manager.
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/muse-sequencer/muse/issues/423

OMG. 

It's a Qt5 bug !

What OS are (were) you running? *Ubuntu LTR? I am.
Maybe it's fixed in more recent Qt versions?

** To all: Please verify: Please try this: 

Open any Qt5 program such as Qt5 Creator.

Click on the main menu bar to open the the menu.
Now click away on either the app's Title Bar, or the desktop,
 or another app, but not anywhere else inside the app.
The menu will disappear. Good so far.
Now click on the app's main menu bar again.
WTF? No menu !
Click again on the main menu bar, now the menu appears!


Now try the same thing with a Qt4 app. Like MusE-2.
All works OK /including/ our special popup menus ! 

Yay! 

It's weird I could swear this bug was there since 
 Qt4 days but maybe I'm just mis-remembering. 

I was really worried it was our custom popup menus. 
I started to look into the problem today.
But then was /shocked/ tonight to see it occur with 
 our Main Menu which is /not/ customized.

Tim.

**Comment by asbaklm** [comment]
Yes, running Mint 17.3 / 14.04 LTR

**Comment by terminator356** [comment]
On January 16, 2016 09:14:44 AM asbaklm wrote:
> Yes, running Mint 17.3 / 14.04 LTR
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/muse-sequencer/muse/issues/423#issuecomment-172229639

Oh. 
I hastily filed a Qt bug report.

They'll either laugh or get mad at at me for testing on Qt 5.2.1

But I searched and could find no report or fix related to this.

We'll see.

T.

**Comment by kybos** [comment]
Should be fixed now.
