### ISSUE TITLE
Option to auto-create fluidsynth plugins when importing GM MIDI files

### ISSUE THREAD

**Issue by danboid** [muse-sequencer/muse#425]
Under Arch (for example) if I have both timidity++ and timidity-freepats installed I can just run:

timidity song.mid

And it will play the file provided it is a regular GM MIDI file.

It would be great if there was a new 'Path to GM soundfont' option added to the 'MIDI ports / Soft Synths' window. When a suitable soundfont has been specified here, then the user would have a new option when importing GM MIDI files so that MusE would auto-create a MESS FluidSynth plugin instrument with the correct instrument patch already selected for every track in the MIDI file.

**Comment by asbaklm** [comment]
Hi Dan, my understanding of this issue is limited but an easy way to import and play midifiles is to set Fluidsynth in Device/Port Assignments of the MidiPorts/Softsynths menusetting and save it as a Muse template. 

Also remember to configure Fluidsynth in the Usable Devices Section of "Configure Midi Devices". I use it with the Fluid R3 GM soundfont. Each Channel in the Channel Setup is set to Fluid R3 and I set CH#10 to Drums.

Then simply open this template, import your MIDI file, add it to project and voila, you have all tracks and channels automagically mapped to Fluidsynth in Muse.

Quick and easy :)

**Comment by danboid** [comment]
Thanks for your suggestion asbakim! That's what I'll have to do if nobody decides to implement my original suggestion which is what I'd strongly prefer.
