### ISSUE TITLE
[Per-channel instruments] Assignment of IDF files to midi hardware [sf#1076083]

### ISSUE THREAD

**Issue by Windfisch** [muse-sequencer/muse#43]
Submitted by christeck on 2004-11-30 16:42:13

I like the idea of the IDF files.

Unfortunately, I can only assign IDF files to a certain MIDI hardware 
device.

But in many setups one hardware device drives multiple devices using 
different MIDI channels. E.g. in my setup I drive a Wladorf Microwave, 
an Alesis QSR, an Organ and an Access Viris Synth using the same 
USB2MIDI device which has only one jack.

So, it would be great to be able to assign an IDF file to a track in the 
inspector instead of a hardware device in the preferences.

**Comment by kybos** [comment]
Already there.

**Comment by terminator356** [comment]
Only seven years to respond!

If I understand the question, it is still not there yet. I have been asked this before.
We do not have per-channel instrument (and therefore IDF) assignment.

It can be done, yes, but it is a huge undertaking, requiring redesign of our instrument classes and structures,
 and our IDF format.

Ironically, recently I completed most of the MidiName [1] support (at least for synthesizers -
 the ability to load external MidiName files will come later).
Believe it or not, my MidiName support **does** in fact have per-channel instruments,
 because the MidiName specification demanded it.

I really wanted to overhaul our own instruments and IDF files to **natively** mirror what MidiName can do,
 but as I say above, it is a monumental task, and I could only 'shoehorn' the MidiName support along side
 our existing code. It's kind of a miracle I was able to get the support this far along.

If you don't mind, I'm going to re-open this as a reminder, as it is still a valid and desirable request.
When it could be done is hard to say.

[1] [https://www.midi.org/specifications-old/item/midi-in-xml](url)
