### ISSUE TITLE
more os

### ISSUE THREAD

**Issue by Reaper10** [muse-sequencer/muse#434]
Is there planes to bring MusE to windows?

**Comment by spamatica** [comment]
There is, or rather, was, a plan to allow MusE to work on Windows but it
isn't finished and I cannot say when and if it will be finished. There are
only so many hours to dedicate to this kind of work..
The branch platform_independence can with be made to build on windows but
the resulting MusE binary is not fully functional.


2015-12-16 22:41 GMT+01:00 Reaper10 <notifications@github.com>:

**Comment by Reaper10** [comment]
is it possible to make it for android two?

**Comment by spamatica** [comment]
2016-01-12 0:26 GMT+01:00 Reaper10 <notifications@github.com>:

> is it possible to make it for android two?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/muse-sequencer/muse/issues/434#issuecomment-170730879>
> .
>

Large parts of the infrastructure is actually quite compatible with Android
since it's based on linux, including Qt, but there will be new challenges
not the least to make MusE usable with a touch screen..
I don't think there is any current developer who would prioritize doing
this so I think we need fresh blood, a developer interested in bringing
MusE to Android.

**Comment by Reaper10** [comment]
any new on muse on windows?

**Comment by Reaper10** [comment]
#540 may
