### ISSUE TITLE
LV2 synths crash when operating controls while notes are playing

### ISSUE THREAD

**Issue by terminator356** [muse-sequencer/muse#435]
Steps to reproduce: Create an LV2 synth track such as MDAePiano or Calf Organ.
Create a midi track and assign it to the synth device.
Either arm the track and play notes from a keyboard, or create a part with notes
 and play the part. Ensure that notes are actually being played (use a loop etc).
Now adjust any generic GUI or native GUI control. 
MusE should soon crash, when adjustments coincide with notes.
The crash also happens when operating midi controls such as midi volume, 
 while notes are playing, for synths that respond to such controls such as MDAePiano.

Seems to suggest a conflict when processing the eventFIFO and playEventList ?

Related question: Might be a separate issue but I'll ask here:
As mentioned above, why do some LV2 synths not seem to respond at all 
 to midi volume, while others like MDAePiano do?

Thanks.
Tim.

**Comment by danvd** [comment]
Hi Tim!

Yes, I conrifm this. It's very bad bug. Will fix it soon.

**Comment by danvd** [comment]
Some investigation results:
This problem can be divided into 2 subproblems:
1. When gui control is touched, _controlFifo is used (direct control sent)
2. When midi strip slider is touched, _eventFifo is used. (control is sent via ME_CONTROLLER midi message)

So these are different types of one bug. I think that the reason is memory corruption in getData() method where all of the above queues are used. 

Stay tuned for more results :)

**Comment by danvd** [comment]
Found th reason - bug in class LV2EvBuf which receives and transmits midi data to plugin's midi ports. When I first started to learn lv2 specs, I ported this code from jalv.c (from c to c++) and it seems that also introduced a regression. Now I decided to rewrite it from scratch in more c++ way, because it's rather hard to debug pointer arithmetics.

**Comment by danvd** [comment]
Hi Tim,
I pushed a fix a80894a now. Can you check again?
Though it was not an ordinary fix, but a big rewrite of lv2 host midi events handling code. Now alsa deps are not used anymore. One step to support other platforms :)

Regards,
Andrew

**Comment by jensplixplox** [comment]
I just tested all LV2 synths which are available in my MusE installation. Before that I installed the latest git version of MusE.

I found out that Muse does not crash when I change the synth settings of all available LV2 synths, and when I change the volume in the connected Midi track, except for the Example metronome synth. When I change its synth settings or its Midi track volume, then MusE crashes.

What I also noticed is:

a) Calf Filterclavier, Calf Fluidsynth and Calf Rotary Speaker do not produce any sound.

b) At a certain point, when changing the synth settings, Calf Monosynth creates disturbing sounds and then no sound at all.

I have Ubuntu Studio installed on my system (where MusE is installed) with all current Ubuntu Studio updates installed. If necessary, I will provide its current version number. Currently I cannot find it out because I am running my second Linux installation on my machine, Debian 7.9 (with no MusE installed).

Regards,

Jens

**Comment by danvd** [comment]
Hi Jens,

Thanks for testing!
Will try to reproduce this behavior today. 
BTW, could you test all of the above with previous muse installation too? 

Regards,
Andrew

**Comment by danvd** [comment]
Jens,
I can't reproducy your bugs. Can you make a video (with sound) of all your bad cases?

**Comment by jensplixplox** [comment]
Hi Andrew,

You wrote:
> BTW, could you test all of the above with previous muse installation too? 

I have attached a table about my testing results for MusE git version > official 2.2.1 version, but older than oldest MusE 3 git version.

Regards,

Jens
[lv2_synths_muse_2.2.1_git_version.pdf](https://github.com/muse-sequencer/muse/files/69897/lv2_synths_muse_2.2.1_git_version.pdf)

**Comment by jensplixplox** [comment]
Hi Andrew,

You wrote:
> I can't reproduce your bugs. Can you make a video (with sound) of all your bad cases?

I will send you an email regarding this issue,

Regards,

Jens

**Comment by jensplixplox** [comment]
Sorry, I just found out that my attached table has a bad page layout. I changed its layout, here is this table again.
[lv2_synths_muse_2.2.1_git_version.pdf](https://github.com/muse-sequencer/muse/files/69905/lv2_synths_muse_2.2.1_git_version.pdf)

**Comment by terminator356** [comment]
Andrew: Fix a80894a seems to be fine, all tests OK. I'm closing.
Nice about the no ALSA platform dep thing.
(It'd be nice to remove ALSA from DSSI, but that's way harder than it sounds.)

**Comment by danvd** [comment]
Ok, I'm happy to hear this!
Thanks for testing, Tim.
