### ISSUE TITLE
Built-in parametric EQ and Compressor/limiter for all audio-producing tracks

### ISSUE THREAD

**Issue by danvd** [muse-sequencer/muse#440]
Very very nice to have.

**Comment by terminator356** [comment]
Some things I/we have talked about:
Using a plugin instead of rolling your own:
The controllers on our audio strips are built in: Volume, Pan, and hidden undeveloped Mute.
It is ironic then that one can slap an instance of Invada Input Module in a strip rack and do 
all of that, and more, right from the plugin without ever touching our own volume and pan.
With some intriguing changes, it would be possible to map any plugin to the main strip area,
 basically everything you see from the bottom of the rack down to the top of the off and record
 buttons could be replaced by controls from a plugin. And they could be selectable
 depending on things like number of track channels (see Ardour's plug-style Panner system),
style of display, compactness etc. With meters too, using plugin outputs.
We could embed some plugins in our tree (we already do), but using an external plugin 
 we would not have to sync whenever improvements occur in the plugin upstream.

How to map the controls visually to the strip area?
The entire mid-strip rectangle could be filled with a plugin's GUI. 
What GUI, you ask? Well, one solution is that MusE has its very own plugin GUI system.
Try this: Add a LADSPA "Tap Reverberator" to a strip. Open the generic MusE GUI on it.
See the controls? The enumerated list of presets? That's ours!

Anyway, just some ideas. 
Also be careful of processing time, and no/little added path latency if possible.
If there's latency, consider how to report it to MusE, maybe using a plugin, of which most can
 report it via an output, which I will be using in a future latency compensation scheme.

Cheers.
TIm.

**Comment by danvd** [comment]
Thanks for the tips, Tim. 
I'm only planning to do that. May be we should make a release before all new features like that. There are already lots of changes that can pretend for a 3.0 version :)

**Comment by terminator356** [comment]
Yes of course. I was not suggesting we do it now. But it's fun to talk about.

**Comment by Reaper10** [comment]
like mxcbus?
![mb2_mixer_4](https://cloud.githubusercontent.com/assets/8137561/17872132/485eace6-6884-11e6-9a31-a8111a47a562.jpg)
