### ISSUE TITLE
audio time stretching and beat detection

### ISSUE THREAD

**Issue by danboid** [muse-sequencer/muse#441]
This could well be one of my last feature requests for MusE because I think that when my previous requests have been implemented as well as this, MusE should do pretty much everything I currently need from a DAW. I've left this one until now as this is by far the hardest feature to implement well that I've requested for the project.

Ardour has a thing called Rhythm Ferret to time stretch audio although I've never had much luck with it personally. What has worked very well for me is the audio time stretching functionality within Tracktion (under Linux). Tracktion does a pretty decent job of auto-detecting the peaks of the beats of an audio file but quite often the beat marker nodes require some fine-tuning to get spot-on.

Audio time stretching works well enough in Tracktion that it even works when the tracks tempo is slowly increasing or decreasing and so ideally I'd like to see it work this well under MusE too.

**Comment by terminator356** [comment]
Florian (user windfisch) made a MusE branch which has all these features.
Here in git master, these features are gradually being added, but not much has happened lately.
The most important thing so far is recently MusE switched to non-shared event lists. 
That makes these features possible. (Every sndfile usage gets its own handle now.)
Also, there's a branch I started, with massive sweeping changes to prepare for features like this.
Flo used something he called extended ticks. While I was trying to keep frames and ticks
by making classes Pos and Len completely agnostic. See full details in about_this_branch.txt

For me now, a much higher priority is latency compensation in MusE. There is none.
So that comes first. I feel that will finally make MusE a worthy system with worry-free recording,
 and will warrant a proud version step. It's very important.

Tim.

**Comment by danvd** [comment]
Hi Dan,

Does this feature has any relations to Reason's rex format (from Recycle)?

**Comment by danboid** [comment]
Tim:

That's good news! I agree that latency compensation is more important than audio time stretching.

Have we decided on what will make 3.0.0 yet? Maybe I should start a forum topic for it? I'll have to make a new account as I've forgot my password (for danboid) and I couldn't see where to reset it last time I looked.

Andrew:

I haven't used Reason in a loooong time so I can't really comment. I'm sure people would love some kind of Reason compat. in MusE if their file formats are documented but I'd expect thats not the case.

**Comment by danvd** [comment]
3.0.0 is actually a master branch. We will just tag it at some moment to freeze current changes and name it muse_3_0_0 or so. So all current features will go to 3.0.0.

**Comment by danvd** [comment]
Dan, I can reset your forum's password when you'll be ready to change it.

**Comment by danboid** [comment]
Maybe I worded my question wrong. There must be at least 20 unimplemented MusE feature requests on GH. I would presume you want to fix all known bugs for the next stable release but how many of the unimplemented feature requests are likely to make it into the next release? What will have to wait?

**Comment by danvd** [comment]
Aha, I think that now many useful features are implemented and we can make 3.0.0 release from current state, but before that find and fix new bugs (if any). All major new feature requests should go to the next stable release (3.0.1 of 3.1 etc..)
