### ISSUE TITLE
no noteoff when looping back

### ISSUE THREAD

**Issue by derselbst** [muse-sequencer/muse#444]
Currently, whenever the player loops back, all notes are killed. in my opinion this shouldnt be the case. Usually when working with loops, notes are arranged as seen in Track1. If a note is still on when the player loops back, this note will be killed whenever a corresponding noteoff event at the beginning of the loop is sent, as seen in Track2. In case of Track3 nothing will happen anyway.

In summary, if the composer really wants a noteoff when looping back, he should arrange his note(s) just like in Track1.

![loop-example](https://cloud.githubusercontent.com/assets/8152480/12020676/56b0fc2e-ad7f-11e5-8bac-f58b098baacc.png)

Opinions?

**Comment by danvd** [comment]
So you suggest to not to send note-offs if note began before end loop marker but should end after it?

**Comment by spamatica** [comment]
How does other softwares handle this, anyone know?

2015-12-28 17:46 GMT+01:00 Andrew <notifications@github.com>:

**Comment by derselbst** [comment]
@danvd Yeah, I would suggest not to send noteoffs if a note began right before end loop marker. From my understanding a loop shall only set the playhead back to the loop start marker. From there we continue grabbing the events and send them to whoever wants to know. If we grab a noteoff event and by that kill a note that has been started before we looped back, it is probably due to composers intention. Else if this note continues to play, since we looped back before we grabbed the noteoff event, it is the composers fault (or intention), so let him deal with the situation. --> We are only moving the playhead...

**Comment by derselbst** [comment]
@spamatica Rosegarden and Qtractor kill the notes when they are looping back

**Comment by danvd** [comment]
I can test this behavior in logic pro on os x. Will write when get a result.

**Comment by terminator356** [comment]
On December 28, 2015 07:29:36 AM Tom M. wrote:
> Currently, whenever the player loops back, all notes are killed. in my
> opinion this shouldnt be the case. Usually when working with loops, notes
> are arranged as seen in Track1. If a note is still on when the player loops
> back, this note will be killed whenever a corresponding noteoff event at
> the beginning of the loop is sent, as seen in Track2. In case of Track3
> nothing will happen anyway.
> 
> In summary, if the composer really wants a noteoff when looping back, he
> should arrange his note(s) just like in Track1.
> 
> ![loop-example](https://cloud.githubusercontent.com/assets/8152480/12020676/
> 56b0fc2e-ad7f-11e5-8bac-f58b098baacc.png)
> 
> Opinions?
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/muse-sequencer/muse/issues/444

Not sure if this helps or if you saw it, but the Transport window 
 (is the only window which) has Loop Mode boxes such as overwrite,
 erase etc. Tried it?

I was the last one to do major work in this looping area years ago,
 and I do know that there was an issue or two left that I had 
 difficulty resolving. I think they may have involved overwrite mode 
 not behaving quite as one would expect. Can't remember.

Tim.

**Comment by derselbst** [comment]
@terminator356 You mean cycleMode? It provides normal, replace and mix. Tried all three, but no observable difference. To me it is not clear why it is labelled as *cycle rec* in transport window? Seems to be handled at [/muse/midi.cpp:287](https://github.com/muse-sequencer/muse/blob/dc663109e4f3c35fb4126089e6cb95ebce29941f/muse3/muse/midi.cpp#L287)

**Comment by derselbst** [comment]
This is the code actually responsible for killing notes whenever looping or seeking: [/muse3/muse/mididev.cpp#L759](https://github.com/muse-sequencer/muse/blob/f33b92e5bc1ac7659ea4dc5ceec277432d270413/muse3/muse/mididev.cpp#L759)

Any news how Logic Pro deals with this issue?

**Comment by terminator356** [comment]
On January 15, 2016 12:49:45 PM Tom M. wrote:
> This is the code actually responsible for killing notes whenever looping or
> seeking:
> [/muse3/muse/mididev.cpp#L759](https://github.com/muse-sequencer/muse/blob/
> f33b92e5bc1ac7659ea4dc5ceec277432d270413/muse3/muse/mididev.cpp#L759)
> 
> Any news how Logic Pro deals with this issue?
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/muse-sequencer/muse/issues/444#issuecomment-172088999

I wasn't quite sure what your original request was until you
 pointed to the code. 

So you're talking about actual /playback/ of notes while loop is on,
 not necessarily while in record mode and issues that happen when
 recording the notes (which I was referring to before)?

My first thought is what will actually turn off the notes (besides stopping)?
Upon the first loopback it will come across the same notes and
 try to turn them on again but they haven't been turned off.

Therefore we would have to completely ignore them.
('Completely' means that because a note is an Event it encapsulates
 both a note on and note off. So we'd ignore the whole event.)

That means when we come across these notes we'd have to look them up in 
 the stuck notes EventList to see if they were already on, and ignore them. 

This means perpetually stuck notes while looping in /this/ particular  
 scenario, right?

Like continually held chords at the end of a song which loops back
 a few bars at the end?
("The composer wanted it that way" as you say.)

Note: I have seen some synthesizers actually 'pile up' notes,
 increasing apparent note volume if they receive multiple note-ons
 with no corresponding note-offs. Others don't. Consider that some
 might use that. 

Come to think of it I wonder if aftertouch is affected here.
Ah yes, and then the all-important headache-inducing /sustain/ controller:
At the moment of loopback we'd have to leave that... 
On?
At the last value? 
Reset to off?
Reset to the value at the loop begin point?

(I'm still studying your track pic! It'll become clearer later I think.)


OT but related: 
------
I mentioned once I wanted to introduce 'jumping'.
Not just looping... actual jumping! 
Using the marker system. Adding some features.
Markers could simply be 'jump commands' holding a position
 to another marker!

Expanding further, Markers could be 'jump to sub-routine' commands,
 and conversely could also be 'return from sub-routine' commands.
And with a 'repeat the sub-routine N times' value.

Think about it.

Your song a bit too long? Need to trim it but don't want to 
'cut and paste and move' entire middle-sections out of the way?
Jump!

Got sections you'd like to repeat? Al coda? N times? Infinite fade?
Jump!
Sub!

Maybe Florian's Score Editor could use the Coda, Al Coda concept.

One drawback is, all of this stuff is laid out on a linear timeline!
Makes it hard to access.
Maybe separate mini-arranger holding favourite whole sub-routine sections.
Multiple arrangers?

Thanks for your help Tom.
Tim.

**Comment by derselbst** [comment]
> So you're talking about actual /playback/ of notes while loop is on...

Yes, exactly what I meant, not record related at all.

> Upon the first loopback it will come across the same notes and try to turn them on again but they haven't been turned off. Therefore we would have to completely ignore them. ('Completely' means that because a note is an Event it encapsulates both a note on and note off. So we'd ignore the whole event.) That means when we come across these notes we'd have to look them up in the stuck notes EventList to see if they were already on, and ignore them.

Ok, good to know.

> This means perpetually stuck notes while looping in /this/ particular scenario, right?
> Like continually held chords at the end of a song which loops back a few bars at the end? ("The composer wanted it that way" as you say.) 

Yeah, exactly.

> /sustain/ controller: At the moment of loopback we'd have to leave that... On? At the last value? Reset to off? Reset to the value at the loop begin point?

Good point, hard to say but I would just leave it at its last value?
