### ISSUE TITLE
Add support for native vst FX

### ISSUE THREAD

**Issue by danvd** [muse-sequencer/muse#448]
Now only instruments are supported

**Comment by danvd** [comment]
Hi All,
Implemented this in 044cd39.
There are lots of files changed, so it better to run 'make clean' before compile.

I'm closing this issue now, but, if something will not work, we can always reopen it.

P.S. All functionality of native vst synths is supported.

**Comment by asbaklm** [comment]
Hi Andrey, thanks a lot!

I tested with new source, there still are some problems.

- Add Synth section

In "add synth", no native Linux FX VST plugins are shown on my system, except for one reverb plugin by drowaudio because it is currently being mis-detected as a Native Linux VST synth.

No dssi-vst FX plugins are shown.

Problem Summary: 
In add synth, no dssi-vst FX plugins and no Linux Native VST FX plugins are shown.


- Effects Rack

When going to effect rack, dssi-vst FX plugins are present. Working. :+1: 
When going to effect rack, Native Linux VST FX are not present. Not working.

Problem Summary: No native Linux VST FX present in the Effects rack.

**Comment by danvd** [comment]
Hi @asbaklm,

Can you repost your installed list of native vst plugins here? I'll check them.

**Comment by asbaklm** [comment]
Here are the Native VST FX plugs 
(there may be some synths, apologies if I missed removing those)

AmplitudeImposer-vst.so
carla.vst
CycleShifter-vst.so
drowaudio-distortionshaper.so
drowaudio-distortion.so
drowaudio-flanger.so
drowaudio-reverb.so
drowaudio-tremolo.so
EasySSP.so
eqinox.so
GBand.so
GChorus.so
GClip.so
GComp2.so
GComp.so
GDelay.so
GDuckDly.so
GFader.so
GForm.so
GGain.so
GGate.so
GGrain.so
GHi.so
GLFO.so
GLow.so
GMax.so
GMonoBass.so
GMulti.so
GNormal.so
GPitchGate.so
GRect.so
GRevDly.so
GSatMax.so
GSnap.so
GSpace.so
GStereo.so
GTriChorus.so
GTriGate.so
GTune.so
JackAssFx.so
JackAss.so
JuceDemoHost.so
JuceDemoPlugin.so
LUFSMeterMulti.so
LUFSMeter.so
Luftikus.so
PitchedDelay.so
SAFECompressor.so
SAFEDistortion.so
SAFEEqualiser.so
SAFEReverb.so
SoulForce-vst.so
StereoSourceSeparation.so
TAL-Dub-3.so
TAL-Filter-2.so
TAL-Filter.so
TAL-Reverb-2.so
TAL-Reverb-3.so
TAL-Reverb.so
TAL-Vocoder-2.so
TheFunction.so
ThePilgrim.so
ZamAutoSat-vst.so
ZaMaximX2-vst.so
ZamComp-vst.so
ZamCompX2-vst.so
ZamDelay-vst.so
ZamEQ2-vst.so
ZamGate-vst.so
ZamGateX2-vst.so
ZamGEQ31-vst.so
ZamHeadX2-vst.so
ZamTube-vst.so
ZaMultiComp-vst.so
ZaMultiCompX2-vst.so

**Comment by danvd** [comment]
Hmm, strange, I have some of these plugs installed, and they are present in the list. 
can you make a video your muse session?

And I'll check other plugs from your list

**Comment by asbaklm** [comment]
Here it is  
[muse3_vst_fx.ogg.zip](https://github.com/muse-sequencer/muse/files/76354/muse3_vst_fx.ogg.zip)

On AddSynth menu, there are no native VST FX or DSSI-VST FX
On effect rack the DSSI-VST FX are there but no native VST FX

env | grep VST
VST_PATH=/usr/local/lib/vst:/usr/lib/vst:/home/asbak2/.vst

**Comment by danvd** [comment]
Hi @asbaklm,

Just pushed a fix for this error. Probably it was not a error, but a filter: support code for vst plugins filtered only those plugs, that can receive midi events. Now all plugins are supported.
Commit 8e99a58.

Can you update and recheck?

**Comment by asbaklm** [comment]
Privet Andrey!

Just checked, it is interesting change.

- Add Synth Menu
-----------------------

Now I can see Native VST Effects under the "Add Synth Menu" (It didn't exist before). 
Quickly tested loading / unloading of VST FX plugs, it seems to work.

- Summary: VST Effects at Add Synth Menu seems to work    :+1: 


Effect Rack has many VST plugs missing:
---------------------------------------------------

- Summary: In Effect rack, many VST FX plugins are not showing up.

Partial list of missing plugins

AmplitudeImposer-vst.so (missing)
CycleShifter-vst.so (missing)
drowaudio-distortionshaper.so (missing)
drowaudio-reverb.so  (detected as synth, but it is an effect)
drowaudio-tremolo.so (missing)
GBand.so (missing)
GChorus.so (missing)
GClip.so (missing)
GComp2.so (missing)
GDelay.so (missing)
GForm.so (missing)
GLFO.so (missing)
GLow.so (missing)
GMax.so (missing)
GMulti.so (missing)
GPitchGate.so (missing)
GRevDly.so (missing)
GSnap.so (missing)
GSpace.so (missing)
GTriGate.so (missing)
JackAssFx.so (missing)
JackAss.so (missing)
LUFSMeter.so (missing)
Luftikus.so (missing)
PitchedDelay.so (missing)
SAFEDistortion.so (missing)
SoulForce-vst.so (missing)
StereoSourceSeparation.so (missing)
TAL-Filter-2.so (missing)
TheFunction.so (missing)
ZamAutoSat-vst.so (missing)
ZamCompX2-vst.so (missing)
ZamDelay-vst.so  (missing)
ZamGateX2-vst.so (missing)
ZamHeadX2-vst.so (missing)
ZaMultiComp-vst.so (missing)
ZaMultiCompX2-vst.so (missing)

**Comment by danvd** [comment]
Ok, this sounds promising :)
Moving forward...

**Comment by asbaklm** [comment]
hehe :)

**Comment by danvd** [comment]
I have some of these plugins installed and theay are in the list:
![image](https://cloud.githubusercontent.com/assets/5666218/12078464/c55a9f64-b224-11e5-99c0-afaff7596b07.png)

**Comment by danvd** [comment]
I made a little demo of working native vsts:

[MusE_NativeVST-2016-01-03_15.35.02.mkv.zip](https://github.com/muse-sequencer/muse/files/76573/MusE_NativeVST-2016-01-03_15.35.02.mkv.zip)

**Comment by asbaklm** [comment]
Thanks Andrey

Glenn Medeiros? :dancers: 

It seems to me that something is behaving strange with the plugins on the effects rack because it seems to be detecting different VST FX plugins on different user systems.

- Some differences I notice between yours and mine in muse3 effect rack where we have the same plugin suites installed:

On yours, drowaudio flanger is missing. On mine it is present.
On yours, Luftikus is present and on mine it is missing.
On yours, Tal-Filter-2 is present, on mine it is missing.
On yours, Tal-Reverb 3 is missing, on mine it is present.

I have all these plugins installed, and they work and show up in the muse Add Synth menu. They also show up in Carla. 

The previous list contains the plugins which are missing in the Muse Effect Rack on my system.

The strange thing is that the missing plugs are present in the Add Synth section.

**Comment by danvd** [comment]
Interesting :). Let's do an experiment - attach your zipped missing vst .so plugins here - I'll test them on my system.

**Comment by asbaklm** [comment]
Here are the plugs from the Zamaudio and GVST sets (some of the other plugins were quite big)

Another weird thing I just noticed, in your screenshot of plugs, drowaudio flanger is present, but if you look at your video, it is missing! :D


[zam_gplugs.zip](https://github.com/muse-sequencer/muse/files/76586/zam_gplugs.zip)

**Comment by danvd** [comment]
I hope this bug is finally fixed in a501b67!

Can you make new tests?

**Comment by asbaklm** [comment]
I tested plugin loading and it looks like it's working!! (I didn't test audio yet.)

Fantastic work Andrey, this was quite a difficult problem to resolve.

**Comment by danvd** [comment]
Ok! Pleased to hear that the problem is solved. 
Make your tests with audio and, if something will go wrong, we will reopen this issue.

Now closing it.
