### ISSUE TITLE
Muse Settings: Configure Midi Devices: Device Port Assignments: Port selection bug

### ISSUE THREAD

**Issue by asbaklm** [muse-sequencer/muse#467]
Muse crashes when Port 1: Def Out Chn is set to 'none'

**Bug Summary** - Conditions to reproduce it
Muse Settings: Configure Midi Devices, Midi Ports and Synthesizers
Device Port Assignments
Navigate to Port 1 (Move slider to the top)
Click on Def Out Channel
Set it to 'none'
Muse Crashes

**Comment by asbaklm** [comment]
Update:

This behaviour is caused by #468, if LD_LIBRARY_PATH setting was exported without /usr/local/lib before starting muse3

**Comment by asbaklm** [comment]
Closing

**Comment by terminator356** [comment]
On January 29, 2016 03:00:14 AM asbaklm wrote:
> Muse crashes when Port 1: Def Out Chn is set to 'none'
> 
> **Bug Summary** - Conditions to reproduce it
> Muse Settings: Configure Midi Devices, Midi Ports and Synthesizers
> Device Port Assignments
> Navigate to Port 1 (Move slider to the top)
> Click on Def Out Channel
> Set it to 'none'
> Muse Crashes
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/muse-sequencer/muse/issues/467


[Reference to bug #468 and #466 as well:]

Hi. Bug 468 may be related to this.

The problem is that this column should never allow 
 all rows to say 'none'. That is, there should always
 be one row that doesn't say 'none'.

If all rows say 'none', bad things can happen where
 upon adding a new midi track its output route is invalid,
 which may cause a crash. So #468 may be related here.

I saw problem this when I fixed #466. You'll notice I changed
 the popup menu slightly, but I don't think I got around to solving
 this particular issue and I got side-tracked.

So for now, please ensure that one row in that dialog 
 has a valid number in that column like '1', before adding
 any midi new tracks. Also avoid the 'apply to all tracks now'
 option if no row has a valid number.

Thanks.
Tim.

**Comment by asbaklm** [comment]
Thanks a lot Tim
