### ISSUE TITLE
BSD support

### ISSUE THREAD

**Issue by danboid** [muse-sequencer/muse#473]
I don't think any of the MusE devs run BSD so I don't know if there is any interest in getting MusE running under *BSD but I think it'd be cool for MusE to run on as many platforms as possible - certainly at least the BSD family as they shouldnt be too hard to support compared to say Windows. There seems to be some kind of (intended) support for OSX in the CMake files already. OSX is partly based upon FreeBSD so if we can get it to build on a BSD it should get us some of the way to supporting OSX too, kinda.

I've just installed NetBSD 7.0 on my Banana Pi so I thought I'd try compiling muse git. I've got up to the point where its asking for ALSA and now I feel out of my depth as I don't understand cmake. ALSA is deemed a mandatory dependency although the cmake file seems to say this would be optional if built on OSX so thats what makes me think we're in with a chance of getting Muse to build under BSD where we only have OSS? Would it still be possible to use MIDI devices with muse without ALSA or would OSS MIDI support be required? Maybe JACK MIDI takes care of this? I hope so.

To get to the point I did, I had to run:

export CMAKE_PREFIX_PATH="/usr/pkg/qt5/lib/cmake/Qt5Widgets/:/usr/pkg/qt5/lib/cmake/Qt5UiTools/:/usr/pkg/qt5/lib/cmake/Qt5LinguistTools/:/usr/pkg/qt5/lib/cmake/Qt5Xml/"

To get cmake to find all the Qt5 stuff but I failed to add a new include dir into the cmakelist file to get it to find the LADSPA header I edited compile_muse.sh and changed the cmake command to:

cmake -DCMAKE_BUILD_TYPE=release -DHAVE_LADSPA_H=/usr/pkg/include/ .. && make clean all && echo "Build was OK, now enter the 'build' dir and run 'make install' as root"

**Comment by terminator356** [comment]
On February 14, 2016 09:58:17 AM danboid wrote:
> I don't think any of the MusE devs run BSD so I don't know if there is any
> interest in getting MusE running under *BSD but I think it'd be cool for
> MusE to run on as many platforms as possible - certainly at least the BSD
> family as they shouldnt be too hard to support compared to say Windows.
> There seems to be some kind of (intended) support for OSX in the CMake
> files already. OSX is partly based upon FreeBSD so if we can get it to
> build on a BSD it should get us some of the way to supporting OSX too,
> kinda.
> 
> I've just installed NetBSD 7.0 on my Banana Pi so I thought I'd try
> compiling muse git. I've got up to the point where its asking for ALSA and
> now I feel out of my depth as I don't understand cmake. ALSA is deemed a
> mandatory dependency although the cmake file seems to say this would be
> optional if built on OSX so thats what makes me think we're in with a
> chance of getting Muse to build under BSD where we only have OSS? Would it
> still be possible to use MIDI devices with muse without ALSA or would OSS
> MIDI support be required? Maybe JACK MIDI takes care of this? I hope so.
> 
> To get to the point I did, I had to run:
> 
> export
> CMAKE_PREFIX_PATH="/usr/pkg/qt5/lib/cmake/Qt5Widgets/:/usr/pkg/qt5/lib/cmak
> e/Qt5UiTools/:/usr/pkg/qt5/lib/cmake/Qt5LinguistTools/:/usr/pkg/qt5/lib/cmak
> e/Qt5Xml/"
> 
> To get cmake to find all the Qt5 stuff but I failed to add a new include dir
> into the cmakelist file so to get it to find the LADSPA header I edit
> compile_muse.sh and changed the cmake command to:
> 
> cmake -DCMAKE_BUILD_TYPE=release -DHAVE_LADSPA_H=/usr/pkg/include/ .. &&
> make clean all && echo "Build was OK, now enter the 'build' dir and run
> 'make install' as root"
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/muse-sequencer/muse/issues/473


There is already a cross-platform branch started by RJ.
And all of us have slowly been inching towards this realization,
 which is a very worthy goal.

For example one of my tasks is making ALSA optional in MusE,
 which is a huge first step.
I was planning to get back to this soon after all the current stuff,
 as the opportunity is there for me to make it easier now since I 
 added that new ALSA button in the Midi Configuration dialog. 
(The new ALSA button completely stops or starts our ALSA driver,
 meaning it will be easier now to run without ALSA at all.)

DSSI uses ALSA.
So be aware that if you wished to use DSSI in MusE (or in BSD),
 you would still need to install either the full ALSA, or the smaller
 ALSA-DSSI compatibility package, which is available in BSD.
(Last time I checked, full ALSA is not available standard in BSD.)

But for sure cross-platform will not happen for 3.0 release.

Tim.

**Comment by terminator356** [comment]
Super old.
MusE runs on BSD now. One of the BSD devs helped make it happen.
There is now a MusE 'ports' available on BSD, for about a year now.
