### ISSUE TITLE
UI issues under ARM

### ISSUE THREAD

**Issue by danboid** [muse-sequencer/muse#480]
I have built the latest git under Arch Linux ARM on my Banana Pi but as you can see in the attached screenshots its not drawing the UI correctly.

The worst is the arranger where it seems to be trying to cram three rows of icons into one row. The MIDI editing window is a bit better as I can rearrange the elements to how they should be but they all get messed up again as soon as I close then re-open the MIDI editing window.

I saw someone (Orcan?) post to the dev list recently about packaging MusE for Fedora ARM so I wonder if he's experienced these issues too?

![arranger](https://cloud.githubusercontent.com/assets/1429783/13381546/a65f68a2-de56-11e5-8caf-0bf5e5cefaac.png)

![midi](https://cloud.githubusercontent.com/assets/1429783/13381550/b2f29a08-de56-11e5-8133-0f1cbff5727b.png)

**Comment by terminator356** [comment]
On February 28, 2016 12:06:20 PM danboid wrote:
> I have built the latest git under Arch Linux ARM on my Banana Pi but as you
> can see in the attached screenshots its not drawing the UI correctly.
> 
> The worst is the arranger where it seems to be trying to cram three rows of
> icons into one row. The MIDI editing window is a bit better as I can
> rearrange the elements to how they should be but they all get messed up
> again as soon as I close then re-open the MIDI editing window.
> 
> I saw someone (Orcan?) post to the dev list recently about packaging MusE
> for Fedora ARM so I wonder if he's experienced these issues too?
> 
> ![arranger](https://cloud.githubusercontent.com/assets/1429783/13381546/a65f
> 68a2-de56-11e5-8caf-0bf5e5cefaac.png)
> 
> ![midi](https://cloud.githubusercontent.com/assets/1429783/13381550/b2f29a08
> -de56-11e5-8133-0f1cbff5727b.png)
> 
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/muse-sequencer/muse/issues/480

[CC'ing dev ml so that all get this]

Tested: Seems we're not updating (not saving) the MusE.cfg file 
 when the menu bars are rearranged.
Or... at quitting time, it's not gathering the info from the menus 
 and storing it in MusE.cfg

Workaround:
Open the Global Settings and click OK.

To verify:
Close MusE. 
Run MusE again and check Arranger and Pianoroll menus are as desired.

(I'll assume you can actually rearrange the Arranger menus
 if you keep trying. I know Qt sometimes fails to respond
 and you have to try a few times to move them.)

NOTE:
There's another bug! The state of the midi editor is not remembered.
Some problem with the saved state of the midi editor (menus are OK):

MusE: unknown tag <midieditor> at line 894
MusE: unknown tag <splitter> at line 906
MusE: unknown tag <hsplitter> at line 907
MusE: unknown tag <ctrledit> at line 908
MusE: unknown tag <steprec> at line 912
MusE: unknown tag <midiin> at line 913
MusE: unknown tag <tool> at line 914
MusE: unknown tag <playEvents> at line 915
MusE: unknown tag <xmag> at line 916
MusE: unknown tag <xpos> at line 917
MusE: unknown tag <ymag> at line 918
MusE: unknown tag <ypos> at line 919

I should file this separately, unless... it's related?

Lemme know if the workaround works.

Myself I may not have time to investigate solutions for this ATM.

Tim.

**Comment by danboid** [comment]
Hi Tim

I'll try your workaround for the MIDI editor tonight but I can't see how it
could help for the arranger as I need a way to make 2 extra icon rows
appear so its not all squashed up.

Note that I only have ths issue under ARM Arch, x64 Arch is fine.

**Comment by spamatica** [comment]
2016-02-29 8:56 GMT+01:00 danboid <notifications@github.com>:

> Hi Tim
>
> I'll try your workaround for the MIDI editor tonight but I can't see how it
> could help for the arranger as I need a way to make 2 extra icon rows
> appear so its not all squashed up.
>

Don't the icon rows automatically appear (and disappear) if you try to drag
around the toolbars? I think they are supposed to.

Regards,
Robert

>
> Note that I only have ths issue under ARM Arch, x64 Arch is fine.
>

**Comment by danboid** [comment]
Tim:

As you say, if I make a change to the UI in the MIDI window it remembers my change(s) if I open the Global Settings and click OK but I have to do that every time I open and close the window. If I don't do it, any UI changes are lost  Of course its just a workaround for the moment.

Robert:

You're right,a new row is created if I drag elements below the existing row. I've never really had any need to rearrange the UI until now.

Another odd thing is that the transport panel gets opened by default and gets re-opened every time I open the Global Settings and click OK. This seems to big another ARM-only issue.

**Comment by terminator356** [comment]
On February 29, 2016 12:41:47 PM danboid wrote:
> Tim:
> 
> As you say, if I make a change to the UI in the MIDI window it remembers my
> change(s) if I open the Global Settings and click OK but I have to do that
> every time I open and close the window. If I don't do it, any UI changes
> are lost  Of course its just a workaround for the moment.
> 
> Robert:
> 
> You're right,a new row is created if I drag elements below the existing row.
> I've never really had any need to rearrange the UI until now.
> 
> Another odd thing is that the transport panel gets opened by default and
> gets re-opened every time I open the Global Settings and click OK. This
> seems to big another ARM-only issue.

That may be just a quirk of our quirky Global Settings window.

If 'Transport' says 'show' in the Global Settings 'Views' section,  
 that's what will happen. 

Try un-checking it and click 'OK'.

Tim.

**Comment by danboid** [comment]
It certainly is a quirk. If I turn show off for the transport it stops reappearing when I click OK under the global settings but it turns itself back on again when I quit and reload MusE.

Did you guys spot the RPi 3 got released today? It's 64 bit but I'm disappointed it still lacks SATA or USB3 and still only has a 100Mb nic. I think I prefer the BPi still.

**Comment by danboid** [comment]
I say the transport issue is ARM-only as I don't remember ever having this issue under x64. I don't normally use the transport window and I don't recall having to disable it when I nuked my MusE3 config folder recently on my laptop although I must admit I've not tested this is still the case under the latest git code on x64.

**Comment by danboid** [comment]
I should also mention that when I built the latest git from yesterday on my BPi it did give a few warnings during compilation.

Next time I build it I'll be sure to pass them on if they crop up again.

**Comment by terminator356** [comment]
The above problems, and more, should be fixed now.
Toolbar initial placement in all windows fixed.
Midi editor save/load errors fixed.

Tim.
