### ISSUE TITLE
Plug-in sandboxing (Damage control)

### ISSUE THREAD

**Issue by artur-shaik** [muse-sequencer/muse#482]
Ok, this is just an excerpt from Bitwig site.

> Never again will a single plugin take down your entire project. The “sandboxing” feature built-in to Bitwig Studio ensures plug-in crashes will not interrupt valuable production time, or better yet, your performance on stage. Choose 32-bit, 64-bit, or choose both. No third-party bridging is necessary to run your favorite plugins side-by-side. Bitwig Studio protects your workflow while efficiently running your VSTs for non-stop creativity.

Played a little with MusE, I realized that, often crashes happen because of third party plug-ins. So, may be it makes sense to separate plug-in processes from main one, to not crush everything?

**Comment by terminator356** [comment]
On March 4, 2016 07:44:59 PM Artur Shaik wrote:
> Ok, this is just excerpt from Bitwig site.
> 
> > Never again will a single plugin take down your entire project. The
> > “sandboxing” feature built-in to Bitwig Studio ensures plug-in crashes
> > will not interrupt valuable production time, or better yet, your
> > performance on stage. Choose 32-bit, 64-bit, or choose both. No
> > third-party bridging is necessary to run your favorite plugins
> > side-by-side. Bitwig Studio protects your workflow while efficiently
> > running your VSTs for non-stop creativity.
> Played a little with MusE, I realized that often crashes happen because of
> third party plug-ins. So, may be it makes sense to separate plug-in
> processes from main one, to not crush everything?
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/muse-sequencer/muse/issues/482


Hello.
Yes, it's a plugin 'jungle' out there.

It reminds me of a scene in the original movie
 War of the Worlds, where the alien craft is 
 moving across the land destroying everything,
 and a priest decides to come out of the safety of a
 bunker and confront the alien craft, and everyone is
 shouting "no don't go out there" but he does and is killed.

Like going out for a night on the town - without a condom ;-)

After the move to Qt4, Orcan did an amazing tough job
 adding namespaces to MusE, which I think helped here
 because it seemed some plugin global variables were
 polluting the MusE landscape.

So I had briefly mentioned that I would like to put the plugins 
 in a sandbox and/or give them their very own namespace.
It is a good idea.

Certainly at least during plugin discovery, where we must load
 the plugin to find out what's in it, a sandbox would help.

As for the actual audio processing, I am not sure if another
 thread is workable or practical or desirable.
Because of the realtime nature, and possible short cycle periods,
 another thread may hinder the process.
The BitWig blurb doesn't seem to mention it.

I imagine we can rig up a system similar to our disk thread,
 where reading and writing to disk is done through a thread.
However, that's a disk file where we are not concerned
 with reading /and/ writing at the same time.
Plugins are different, both have to done on time.

IIRC there was a discussion on LAD some time ago where
 the consensus was another thread didn't make sense
 for plugin audio processing.
But I think some do it, for example I think some of Fons' 
 software does that.

Also of course there are the plugin GUIs and control
 signal processing to worry about crashing.

I'll have to look at the situation and see if it's practical.

Thanks.
Tim.

**Comment by danboid** [comment]
A huuuuuuuuuge +1 from me if a workable solution can be found!

PS I really enjoyed your WOTW metaphor Tim! :D

**Comment by artur-shaik** [comment]
@terminator356 , :smile: nice response.

What about Bitwig, I had some testing and can say that they somehow protect their app from plug-ins, even in audio processing time. There was made huge work by them, I guess.
