### ISSUE TITLE
amsynth lv2 preset loading does wierd things

### ISSUE THREAD

**Issue by spamatica** [muse-sequencer/muse#491]
The amsynth lv2 synth has a very large amount of presets, possibly this is the reason for it bugging out..

On my computer, when opening the preset list, the menu bugs out and shows everything double size, navigating the menu is then very hard.

Also, I saw mentioned somewhere that there is a LV2 preset extension that we probably don't have support for, possibly related.

**Comment by terminator356** [comment]
Fixed now. The presets menu now uses our PopupMenu instead of QMenu.
Go to Settings and choose either scroll or our normal PopupMenu <More...> behaviour.
Although in the case of amsynth, either way it looks FUGLY - waaay too many items.

I briefly looked at categorizing the items, just like the native UI does.
I'm sure there's a way, but currently the items in our _presets list class member 
 just hold one piece piece of text - the whole preset name.

Regarding the support. It looks like we are already using that extension.
Seems to work OK.
IIRC on my older 32-bit 14.04 distro, these presets menus did not populate, I think. 
Here on newer 15.10 they are fine.

Tim.

**Comment by spamatica** [comment]
Confirmed as working
