### ISSUE TITLE
drumgizmo output channels

### ISSUE THREAD

**Issue by funkmuscle** [muse-sequencer/muse#502]
Hey, dunno if this is an issue but is it possible for drumgizmo to have all 16 channels output to it's own track or buss like you can on Ardour or Reaper?

**Comment by terminator356** [comment]
On April 17, 2016 11:02:59 AM funkmuscle wrote:
> Hey, dunno if this is an issue but is it possible for drumgizmo to have all
> 16 channels output to it's own track or buss like you can on Ardour or
> Reaper?
> 
> ---
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/muse-sequencer/muse/issues/502

Yes. Multi-channel synths are supported.

After creating an instance of the synth track, click on the track's
 'ouput routing'  button (the two button that look like audio plugs).
There you can route channels any way you wish.
And you can open the Advanced Router for a graphical bird's eye view 
 of all your routing.

Please note: MusE3 now has /two/ kinds of routing:
'Omni' routing, and now 'per-Channel' routing.

Omni routing is for quickly connecting the /entire/ track
 to or from somewhere else, without having to select
 individual channels. The behaviour is exactly like previous
 MusE versions - you just connect and go.
(Ask if you need more deatils on the exact operation of Omni mode.)

Channel routing gives you more control over routing.
It allows you to connect individual channels anywhere you want.

The Routing popup menus allow you to conveniently group
 your channel selections as mono or stereo, for one-click connects.

In the graphical Advanced Router, Omni routes are drawn as
 /thick/ lines while Channel routes are /thin/ lines.
Omni routes are connected between the /textual/ listed items,
 while a Channel Bar is provided for connecting Channel routes.
Hopefully fairly self-explanitory how to use the Advanced Router.
Think QJackCtl - beefed up for MusE.

Note: Please ensure that if you do use Channel routing, that the Omni
 routing is not also on, otherwise you get a double mix of all the signals.
(Sorry I just need to get into the code and prioritize that Omni setting
 so that it takes over and there's no mixing of the two modes... 
 er, if I haven't already done it.) 

Tim.

**Comment by funkmuscle** [comment]
that is confusing.. I can find the graphical Advanced Router and that's where I'm lost... On Ardour, you route DrumGizmo's output to either busses or tracks through it's Audio Connection graphical interface. How do I do that here?

**Comment by terminator356** [comment]
On April 17, 2016 05:13:36 PM funkmuscle wrote:
> that is confusing.. I can find the graphical Advanced Router and that's
> where I'm lost... On Ardour, you route DrumGizmo's output to either busses
> or tracks through it's Audio Connection graphical interface. How do I do
> that here?
> 
> ---
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/muse-sequencer/muse/issues/502#issuecomment-211137094

[
 I just grabbed drumgizmo and tested it OK. Very nice. Can't wait to hear it. 
 Unfortunately I can't load the drum kits because I don't have enough RAM :-(
]

So, in MusE the equivalent of busses are 'Group Tracks'.
You can route to or from them, or any other audio Track.
Basically similar to Ardour, "route anything to anything".

But, currently all audio Tracks, except Synth Tracks but 
 including Group Tracks, are limited to maximum two channels :-( 

That may change in the near future as more multi-channel support 
 is added ie. Ardour-style true multi-channel Tracks.

So, how do you work with the channels, then?

You will need route all the /extra/ channels, to more audio Tracks, 
 such as more Group Tracks.

On the mixer Strip that you see for your Drum Gizmo Synth Track,
 the Strip's controls (Volume, Pan, and effects rack etc.)
 apply only to the /first/ two channels. 

Therefore you will likely want to at least route all of the extra channels 
 to more Tracks, so that you have several Strips  with Volumes, Pans etc.


Example using Group Tracks with DrumGizmo, DRSKit:

Create a mono Group Track2 and route this DrumGizmo channel to it:
    Ch 3: Kickdrum back

Create a mono Group Track3 and route this DrumGizmo channel to it:
    Ch 4: Kickdrum front

Create a mono Group Track4 and route this DrumGizmo channel to it:
    Ch 5: Hihat

Create a stereo Group Track5 and route these DrumGizmo channels to it:
    Ch 6: Overhead left
    Ch 7: Overhead right

And so on.

Note that you likely don't need to do anything for these DrumGizmo channels:       
    Ch 1: Ambience left
    Ch 2: Ambience right
 because MusE already assigns a mixer Strip to the /first/ two channels,
 so you already get a Strip with Volume, Pan, effect rack etc. for those 
 channels. But you can., if you want, route those two channels to another
 Track and work with its Strip instead. (In that case remember that the 
 Synth Track's Strip controls still apply, so you'd probably want to set
 all of its controls in the middle.)


I know, somewhat cumbersome but workable. 

I want to go further and add Ardour-style true multi-channel tracks, 
 such as Group Tracks. But actually that might be more like just finishing 
 off the obvious, and not strictly necessary, 

 because...

Look at it this way, look on the bright side: 
By sending all of DrumGizmo's outputs to separate Tracks, each Track has
 a mixer Strip with Volume, Pan, and effects rack. You're going to need that.
Whereas with one single full 16-channel Track, all I can offer you is a
 Master Volume. And Pan is... well what is Pan on a true multi-channel Track?
(I've seen Ardour's multi-channel panners.)

So I'm not sure that a single 16-channel Track Strip, or Synth Track Strip,
 is necessarily what one wants with plugins like DrumGizmo, Addictive Drums,
 Kontact etc. since the channels are all sort of arranged separately.
Addictive Drums has its own strips for each of the channels, too.

One definite good use of multi-channel Tracks that I can think of
 is for surround sound recording, where the final routing destination
 (a Wave Track) records the three or more signals, using a surround sound
 encoding plugin. But again, our Wave Tracks are currently limited to 
 two channels max.

Lemme know how it goes.
Keep poking around, you'll see how it works :-)

HTH.
Tim.

**Comment by funkmuscle** [comment]
Thanx Tim.. Yes I like each track channel from DrumGizmo to it's separate track so yes I can EQ, etc, like a real kit.. That's the intention of DrumGizmo.
I like using Muse for the midi.. It's the easiest midi DAW in Linux. What happened was I replaced the drums in a song done with Hydrogen with DrumGizmo. I did the drums with Muse.. when I moved it to Ardour. the kick was on the left and snare on the right. That with DrumGizmo just using the 2 default channels. I struggled through it on Ardour using only the default stereo outputs of DrumGizmo and the kick and snare sounded proper. After doing so, then I branched it off to single tracks like this: 

http://libremusicproduction.com/tutorials/setting-and-using-drumgizmo-ardour

So I think that's what you mean you're aiming to add to Muse?

**Comment by terminator356** [comment]
On April 17, 2016 08:13:05 PM funkmuscle wrote:
> Thanx Tim.. Yes I like each track channel from DrumGizmo to it's separate
> track so yes I can EQ, etc, like a real kit.. That's the intention of
> DrumGizmo. I like using Muse for the midi.. It's the easiest midi DAW in
> Linux. What happened was I replaced the drums in a song done with Hydrogen
> with DrumGizmo. I did the drums with Muse.. when I moved it to Ardour. the
> kick was on the left and snare on the right. That with DrumGizmo just using
> the 2 default channels. I struggled through it on Ardour using only the
> default stereo outputs of DrumGizmo and the kick and snare sounded proper.
> After doing so, then I branched it off to single tracks like this:
> 
> http://libremusicproduction.com/tutorials/setting-and-using-drumgizmo-ardour

Oh neat. Yes, that looks like the same way you would do it in MusE.

> So I think that's what you mean you're aiming to add to Muse?

Yes similar to Ardour, all Tracks, including Synth Tracks, could have 
 more than two channels.

The Advanced Router has some slight drawing glitches.
You might have to move either of the two vertical splitters after 
 a connection is made, to make the Channel Bar lines draw correctly.
And, well, the lines are a bit too close together, and so on.
And I should really remember to highlight any channel dot which
 is connected to something - easier to see.

One important difference between MusE and Ardour is that
 MusE's mixer Strips do not have a separate number of 
 input vs output channels. For example when a Track is 'stereo', 
 it's just two in and two out. When a Track is 'Mono'
 it just one in and one out.

I've been taking a look at whether to do similar to Ardour and
 allow a different number of Track input vs output channels.
Because I would like to try allowing our Strip input/output 
 channel count to be /dictated/ by the effects rack plugin channels
 ie. how many channels into the Strip and how many channels 
 out of the Strip are /required/ by the effects rack chain.

Thus when things are /dictated/ by the effects rack chain 
 in/out channels, you can understand why Ardour sometimes 
 needs to enforce channel counts. We might have to as well
 if we do that.

MusE gets /away/ with panning a signal in a sort of carefree
 'cached' way before it is routed to any destination(s),
 just because our Tracks are limited to two channels.
It's not so easy to do with multi-channel tracks (chs > 2)
 and you can see why a different panner is needed.
Actually it makes the task radically different because 
 one destination might be 2-channels and another 5-channels, 
 so there's no 'common' panner that can be used.
Again, you can see why Ardour sometimes needs to enforce channels.

Cheers.
Tim.

**Comment by funkmuscle** [comment]
Once again, thank you Tim for taking the time to explain the workings of
MusE for me.
About the panning of the kick and snare, that gets transferred when
exporting the midi file.
I wrote a complete drum track on MusE and when I exported it and opened in
Ardour, it was still panned. When I tried to remove the panned instruments
to fix, it couldn't be done. It's like MusE hard coded something. Is that
possible?

Thanx
Harv
On Apr 18, 2016 2:43 AM, "Tim" <notifications@github.com> wrote:

On April 17, 2016 08:13:05 PM funkmuscle wrote:
> Thanx Tim.. Yes I like each track channel from DrumGizmo to it's separate
> track so yes I can EQ, etc, like a real kit.. That's the intention of
> DrumGizmo. I like using Muse for the midi.. It's the easiest midi DAW in
> Linux. What happened was I replaced the drums in a song done with Hydrogen
> with DrumGizmo. I did the drums with Muse.. when I moved it to Ardour. the
> kick was on the left and snare on the right. That with DrumGizmo just
using
> the 2 default channels. I struggled through it on Ardour using only the
> default stereo outputs of DrumGizmo and the kick and snare sounded proper.
> After doing so, then I branched it off to single tracks like this:
>
>
http://libremusicproduction.com/tutorials/setting-and-using-drumgizmo-ardour

Oh neat. Yes, that looks like the same way you would do it in MusE.

> So I think that's what you mean you're aiming to add to Muse?

Yes similar to Ardour, all Tracks, including Synth Tracks, could have
more than two channels.

The Advanced Router has some slight drawing glitches.
You might have to move either of the two vertical splitters after
a connection is made, to make the Channel Bar lines draw correctly.
And, well, the lines are a bit too close together, and so on.
And I should really remember to highlight any channel dot which
is connected to something - easier to see.

One important difference between MusE and Ardour is that
MusE's mixer Strips do not have a separate number of
input vs output channels. For example when a Track is 'stereo',
it's just two in and two out. When a Track is 'Mono'
it just one in and one out.

I've been taking a look at whether to do similar to Ardour and
allow a different number of Track input vs output channels.
Because I would like to try allowing our Strip input/output
channel count to be /dictated/ by the effects rack plugin channels
ie. how many channels into the Strip and how many channels
out of the Strip are /required/ by the effects rack chain.

Thus when things are /dictated/ by the effects rack chain
in/out channels, you can understand why Ardour sometimes
needs to enforce channel counts. We might have to as well
if we do that.

MusE gets /away/ with panning a signal in a sort of carefree
'cached' way before it is routed to any destination(s),
just because our Tracks are limited to two channels.
It's not so easy to do with multi-channel tracks (chs > 2)
and you can see why a different panner is needed.
Actually it makes the task radically different because
one destination might be 2-channels and another 5-channels,
so there's no 'common' panner that can be used.
Again, you can see why Ardour sometimes needs to enforce channels.

Cheers.
Tim.


>
> ---
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/muse-sequencer/muse/issues/502#issuecomment-211169621


—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub
<https://github.com/muse-sequencer/muse/issues/502#issuecomment-211228299>

**Comment by terminator356** [comment]
On April 18, 2016 02:54:45 AM funkmuscle wrote:
> Once again, thank you Tim for taking the time to explain the workings of
> MusE for me.
> About the panning of the kick and snare, that gets transferred when
> exporting the midi file.
> I wrote a complete drum track on MusE and when I exported it and opened in
> Ardour, it was still panned. When I tried to remove the panned instruments
> to fix, it couldn't be done. It's like MusE hard coded something. Is that
> possible?

Hm, sounds like a MusE midi pan control was adjusted before you exported
 and that's the way it opened in Ardour?

If possible, can you post the MusE .med file, or a chopped down version?
I can test it to see if there's any problem exporting midi.

Not sure what you mean by "tried to remove the panned 
 instruments to fix", that's something specific to Ardour?

Thanks.
Tim.

**Comment by funkmuscle** [comment]
the panned kick and snare I meant.. ok let me create a .med and post it.

**Comment by funkmuscle** [comment]
coming back at this kinda late but loving muse3. on this same topic, I've been meaning to mention this but hectic life lately. the advance router, when adding multichannels, the connectors eventually disappears and I can't connect the entire drumkit from DrumGizmo.
is there a way around this?

**Comment by terminator356** [comment]
How's it goin' eh? Sorry for late reply.

I wired up several drumgizmo channels to some audio output tracks,
  saved and reloaded and everything was there.

Can you describe in more detail, what was connected where?

When do the connections disappear, right after you try to
  make them, or later on?

And does it affect all channels, or only some - especially
  those beyond channel 1 + 2?

Last time I checked all the multi-channel stuff was working...

Thanks.
Tim.

**Comment by funkmuscle** [comment]
hey Tim, I had to keep resizing the Advanced Router to connect 13 channels from, I got them going actually today but it was just a pain having to resize the window at different angles.
In the attached pic, look at drumgizmo connections. Ports 13-16 are disappearing. You can see above Group 1. 

![advanced router muse](https://user-images.githubusercontent.com/4959840/33001758-ecc1b166-cd7d-11e7-96b3-9324bce9fbb0.png)

so every connection I make, the deeper the drumgizmo connections behind Group 1.

**Comment by terminator356** [comment]
Ah yes, thank you.

Yes that's a well known bug to me. Something I never
  got around to fixing. There's a couple of graphical
  things and a feature or two I'd like to complete,
  but it's mostly finished and I'm glad you found
  how to correct it. I hope you enjoy this router,
  it was something I felt needed to be expanded upon
  as it hadn't been touched in years so I really
  beefed it up.

Apologies for too much trouble.

TO and CGY at GC here in OT eh?
Know what I mean, if I recall the right fellow?

Tim.

**Comment by funkmuscle** [comment]
Yes love the router. Still figuring out MuSE as i love using it for
creating drum sections for songs via midi.

TO at CGY on 28th??

**Comment by funkmuscle** [comment]
oh dude yes, GC. didn't know we're facing CGY until I woke up.. Argos!!!!
