### ISSUE TITLE
track list in main window gui redo

### ISSUE THREAD

**Issue by Reaper10** [muse-sequencer/muse#514]
muse track list in main window could use a gui redo 

muse track list in main window gui 
![muse_color_shot](https://cloud.githubusercontent.com/assets/8137561/16630687/1ebc03fc-4381-11e6-8ca9-f215aefb5e48.png)

other track list in main window gui 
![audor](https://cloud.githubusercontent.com/assets/8137561/16630746/59e72006-4381-11e6-9b91-c9065682b356.jpg)
![pro tools recording 1](https://cloud.githubusercontent.com/assets/8137561/16630758/64e24936-4381-11e6-97d3-34cc68d8934d.jpg)
![reaper](https://cloud.githubusercontent.com/assets/8137561/16630775/78563f36-4381-11e6-89e4-86311aa05dba.jpg)
![bitwig 1](https://cloud.githubusercontent.com/assets/8137561/16631120/ff4920f2-4382-11e6-90dd-32d51f6a0dc2.png)
<img width="125" alt="presonus-studio-one-pro-3 2-crack 1" src="https://cloud.githubusercontent.com/assets/8137561/16631124/0e99390c-4383-11e6-95fc-c40cef51c541.png">

![cubase-5-arrange-screenshot 1](https://cloud.githubusercontent.com/assets/8137561/16630809/98dcc784-4381-11e6-9b94-f64d73ec9504.jpg)
![sonar](https://cloud.githubusercontent.com/assets/8137561/16630929/015cbb16-4382-11e6-8776-edc4145a9d7c.jpg)
<img width="125" alt="presonus-studio-one-pro-3 2-crack 1" src="https://cloud.githubusercontent.com/assets/8137561/16631248/d1809cda-4383-11e6-831b-fe2c0bf4f508.png">
![reason](https://cloud.githubusercontent.com/assets/8137561/16631260/dd65c034-4383-11e6-8b38-16829288a748.jpg)
![adobe-audition-cc 1](https://cloud.githubusercontent.com/assets/8137561/16631461/df5fc9c4-4384-11e6-8813-a0dd71e98e64.jpg)
![motu-digital-performer-9 1](https://cloud.githubusercontent.com/assets/8137561/16634448/5af417ee-4393-11e6-8bd4-df7e6d35e34f.jpg)
<img width="801" alt="logic-pro-x-04 1" src="https://cloud.githubusercontent.com/assets/8137561/16662899/6bb664ea-443f-11e6-922a-57c9a98cc4df.png">
![apple_garageband09 1](https://cloud.githubusercontent.com/assets/8137561/16663322/5133fb58-4441-11e6-80fb-803bbdada4c1.jpg)

**Comment by ViktorNova** [comment]
+1 bigtime!!
It's silly, but this is one of the only reasons I don't actually use MuSE fulltime.. the appearance of software unfortunately has a major impact on my creativity/inspiration when using it

OpenOctave MIDI (a now-dead fork of an ancient version of MuSE) replaced MuSE's dated table-style track panel with a nice modern looking graphical one:
![OpenOctave MIDI](http://www.openoctave.org/sites/default/files/track-headers.png)

Perhaps their work could be reused and brought up to date?
I see the OOM stuff still in a branch of this repo: 
https://github.com/muse-sequencer/muse/tree/muse2-oom

OOM's own repo (more up-to-date):
https://github.com/ccherrett/oom

OOM was a really nice project, it's too bad them and MuSE didn't combine efforts!

**Comment by GraysonPeddie** [comment]
I'm also in for a redo, but I want to keep it streamlined. How about this?

![muse_prototype](https://cloud.githubusercontent.com/assets/17316096/17459928/4b5c00b0-5c1d-11e6-8677-256e564e3e6f.jpg)

I use MusE for pure MIDI work and Harrison Mixbus for recording MIDI instruments into audio for mixing, so if I want to see meters which is pointless for MIDI (except maybe velocity?), I will simply use a mixer window just for that.

And there's no need to bombard so many screenshots of DAWs in one post unless you want to show how cool ProTools looks in Windows 7. (Heh heh) It's just too much scrolling.

**Comment by ViktorNova** [comment]
@GraysonPeddie - While that is definitely cleaner, IMO that is a little TOO streamlined and doesn't take advantage of the extra vertical space if the track is wide. Maybe if one was to zoom all the way out and have skinny tracks that could be a decent 'compacted' version of the track list

But more importantly, this idea doesn't address the issue of it being ugly.
If this is going to be redone, I think the "table" style paradigm needs to be left behind and replaced with something graphical that looks nice and makes better use of the vertical space if MusE is going to compete with basically everything else. 

At the very least, if the table layout stays for awhile, it could be vastly improved by making better use of the vertical space instead of just listing everything in a single text row. Qtractor does this in a way that is not far off from MusE, but somehow manages to look  much nicer and more modern:

![2016-08-09-164547_2944x2560_scrot](https://cloud.githubusercontent.com/assets/3234333/17537582/a5fdf4c4-5e52-11e6-884d-ebef92289197.png)

**Comment by GraysonPeddie** [comment]
Then can I have the option to have it as streamlined as I want it? I don't mind a table-style design. The primary three things that I'm into that should be visible are track name, MIDI port, and channel number.

And "ugly" is very subjective. It's just a matter of taste. The total-black-themed screenshot that you have seems like a waste of space to me. Is this Qtractor that I am seeing?

Anyway, keeping the track view streamlined is the utmost top importance for me, so if I want something nice, I'll just use Ardour or Reaper.

**Comment by ViktorNova** [comment]
It is definitely all subjective.

The waste of space you mention on my screenshot only has to do with Qtractor's default track height. Here is a screenshot of Qtractor with skinny tracks, close to the size that MusE uses as default. Notice the word wrapping:
![qtractor-skinny](https://cloud.githubusercontent.com/assets/3234333/17573368/bef35c1e-5f0e-11e6-843c-919cb7d325b7.png)
Conversely, here's what MusE looks like with wide tracks (with otherwise stock config):
![muse-fat](https://cloud.githubusercontent.com/assets/3234333/17573717/19bdf8dc-5f11-11e6-86df-d8210d22ae37.png)
Not only are parts unreadable, but it doesn't utilize the available space, and things are still cut off. I think when the tracks are widened, that the layout should rearrange (Reaper does this) so that the space is better used, rather than still having only a single line of text that is truncated all over the place but with  increased padding above and below that single line like it does now.

Here it is with that area widened a bit to show everything:
![muse-fat2](https://cloud.githubusercontent.com/assets/3234333/17573778/78ec4700-5f11-11e6-94e4-6941448b8a90.png)
Now _that_  is a lot of wasted space. I actually prefer very wide tracks because it helps me to focus in on the instrument I'm working on and it makes small edits easier. 

All I'm saying is... it could be better. ;) Ugly is subjective, but MusE is far nicer than Ardour or Qtractor or Reaper when it comes to working with MIDI, I think a lot of people would switch to MusE if it looked just a little better out of the box (myself included! For now, I use [LOS](https://github.com/falkTX/los) which is a MIDI only fork of OOM, which is a fork of an old version of MusE with lots of improvements)

**Comment by GraysonPeddie** [comment]
I see your point and MusE definitely needs improvement. MusE is one of my only MIDI sequencers out there that have the best workflow and keyboard shortcuts combined.

I will check out and give LOS a try. I did not know falkTX forked a MIDI sequencer based off of OOM. I never came across that until now.

**Comment by ViktorNova** [comment]
Excellent, I think you will like LOS! It works great, despite a few things being rough around the edges.. falkTX wants to get some of these things polished before telling the world about it, so that's why it's kind of an obscure project at the moment..(I've been helping a tiny bit!) On the plus side, not only does it look nicer than MusE but it is also more stable and much faster to launch!

**Comment by drautzburg** [comment]
Whenever you discuss GUI matters, lots of experts appear. That's why I prefer to do weird algorithmic stuff, that nobody understands anyways. At least they leave me alone.

Having said that, the only complaint I have is about the fader buttons in the mixer GUIs, which should look more like real faders.

**Comment by terminator356** [comment]
On Wednesday, November 9, 2016 11:30:49 AM EST Martin Drautzburg wrote:
> Whenever you discuss GUI matters, lots of experts appear. That's why I
> prefer to do weird algorithmic stuff, that nobody understands anyways. At
> least they leave me alone.
> 
> Having said that, the only complaint I have is about the fader buttons in
> the mixer GUIs, which should look more like real faders.

Hi, my main goal with those faders was to squeeze as much possible
 into about a 40-pixel wide strip so that we can squeeze as many strips
 as possible into the mixer. When I record projects I often have many tracks
 so I want to have as many as possible showing in the mixer without having
 to do too much horizontal scrolling.

I know the faders may seem unusual but the only way I could accomplish
 my goal was to put the numbers on top of the sliders.
That means I had to be careful how the fader knobs look otherwise
 they will obscure the numbers.
I know that Andrew had made real-looking fader knobs and I am thinking 
 of ways to re-introduce them in a way that they don't obscure the numbers.
At one point you may recall the faders had *no* knobs until someone
 requested I put them back.
For now I simply stuck with dark grey 'drawn' fader knobs rather than 
 realistic looking bitmap 'pictures'. I hope to make it look better later.
 
Tim.
