### ISSUE TITLE
Importing Midi Files loads extra but empty tracks.

### ISSUE THREAD

**Issue by therealkitman** [muse-sequencer/muse#529]

**Comment by therealkitman** [comment]
Hi,
When I import a midi file into Muse3Pre1, it loads extra but empty tracks along with the real tracks.

![spectacle l10230](https://cloud.githubusercontent.com/assets/14888092/17659459/3ac0b34c-6305-11e6-9c75-c970eda6d2ca.png)

Why is this? Midi used from https://freemidi.org/download-22129-mull-of-kintyre-paul-mccartney?PageSpeed=noscript

Thanks,
Chris.

**Comment by terminator356** [comment]
On Monday, August 15, 2016 1:28:56 AM EDT therealkitman wrote:
> Hi,
> When I import a midi file into Muse3Pre1, it loads extra but empty tracks
> along with the real tracks.
> 
> ![spectacle
> l10230](https://cloud.githubusercontent.com/assets/14888092/17659459/3ac0b3
> 4c-6305-11e6-9c75-c970eda6d2ca.png)
> 
> Why is this? Midi used from
> https://freemidi.org/download-22129-mull-of-kintyre-paul-mccartney?PageSpee
> d=noscript
> 
> Thanks,
> Chris.

Hi.
This is common with opening many midi files, at least in MusE.
You often see what appear to be empty tracks with single small 
 MusE midi parts at the beginning.

But these parts are not empty.
Right click such a part and select 'List' to open the list editor,
 and you will see there are actual midi events in there.
It's the way the file was designed.
In this particular file it is a bit extreme but I've seen similar.

Each of the small parts actually contain initial controller values
 for each of the midi channels. (In this case some RPN14 controllers.)

[Funny, I was just singing Mull Of Kintyre the other day.
I remember when it first came out. A surprise hit.
Coming Up, and the very weird Temporary Secretary were 
 also hits for Sir Paul.]


Now, as for all those the *blank* track names that you may see... 
 well... not much that I can do. That is the way the file was made.
Hm... I have considered many times whether to automatically fill in some 
 useful track names there, but... there is a subtle conceptual problem: 
If we fill in some names, it is no longer the same file, really, and upon
 exporting the file to midi again, the tracks will have names
 which might not be what was intended (we try to preserve 
 the original state of the file). Therefore it is up to the MusE user
 to fill in some useful names and save the file and export if
 so desired.
(But now that I think of it, certainly we should provide a facility to 
 let the user let MusE rename them at the push of a button or 
 upon import - just not automatically, ask the user first. 
Yes, I think that's a solution, for the next time I'm in there coding... )

Tim.

**Comment by therealkitman** [comment]
Hi Tim,
Yes, I see those smaller tracks (though the RPN14 means nothing to me). I installed MuseScore last night and it loaded only the 13 or 14 tracks just like Tuxguitar, LMMS and KMidimon do. 

It is not fatal for me to see those extra tracks in Muse3 (I am just 'playing' at the moment but I do want to bring in Beethoven's 9th later) but it is just messy trying to figure out which tracks are which.
Regards,
Chris.

**Comment by terminator356** [comment]
On Tuesday, August 16, 2016 12:01:02 AM EDT therealkitman wrote:
> Hi Tim,
> Yes, I see those smaller tracks (though the RPN14 means nothing to me). I
> installed MuseScore last night and it loaded only the 13 or 14 tracks just
> like Tuxguitar, LMMS and KMidimon do.

MusE takes great pains to ensure that what is displayed and eventually 
 exported is /identical/ to what was imported. 
It's more of a "what you see is what you get" piano-roll midi editor.

Some other apps fail here, sometimes because they don't support advanced 
 RPN controllers like MusE.

The author of that MOK midi file, for example, would be pleased 
 to know that upon importing and say, some editing in MusE,
 and then re-exporting as midi, *everything* is preserved.


But maybe now it is time to /counter/ that rigidity with some flexibility:

How about a general command, button etc. which says:

"Consolidate tracks on similar channels"

In the case of that MOK midi file, this would take those small parts
 having NO notes and merge them into the other tracks with notes
 that are on the SAME channel.

So it will then /look/ like say LMMS or MusEScore, but will still contain
 /everything/ that was imported, just arranged in a consolidated way.

Some 'smart' variations of the command may be required, like:
"Don't merge same-channel tracks each of which have notes on them"
 since some projects do separate tracks on same channel, with notes.

Merging track names may be tricky. Some arbitrary textual decisions 
 may be needed. Else simple concatenation of names?

The command could be used at any time on an open project.

We could also, for convenience, add a separate set of checkboxes
 for these features in the "Midi file import/export" settings dialog,
 for automatic merging upon midi import.

What do you think?

I will try to do it, but very busy with other feature code right now.
Someone flag this forum post as 'import'-ant. Pun intended.

T.

> It is not fatal for me to see those extra tracks in Muse3 (I am just
> 'playing' at the moment but I do want to bring in Beethoven's 9th later)
> but it is just messy trying to figure out which tracks are which. Regards,
> Chris.

**Comment by therealkitman** [comment]
Hi Tim,
You would naturally have a better perspective on these things than I, so what ever you decide to make midi import/export 'cleaner' would be ok by me. As I said before I am just playing and now I know a bit more I can live with things (import midi, remove extra tracks, label tracks and save as a Muse project).

If it is on your to-do list it is ok, no need for you to bust a gut :)
Thanks,
Chris.
