### ISSUE TITLE
dssi-vst vs carla

### ISSUE THREAD

**Issue by therealkitman** [muse-sequencer/muse#563]
Hi, 
on your FAQ page you refer to using patches to get dssi-vst to use win32 VSTi plugins in muse. I had, as always, trouble getting dssi-vst sorted.

But I ask is with carla as a lv2 plugin by FalkTX hosting Win VSTs is there any benefit of using dssi-vst?

Thanks,
Chris.

**Comment by spamatica** [comment]
Hi Chris,

There is a third alternative to consider also,
https://github.com/phantom-code/airwave.

I have only tried using Carla a few times so I may be wrong, but I could
not get Carla to save the state of what synths are loaded, such that
opening the song in MusE will restore all settings. If Carla supports that
it is a better alternative than dssi-vst as it has lots more features.

It was a while since I tried airwave, it is also a bit nasty to set up but
it supports Win64, which dssi-vst does not. It was a while since I tried,
might have improved.

2017-02-11 9:53 GMT+01:00 therealkitman <notifications@github.com>:

**Comment by therealkitman** [comment]
Hi and thanks.
Carla does save the synth state in it's .carxp file (just tested with Noize mak3r synth with ridiculous settings - saved - closed - restarted carla and opened the .carxp file and my synth settings were still set. ).

I saw airwave a while ago but had trouble compiling. Might try to build it again out of curiosity but it seems carla may be the one to stick with.

BTW - I am sorry for asking a non-technical build issue here but I saw in one of the forum posts that you recommended using your mailing list or IRC instead of the forum. Which is the best way to discuss general things  - issues page? forum? mailing list? IRC?

Thanks,
Chris.

**Comment by spamatica** [comment]
2017-02-12 3:02 GMT+01:00 therealkitman <notifications@github.com>:

> Hi and thanks.
> Carla does save the synth state in it's .carxp file (just tested with
> Noize mak3r synth with ridiculous settings - saved - closed - restarted
> carla and opened the .carxp file and my synth settings were still set. ).
>

Okay, if that is good enough for you then carla will do fine. I prefer when
I only have to setup things in one place, in this case MusE, so loading the
song would automatically setup the whole session.


> I saw airwave a while ago but had trouble compiling. Might try to build it
> again out of curiosity but it seems carla may be the one to stick with.
>
> BTW - I am sorry for asking a non-technical build issue here but I saw in
> one of the forum posts that you recommended using your mailing list or IRC
> instead of the forum. Which is the best way to discuss general things -
> issues page? forum? mailing list? IRC?
>
The mailinglist is much preferred. Very sorry about the forum, need to get
to the bottom of that...



Thanks,

**Comment by therealkitman** [comment]
Hi, just to end this topic, Muse3 saves Carla's state without having to save a separate Carla state (.carxp file) - very nice!!!!
Airwave however kept crashing Muse3 when I reopened a saved .med project. The bug is airwave related so I will pass it on to them.
