### ISSUE TITLE
Can I have bars before bar 1

### ISSUE THREAD

**Issue by drautzburg** [muse-sequencer/muse#568]
Just a quick simple question: _Can I have bars before bar 1_. I always wanted to have a "bar 0" before "bar 1". I would use this bar to count in and possibly store init data. 

I can of course simply treat "bar 2" as the first bar of the song and use "bar 1" for those special purposes. However, when someone else has numbered the bars too (e.g. the guy who wrote the score), my bars would always be off by one, which complicates the communication.

**Comment by terminator356** [comment]
On 06/09/2017 12:47 PM, Martin Drautzburg wrote:
>
> Just a quick simple question: /Can I have bars before bar 1/. I always 
> wanted to have a "bar 0" before "bar 1". I would use this bar to count 
> in and possibly store init data.
>
> I can of course simply treat "bar 2" as the first bar of the song and 
> use "bar 1" for those special purposes. However, when someone else has 
> numbered the bars too (e.g. the guy who wrote the score), my bars 
> would always be off by one, which complicates the communication.
>
>
Would such a score start at bar 0?
Since I don't recall seeing a score with bars less than 0 (-2, -1, 0),
  the only practical thing we could do is allow the bars to be
  renumbered starting at zero.

Ah, setup bars. Grace notes. Initial data.
I researched and gave this quite a lot of thought a few months ago.
I concluded that the concept of a /special/ setup bar (specially treated)
   is illogical in MusE. There is only "the leftmost play position".
Any desired 'setup' bar(s) start at the 'first' bar.
(For this reason in every DAW that I use I never start recording at bar 1,
  always leaving bar 1 for incidentals later, and as a pre-count bar - 
for MusE!)
As I say, we could allow renumbering to start at bar 0, but ultimately
  it's the same thing.

What do you think?

The reason I looked into it is because I really /really/ want to fix MusE's
  broken pre-count feature. I've got a branch going here and I'm trying.
(That's why above, I mentioned the currently recommended use of a
  pre-count bar in MusE. It's our only option right now.)

Consider the role Jack (if running) might, or should, play:
Jack has a 'slow sync' feature that any client can use to 'hold up' the
  transport when some client is trying to 'start playing' the transport.
Suppose MusE has a pre-count set, and another client starts the transport.
We could use the slow-sync feature to make /all/ the clients wait for
  OUR pre-count to finish before playing.
There are some... issues. Like what if Jack's not running, only ALSA midi,
  so we still need a 'native' mechanism to 'hold up' our own transport.
(This could be straight forward: Long ago I added a 'mimic' of Jack's
  transport behaviour in our dummy audio driver.)
Also, another client may actually need the slow sync for regular purposes -
  to hold up the transport while it catches up. How to support both uses?
Trying to work it out.

T.

**Comment by drautzburg** [comment]
**(1) Renumbering the bars**

This would perfectly solve my problem. 

I suppose that the first bar will internally always be "bar 1" even when it is renumbered to "bar 0" on the display. If - as you say - every DAW counts bars starting with 1, the renumbering will not have any effect on synced applications (i.e. other clients). The first bar will remain "bar 1" for the rest of the world (except for applications who also renumbered their bars). 

**(2) Pre-count**

I don't know too much about transport, so the following may be all wrong. I would assumed that pre-count is local to MusE.  Consider multiple synced applications with different pre-count settings.  When you initiate recording from MusE, MuseE would do the pre-count and the whole syncing business only starts _after_ the pre-count. When the recording is initiated from some other application, MusE's pre-count should have no effect.

**Comment by terminator356** [comment]
On 06/10/2017 08:00 AM, Martin Drautzburg wrote:
>
> *(1) Renumbering the bars*
>
> This would perfectly solve my problem.
>
> I suppose that the first bar will internally always be "bar 1" even 
> when it is renumbered to "bar 0" on the display. If - as you say - 
> every DAW counts bars starting with 1, the renumbering will not have 
> any effect on synced applications (i.e. other clients). The first bar 
> will remain "bar 1" for the rest of the world (except for applications 
> who also renumbered their bars).
>
> *(2) Pre-count*
>
> I don't know too much about transport, so the following may be all 
> wrong. I would assumed that pre-count is local to MusE. Consider 
> multiple synced applications with different pre-count settings. When 
> you initiate recording from MusE, MuseE would do the pre-count and the 
> whole syncing business only starts /after/ the pre-count. When the 
> recording is initiated from some other application, MusE's pre-count 
> should have no effect.
>
>
Agreed. Yeah I thought about it more, and that's probably the best way 
to go.
We will not make use of the 'slow sync' Jack feature.
We will use a local MusE pre-count, and only at the very end will MusE 
start the transport.
The clients will just have to be 'ready to go' by the time MusE starts 
the Jack transport,
  because if any of them holds up the transport that will unexpectedly 
delay the start.

T.
