### ISSUE TITLE
Saving an existing med file with a new file name in another folder: Med file gets saved in old folder

### ISSUE THREAD

**Issue by jensplixplox** [muse-sequencer/muse#578]
Second last week I compiled and installed the latest MusE version from the github
repository under Ubuntu Studio 16.04.2. 

Song x is saved in a project folder below ~/band/songs. I opened this song in MusE and told MusE to save it in another location (~/songs) via Menu File > Save as, and I told MusE to create a project folder at the new location. I gave the song a different file name before I saved it at the new location. 

I then noticed that song x (which now has a new file name) has not been saved in the new location (~/songs), but in the old location ~/band/songs. The new location (~/songs) does not contain a directory with the song.

**Comment by terminator356** [comment]
On 07/11/2017 07:09 AM, Jens Radloff wrote:
>
> Second last week I compiled and installed the latest MusE version from 
> the github
> repository under Ubuntu Studio 16.04.2.
>
> Song x is saved in a project folder below /band/songs. I opened this 
> song in MusE and told MusE to save it in another location (/songs) via 
> Menu File > Save as, and I told MusE to create a project folder at the 
> new location. I gave the song a different file name before I saved it 
> at the new location.
>
> I then noticed that song x (which now has a new file name) has not 
> been saved in the new location (~/songs), but in the old location 
> /band/songs. The new location (/songs) does not contain a directory 
> with the song.
>
> —
>
Hi, not sure what's going on there. Seems to work here.
In the save dialog, the text in "Project Path to song file" should be the
  ultimate complete final file name and location. What does it say?

Also, what does the "Projects folder" say? By default it is ~/MusE.
Did you change it to ~/songs?

Tim.

**Comment by kybos** [comment]
Fixed in master.

**Comment by spamatica** [comment]
Oh this was interesting. 
The previous functionality might have been intentional, I use it all the time for saving revisions of the same song (might have been myself that made it like that).

**Comment by spamatica** [comment]
Maybe I'll add a revision checkbox that preserves the old functionalty?

**Comment by kybos** [comment]
Feel free to do so. 
I found the behaviour pretty confusing myself, that's why I changed it. If it was intended, than maybe it should be made clearer somehow, if possible.

**Comment by spamatica** [comment]
Added a separate feature for saving incremental revisions. It can be improved so it auto increments and what not but I think I like it already. 
If you saw the comment about fixing a basePath bug, that was actually unrelated. I removed a wierd "cd.."-step that caused wierd things.

**Comment by kybos** [comment]
@spamatica 

I think I finally understood your issue with the revisions. I guess you use a subfolder for your projects (checking "Create project folder" in the Project dialog). I never do so I just couldn't get it...
In the light of this my above change was definitely wrong and I will revert it. 
What the user complains about is still right, it is difficult to understand the interactions between the various folders involved (global, base, project, file...). Especially when the Project dialog is used for "Save as...", then the behaviour of some actions is quite incomprehensible (like the Revert button). 

This makes the new "Save revision..." function redundant (as it is now, at least) doesn't it?
It still could make sense when a file counter is pre-filled, as you had suggested. I personally would prefer the standard file dialog for that, though. I'd like to see the content of the folder I'm saving to, and have to possibility to e.g. create a new folder for the revision. And it's just as quick, just pressing Enter/OK, so why deprive the user of the flexibility?
Just my opinion. Well, perhaps not quite ;-). UI best practices say, always use standard dialogs where possible, for consistency and because users prefer familiar UIs ;-).

**Comment by spamatica** [comment]
> I think I finally understood your issue with the revisions. I guess you use a subfolder for your projects (checking "Create project folder" in the Project dialog). I never do so I just couldn't get it...

Yes, when you use audio a project-folder is pretty much a requirement, otherwise audio files will end up in a mess.

> In the light of this my above change was definitely wrong and I will revert it.
> What the user complains about is still right, it is difficult to understand the interactions between the various folders involved (global, base, project, file...). Especially when the Project dialog is used for "Save as...", then the behaviour of some actions is quite incomprehensible (like the Revert button).

Yes it is, question is what to do about it? In the beginning the Project dialog was a convenience for handling the creation of the project-folder. Along the way someone added all the features for handing alternative folders, revert etc. And I have to wonder how much that is used. A guess is -not that much- as it is quite hard to understand exactly what it does. Plus it complicates the code.

> This makes the new "Save revision..." function redundant (as it is now, at least) doesn't it?
> It still could make sense when a file counter is pre-filled, as you had suggested. I personally would prefer the standard file dialog for that, though. I'd like to see the content of the folder I'm saving to, and have to possibility to e.g. create a new folder for the revision. And it's just as quick, just pressing Enter/OK, so why deprive the user of the flexibility?
> Just my opinion. Well, perhaps not quite ;-). UI best practices say, always use standard dialogs where possible, for consistency and because users prefer familiar UIs ;-).

A Save As dialog would be clearly understood, that is true, but from a power-user perspective I don't think it is always optimal. 
What about we only use the project dialog on the initial save and otherwise use a traditional Save As dialog? We could add a separate menu alternative Save As New Project... if you really want to start a new project based on the current song.

The New Revision function could still have a use, if we streamlined it to the point that if there is a number at the end of the filename it will increment this and save without even opening a dialog.

**Comment by spamatica** [comment]
If this seems reasonable to you @kybos I can do the fixing this weekend.

**Comment by kybos** [comment]
> Yes it is, question is what to do about it? In the beginning the Project dialog was a convenience for handling the creation of the project-folder. Along the way someone added all the features for handing alternative folders, revert etc. And I have to wonder how much that is used. A guess is -not that much- as it is quite hard to understand exactly what it does. Plus it complicates the code.

I'm afraid I have no good idea how to simplify that (without taking away functionality) ATM...

> What about we only use the project dialog on the initial save and otherwise use a traditional Save As dialog? If I understand the original problem correctly, this would work around that problem too.
> We could add a separate menu alternative Save As New Project... if you really want to start a new project based on the current song.

That sounds reasonable. It would move the most confusing part (Save As New Project...) to a separate function, in the hope that it will be never used anyway ;-). And make the Save As... function clearer and more usable.
Also don't forget there is the global setting ("Use project dialog" I think), the changes will have to play well with it too.

> The New Revision function could still have a use, if we streamlined it to the point that if there is a number at the end of the filename it will increment this and save without even opening a dialog.

Agreed. 
Incidentally I did something very similar for another software, and I can only say it's best to define a strict naming convention and stick to it, no heuristics around numbers in the file name.
Like e.g. "_DDD" (D=digit). If the file name already ends with this pattern, then increase the counter, if not, append "_001" to the file name.

BTW:
I looked at the project dialog a little closer and it seems to me that a considerable part of the confusion is caused by bad and inconsistent terminology (e.g. almost everything is called "project folder", even the global setting). I will see if I can improve it a little in this respect.
