### ISSUE TITLE
Please replace all exp10 and pow10 for FreeBSD (and possibly MacOS)

### ISSUE THREAD

**Issue by yurivict** [muse-sequencer/muse#584]
```
inline double exp10(double a) { return pow(10.0, a); }
inline double pow10(double a) { return pow(10.0, a); }
```

**Comment by moe123** [comment]
```
#	if	defined(__APPLE__)
#	define exp10f(x)        __exp10f((float)(x))
#	define exp10(x)         __exp10(ast_exp((double)(x))
#	define exp10l(x)        (long double)__exp10((long double)(x))
#	elif !defined(__GLIBC__)
#	define exp10f(x) expf   ((float)(M_LN10 * (x)))
#	define exp10(x)  exp    ((double)(M_LN10 * (x)))
#	define exp10(x)  expl   ((long double)(M_LN10 * (x)))
#	endif
```

**Comment by yurivict** [comment]
I think this is a Linux-only project. It depends on /dev/rtc which exists only on linux.

**Comment by terminator356** [comment]
Hello, I thought I had replied to this recently but I guess not.
Your request was recently taken care of with commits of 17.02.2019 and 19.02.2019
 in the MusE ChangeLog. Some effort was being put into a Windows port, so I took care of it.
Hopefully the all exp stuff would compile now under BSD.
However I was not aware of the lack of RTC. I can see that it might not compile as
 it appears to be required. But it could be easily made optional.
The question then is what to replace the RTC with.
MusE tries the RTC first and if that fails it tries any detected ALSA timers, which I think
 are not available on BSD.
Someone recently added a simple Qt based timer, but meh...
And about two weeks ago I added POSIX timers. I don't know if BSD supports those.
I just need to activate them before they can be used.

However, all of this timer support is only required for our ALSA support.
So since ALSA is not on BSD, then we don't need those timers and MusE will therefore
 rely solely on Jack and Jack Midi on BSD.

Therefore hopefully all we need is to make that RTC code optional
 because all of our ALSA code is already completely optional via cmake.
After that it might compile... hopefully.

I will reopen this as a reminder to do it, and so that the discussion might continue
 or other potential cross-platform issues might be discussed.

Thanks.
Tim.

**Comment by yurivict** [comment]
Yes, please have an option to disable ALSA so that the FreeBSD port can be created.

Thanks!

**Comment by terminator356** [comment]
Yes, as of 18.12.2016, ALSA support in MusE is completely optional !
It can be completely **disabled** via cmake option.

Sorry for not being clear about that.

So the next step is to make the RTC optional.

**Comment by moe123** [comment]
@terminator356 if you want an agonistic access to mixer/audio engine APIs you might think about using an abstraction libraries such as portaudio; it fairly supports ASIO on win.

**Comment by terminator356** [comment]
(Whoa, we both just posted now at the same time!)

Yes, we already use RtAudio - the user can select it as the MusE audio driver.
The next logical step is to support RtMidi.

For now though, our Jack and Jack Midi support should suffice to get up and running on BSD.

There are serious trade-offs with using an abstraction library:
For example they usually do not support the concept of **routing**, like Jack.
Thus, if Jack is available it is recommended above all other methods.

**Comment by moe123** [comment]
@terminator356 yes, true, you may write a routing abstraction layer each bay containing its virtual process callback + some kind of bypass parameter; it's totally feasible and enough straightforward  to bind such system; you might clone jack then adding your specifics.

**Comment by yurivict** [comment]
I'd unsubscribe from this thread, because these details aren't for me.
Please send me a message when you will have it ready to build on BSD.

Thank you!

**Comment by terminator356** [comment]
Hang in there, I'm fixing it right now!
I need your help to test this, so stand by... I'll message you when ready...
Thanks.

**Comment by terminator356** [comment]
Done in git master now.
RTC support is now compiled in **only** if ALSA support is enabled.
Tested compilation with ALSA support disabled. OK.
Program runs. OK.

BSD users please give it a try.
I've no doubt there will be other issues (especially various paths used by the app),
 but please us help spot them, thanks.

**Comment by terminator356** [comment]
A quick note: On BSD please ensure that **BOTH** the ENABLE_ALSA and ENABLE_DSSI
 cmake options are disabled.
Due to a slight arrangement in our cmake, the DSSI option will force the ALSA
 option on, which will fail on BSD.
We cannot support DSSI without the FULL ALSA package anyway.
The smaller 'ALSA DSSI compatibility package' is **not** sufficient for MusE to use DSSI.

**Comment by spamatica** [comment]
closing as this seems to have been taken care of
