### ISSUE TITLE
After midi sync, tempo cannot be changed anymore

### ISSUE THREAD

**Issue by drautzburg** [muse-sequencer/muse#589]
I tried to sync muse to ardour and finally got it working. However it was so painful, I will probably never use it for anything serious.

However, after undoing all my "midi sync" settings, my song shows a fixed tempo of 120 and I cannot change this anymore. It also ignores the mastertrack. I have the impression muse still thinks it is a slave to some time master. The .med file shows a number of "Sync" tags, which are not present in other projects. 

I am currently trying to edit the med file.

**Comment by drautzburg** [comment]
I got it working again by checking "master" on the transport panel. I swear, I never touched this setting. The tempo shown there was "120". After checking "master" my mastertrack also changed to 120. Originally my song had tempo=90. 

Something is not symmetrical. I was only furiously clicking around in the "midi sync" dialog and in  "midi ports" (because I needed a loopback device). But to undo things I needed to click in the "Transport Panel". The checkbox "Jack transport timebase master" in the "midi sync" dialog and the "Master" button next to the "Jack" button in the Transport panel are not kept in sync. Maybe they indeed stand for different things. However the "Slave to external sync" and the "Sync" button _are_ kept in sync.

**Comment by terminator356** [comment]
Yes, things may seem a bit weird with that.

Don't confuse our transport panel's tempo 'master' button
  with Jack transport timebase 'master' - the transport panel's
  tempo 'master' button means "use the built-in tempo list".
Our rather unfortunately named transport panel tempo 'master'
  (and the corresponding tempo 'master' graph window etc.) was
  in place long before Jack transport's timebase 'master' feature.

Whenever external sync is chosen, it must automatically un-set
  our transport panel's tempo 'master' button, and it may not
  return it to its previous setting.

Also, due to subtleties in how Jack's Transport Timebase Master works,
  other clients can claim or unclaim Jack timebase master without
  informing other clients such as MusE. You'll just have make
  MusE claim the timebase master again.


Also, I am aware of the poor sync between some of the buttons.
All these problems were fixed in my latest branch which I mentioned
  the other day :-)

Furiously working on it so I can merge all this wonderful stuff soon.

Thanks for reporting.
Tim.

**Comment by drautzburg** [comment]
> 
> Furiously working on it so I can merge all this wonderful stuff soon.
> 
> Thanks for reporting.
> Tim.

As a side note, the muse version in the debian repositories is ancient. That's quite unfortunate, because it decimates
your pool of testers. And that will lead to slowly deceasing overall quality, no matter how motivated you guys are.

It is maintained by "Debian Multimedia Maintainers". Do you know these guys? If so, it might be a good idea to nudge
them a bit to switch to muse-3.
