### ISSUE TITLE
Can't register or read the forum

### ISSUE THREAD

**Issue by peter655** [muse-sequencer/muse#603]
Hi,

Sorry is this is not the right place to post this, but I can't seem to find any way of contacting anyone about this issue.

Basically, I just followed the link to the forum from the main Muse website and got a message that says the following:  

> **_I'm sorry, but you are banned. You may not post, read threads, or access the forum. Please contact your forum administrator should you have any questions._**

I tried clicking on the "Register" icon, but got the same message, which I find strange, given I've never visited the forum before.

How do I go about accessing the forum, if I can't register and the system won't let me read posts there?

Kind regards

Peter

**Comment by spamatica** [comment]
Hello Peter, you are quite correct in reporting this here. Unfortunately I have bad news, the forum has been dead for quite a while now :( 
I at least remembered to try to take make this apparent now. As I wrote on the page, keeping the forum available has taken a lot of effort and in the end it seems to have completely stop working.

The mailinglists are currently the best option for asking questions, information about joining and searchable archives are here:
http://muse-sequencer.org/index.php/Muse_ml

**Comment by peter655** [comment]
Hi,

Thanks for the reply..really appreciate it.

Can you tell me if I need WINE to run Windows VSTs in Muse..or can they be run directly within Muse without it?  Excuse my ignorance, as it's been a while since I've actually used a Linux system or any software on it, but I'm planning on making the move completely over to Linux soon and Muse looks like a really solid fit for my production needs.

Peter

**Comment by terminator356** [comment]
You need Wine to use Windows VSTs with _any_ Linux software, AFAIK.
There are a few ways to use them in Linux (see Carla, Airwave etc.) but the only way to
 use them directly in MusE, as a plugin, is with dssi-vst. We support dssi, and dssi-vst.
It has been a while since I tried it, but these days they say (I just read) it should be possible
 on most 64-bit systems if you install 32-bit multi-libraries, build chain, wine, and so on.
(I just tried to build it now but I'm missing a dependency.)

Also check to see if your favourite Windows VST comes in a LinuxVST version, we support that.
And we support LV2 plugins.

A few bugs crept into 3.0.0, hang in there for "The bugfix release" (tm). 
As we fix them you can grab the git master.

**Comment by spamatica** [comment]
New plan: We have a new forum!
https://linuxmusicians.com/viewforum.php?f=61
Nothing there to read yet, just thought I would mention it.

Regarding Windows VST, as Tim mentions there are several ways to use
Windows VSTs, none of them works perfectly, dssi-vst used to work pretty
good but for some reason it doesn't work at all the last times I've tried
under Ubuntu/kxstudio.
Actually Airwave does allow the synths to open inside MusE just as dssi-vst
does, it's just doesn't work quite as well as dssi-vst used to do...

There are some VSTs I have a hard time being without, mainly Addictive
Drums, which works okay in Airwave. Besides that there are plenty of native
plugins to go around so I recommend trying various.




2018-01-11 6:56 GMT+01:00 Tim <notifications@github.com>:
