### ISSUE TITLE
Muse 3.0 fails to build without the cmake option "-DENABLE_FLUID=OFF"

### ISSUE THREAD

**Issue by GvMariani** [muse-sequencer/muse#605]
Building muse 3.0 on Rosa Linux Fresh 2016.1 R10 (a Mandriva derivative distro, similar to Mageia and OpenMandriva), x86_64, with gcc 5.4.1.
After working around issue #604, if the fuildsynth support is enabled (the default) the build still fails with various errors:
1)'FLUIDSYNTH_API' does not name a type (40+ times)
2) 'Event' in namespace 'MusECore' does not name a type (3 times)
3) 'MusECore::Event' has not been declared
4) '_event' was not declared in this scope

See the attached build log for all the details:
[BuildFailedFluid.txt](https://github.com/muse-sequencer/muse/files/1628736/BuildFailedFluid.txt)

I don't know so much about C++, but I noticed that the event.h header file (ie the one that provides the Event class in the MusECore namespace) has the same name as the one from fluidsynth (ie the one that generates the 40+ FLUIDSYNTH_API errors);  I wonder if this could be the cause: the build process searches for an event.h, but it finds the fluidsynth one before the muse internal one...
When fluidsynth support is not enabled at the configure time, the header clash does not happen and all is good...

**Comment by spamatica** [comment]
Curious, guessing the compiler picks up the wrong event.h
since -I/usr/include/fluidsynth is listed in the includes. Which probably
should only be added when building the fluidsynth plugins.
Hmm... actually, why is it there? On my system it's not listed when
building this part of muse.

[ 28%] Building CXX object muse/widgets/CMakeFiles/widgets.dir/moc_canvas.o
cd /home/ddskrjo/dev/muse-build/muse/widgets && /usr/bin/c++
 -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NO_DEBUG -DQT_SVG_LIB -DQT_UITOOLS_LIB
-DQT_WIDGETS_LIB -DQT_XML_LIB -Dwidgets_EXPORTS
-I/home/ddskrjo/dev/muse-build/muse/widgets
-I/home/ddskrjo/dev/muse/muse3/muse/widgets
-I/home/ddskrjo/dev/muse/muse3/vestige -isystem
/usr/include/x86_64-linux-gnu/qt5 -isystem
/usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem
/usr/include/x86_64-linux-gnu/qt5/QtGui -isystem
/usr/include/x86_64-linux-gnu/qt5/QtCore -isystem
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -isystem
/usr/include/x86_64-linux-gnu/qt5/QtUiTools -isystem
/usr/include/x86_64-linux-gnu/qt5/QtXml -isystem
/usr/include/x86_64-linux-gnu/qt5/QtSvg -I/usr/include/alsa
-I/usr/include/rtaudio
-I/home/ddskrjo/dev/muse/muse3/muse/lv2Support/lv2-1.12.0
-I/home/ddskrjo/dev/muse/muse3/muse/lv2Support/sord-0.14.0
-I/home/ddskrjo/dev/muse/muse3/muse/lv2Support/sratom-0.4.6
-I/home/ddskrjo/dev/muse/muse3/muse/lv2Support/serd-0.22.0
-I/home/ddskrjo/dev/muse/muse3/muse/lv2Support/lilv-0.22.0
-I/usr/include/libinstpatch-1.0 -I/usr/include/glib-2.0
-I/usr/lib/x86_64-linux-gnu/glib-2.0/include
-I/home/ddskrjo/dev/muse/muse3/. -I/home/ddskrjo/dev/muse/muse3
-I/home/ddskrjo/dev/muse/muse3/muse -I/home/ddskrjo/dev/muse-build
-I/home/ddskrjo/dev/muse-build/muse
-I/home/ddskrjo/dev/muse-build/muse/instruments
-I/home/ddskrjo/dev/muse-build/muse/ctrl
-I/home/ddskrjo/dev/muse/muse3/muse/arranger
-I/home/ddskrjo/dev/muse/muse3/muse/driver
-I/home/ddskrjo/dev/muse/muse3/muse/instruments
-I/home/ddskrjo/dev/muse/muse3/muse/liste
-I/home/ddskrjo/dev/muse/muse3/muse/midiedit
-I/home/ddskrjo/dev/muse/muse3/muse/mixer
-I/home/ddskrjo/dev/muse/muse3/muse/mplugins
-I/home/ddskrjo/dev/muse/muse3/muse/remote
-I/home/ddskrjo/dev/muse/muse3/muse/waveedit
-I/home/ddskrjo/dev/muse/muse3/muse/lv2Support
-I/home/ddskrjo/dev/muse-build/muse/arranger
-I/home/ddskrjo/dev/muse-build/muse/driver
-I/home/ddskrjo/dev/muse-build/muse/liste
-I/home/ddskrjo/dev/muse-build/muse/midiedit
-I/home/ddskrjo/dev/muse-build/muse/mixer
-I/home/ddskrjo/dev/muse-build/muse/mplugins
-I/home/ddskrjo/dev/muse-build/muse/remote
-I/home/ddskrjo/dev/muse-build/muse/waveedit
-I/home/ddskrjo/dev/muse-build/muse/widgets/function_dialogs  -std=c++11
-Werror=format-security -Wextra -Winvalid-pch -fexceptions -Wall -fPIC
-std=c++11 -O2 -fomit-frame-pointer -ffast-math -fno-finite-math-only -Wall
-Wextra -fPIC -O3 -DNDEBUG -fPIC    -include
/home/ddskrjo/dev/muse-build/all.h  -I../
-I/home/ddskrjo/dev/muse/muse3/synti -fPIC -std=gnu++11 -o
CMakeFiles/widgets.dir/moc_canvas.o -c
/home/ddskrjo/dev/muse-build/muse/widgets/moc_canvas.cpp

Some option must drag it in...



2018-01-13 22:04 GMT+01:00 Giovanni Mariani <notifications@github.com>:

**Comment by GvMariani** [comment]
I don't know why this happens, but I can confirm my guess: the culprit is header name clashing...
Going by brute force, I found that there are 4 headers from muse having the same name as some headers from fluidsynth: audio.h, event.h, midi.h and synth.h...
Curiously, the problem arises only for files in directories below the muse one and not for the ones residing in the same directory as the above headers: evidently
The rude and rather large patch resulting from the my work (attached) fixes the issue by simply putting a "../" before the header names, in every spot they are included:
[muse-3.0.1-fix-fluidsynt-build.txt](https://github.com/muse-sequencer/muse/files/1637013/muse-3.0.1-fix-fluidsynt-build.txt)
With this one I can successfully build muse 3.0.1 with the default -DENABLE_FLUID=ON option.

Another solution could be simply rename your internal headers: e.g. audio.h to something as muse/ms_audio.h and fix the corresponding includes (the recurrences are all listed in my patch, I think)...
Perhaps a much more elegant solution could be force cmake to look in the muse directory, before searching in the system include dirs: I'm not an expert of cmake inner workings, but I guess that 
sprinkle some "-I ../" in the set_target_properties of the relevant CMakeLists.txt files (perhaps before the your standard "-include ${PROJECT_BINARY_DIR}/all.h") could do the trick...

My two cents...

**Comment by spamatica** [comment]
Hi Giovanni,

Thanks for digging deeper into this.

I would much like to understand why fluidsynth headers are included for
modules where they do not matter, they aren't there when I build so it's
either distro specific,  something in the packaging system or something
else in the environment..
Though, as you mention, renaming the files to something less generic is
probably the best solution to work around these kinds of problems.



2018-01-16 23:23 GMT+01:00 Giovanni Mariani <notifications@github.com>:

**Comment by GvMariani** [comment]
> I would much like to understand why fluidsynth headers are included for modules where they do not >matter,

Well, I guess that, to find why this happens, we will have to take a muse subdir showing the problem (eg. widgets) and walk all the "include tree" of the various CMakeLists.txt files, starting from the one in the top source directory... After all, you know your sources very well, did not you?

**Comment by spamatica** [comment]
Hi,

Just wanted to let you know I installed Rosa Linux in a VM and managed to
get the same problem!
So when I have some more time I will try to get to the bottom of what we
can do about it.



2018-01-17 11:45 GMT+01:00 Giovanni Mariani <notifications@github.com>:

**Comment by spamatica** [comment]
Made a change to the build scripts, found out that the fluidsynth includes
were actually globally included in MusE, it's just that in Kubuntu (where I
currently write) this path is set to /usr/include, which in this case is
harmless so I never noticed.
I moved the path to only be included in the actual synth plugin.
Builds fine in Kubuntu, if you want you can test it on Rosa Linux. I can't
tonight but I will do so tomorrow.


2018-01-17 15:30 GMT+01:00 Robert Jonsson <spamatica@gmail.com>:

**Comment by spamatica** [comment]
Tested on Rosa Linux now and my build works with the configuration change.



2018-01-17 21:14 GMT+01:00 Robert Jonsson <spamatica@gmail.com>:

**Comment by GvMariani** [comment]
Confirmed.
888bd223d9cf54956e44d0fb4dcb0bc32e9a9515 fixes the issues: closing...
