### ISSUE TITLE
Drumgizmo channels 1 & 2 are not being heard

### ISSUE THREAD

**Issue by windowsrefund** [muse-sequencer/muse#623]
I've spoken to the DG devs who confirm the channels are being assigned and output as expected using Ardour. They suspect this is a MusE issue. [This awesome Youtube video](https://www.youtube.com/watch?v=PFOUnyH3irU&index=1&list=PLp2qifo30hMsYT4AXcNeepsXkk1PmCJR4) seems to work around this issue starting at 17:00 using the carla-patchbay plugin. However, that's not really working out for me ATM partly due to #622 . In order to try and assist with the setup, I'm attaching a .med file that sets everything up. Obviously, it probably won't load the DG drumkit properly since filesystem paths would likely be different across systems. If there's anything else I can add to this or questions I can answer, please let me know.

Here is a mixer [screenshot](https://i.imgur.com/wWSq6bA.png) showing no output on the 'Rooms' channel (assigned to DG channels 1 & 2) while a small loop is being played.

[drumgizmo-crockellkit.zip](https://github.com/muse-sequencer/muse/files/2334852/drumgizmo-crockellkit.zip)

**Comment by terminator356** [comment]
Hi, sorry for the very late reply.
I tried this file and after loading a DrumGizmo kit into the synth it works fine.

The only problem is that your DrumGizmo synth track's mixer strip volume is at ZERO !
This means channels 1 + 2, which are fed into the Rooms track, will have ZERO volume !
Turn up the volume on that DG synth track and you will hear the Rooms track.

Why does this happen?
You see, with multi-channel synths, we don't have enough channels on a single
mixer strip (max 2) to cover all the channels from the synth.
However, note that the mixer strip for the DrumGizmo synth track DOES control
 the FIRST TWO channels' volume and pan.
Since you have chosen to feed those first two channels into the Rooms track,
the DrumGizmo synth track mixer strip actually DOES affect those volumes.
Thus the Rooms track input volume is actually controlled by that DrumGizmo
 synth track mixer strip. And its volume is currently at ZERO. So turn it up.
As you have correctly discovered and arranged (I may have explained it earlier),
all the extra channels above 1 + 2 need to be fed into OTHER mixer strips or other routes
to be heard and to be able to control their volumes.
It's just that for channel 1 + 2, the DrumGizmo mixer strip ALREADY controls their volumes.

Hope that helps.
T.

**Comment by spamatica** [comment]
Closing as this should be cleared up now. Some tests suggest it is working here.
