### ISSUE TITLE
Build issue on GCC8

### ISSUE THREAD

**Issue by eventhorizon5** [muse-sequencer/muse#627]
Hi, I have a system which is running Debian Testing and GCC 8, and Muse is having a build error:

`
/home/ryan/muse/muse3/muse/lv2Support/sord-0.14.0/src/sord.c: In function ‘sord_new_literal_counted’:
/home/ryan/muse/muse3/muse/lv2Support/sord-0.14.0/src/sord.c:1063:3: error: ‘strncpy’ specified bound 16 equals destination size [-Werror=stringop-truncation]
   strncpy(key.meta.lit.lang, lang, sizeof(key.meta.lit.lang));
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
`

I'm using the latest git code.  Adding a "-1" to the sizeof value fixes the build; I don't know if that's a proper solution or not though.

**Comment by terminator356** [comment]
Hi, that's a strange one. I've got gcc 8.1 and don't get an error here on openSUSE tumbleweed.
(Although, I've got over 2000 packages waiting to be updated since a few weeks now...)
I downloaded sord-0.16.2 separately and it builds fine as well.
Can you do the same and report back? Even better: Download, build and install 
the latest entire suite of these five tools: lv2, sratom, sord, serd, and lilv.
If all goes well with that, MusE should automatically detect these system-installed
 later versions and use them, and if it doesn't you can force it to by setting the
 ENABLE_LV2_SUPPLIED cmake flag to false.
MusE should tell you with a message near the end of configuration whether
 the internal versions or the system versions are being used.
I'm currently talking to the LV2 author about an unrelated bug, so if there's
 a problem with sord, I've got his attention at the moment... Let me know how it goes.
Thanks.
Tim.

**Comment by eventhorizon5** [comment]
The ENABLE_LV2_SUPPLIED flag seems to already be false on my system.  I tried installing the system sord package separately (0.16), wiping the build folder and reconfiguring, and muse didn't detect it.  Installing the other packages (like lv2) fixed it though, and it now builds.  So it looks like just the built-in sord is broken on GCC8.  The GCC I'm using is Debian 8.2.0-6.  I was building from source because Debian only has the old Muse 2.1.2 which doesn't work with Jack2 anymore (at least on Debian Testing), but Muse3 works fine.

**Comment by terminator356** [comment]
Good news. Glad it works. The lv2 author has asked me to try some fixes he made,
 so I'll be getting into that later, and at the same time I will try to update our internal versions.
Looking at the sord code though, nothing has changed in that part where the error was,
 so I think the potential for the error might still happen, but we'll see.
It might be because when building MusE in Debug mode, we force MusE to treat
 all warnings as errors, and it is a very unforgiving mode and hard to work around
 when some third party header or internal library has a warning.
In Release mode it should not stop building on warnings, though.

It may take me some time to get to the lv2 stuff, I'm heavily into a branch right now,
 which I promised two weeks ago I would merge, ehm... Technical Difficulties. - (Great RacerX song.)

**Comment by eventhorizon5** [comment]
I was building Muse in Release mode, so debug mode shouldn't be the issue.

**Comment by aquilarubra** [comment]
Just in case, Debian has something flawed in its GCC 8.2 build. I moved to another distro to have it right.

**Comment by hfiguiere** [comment]
see pr#635. encountered the problem on Fedora 29

**Comment by hfiguiere** [comment]
This can be close now as #635 has been merged.
