### ISSUE TITLE
Ctrl-<Right Mouse Click> does not move left marker

### ISSUE THREAD

**Issue by fellowcraft** [muse-sequencer/muse#632]
Right Mouse Click moves the _**right**_ marker (a blue triangle), however: 

Ctrl-Right Mouse Click 
Shift-Right Mouse Click 
Ctrl-Left Mouse Click  
Shift-Left Mouse Click 

do _not_ move **left** marker (a blue triangle)

(ARCH 3.0.2 build)

**Comment by terminator356** [comment]
Hello. The left blue range marker is set with the middle mouse button.
Don't have a middle mouse button, or don't want to use it?
Go to menu Settings > Global Settings, click on the GUI Behaviour tab,
 click the option labeled "Shift + right click sets left range marker".

And... Oops, that's a mislabel!
The option is supposed to say "Ctrl + right click sets left range marker".
That combination does work when this option is enabled.
Fixed in the MusE git master now. From ChangeLog:
      - Fix fluidsynth fluid_synth_error() deprecated in 2.0.2
      - For bug 632: Fix slight text error in Global Settings option:
         Now reads "Ctrl + right click sets left range marker".

Thanks for the report.

**Comment by spamatica** [comment]
Closing as this should be cleared up now.
