### ISSUE TITLE
Cursors are too small on HiDPI

### ISSUE THREAD

**Issue by hfiguiere** [muse-sequencer/muse#637]
Custom cursors are too small on HiDPI. 

See screenshot:

Regular cursor:
![image](https://user-images.githubusercontent.com/114441/52455332-8f50e480-2b1d-11e9-84de-d49be478001c.png)

Custom cursor:
![image](https://user-images.githubusercontent.com/114441/52455337-937d0200-2b1d-11e9-861a-5f259e54bbee.png)

**Comment by terminator356** [comment]
I wonder if the solution is simply to use SVG scalable cursors.
Coincidentally I investigated that during the last big commit. I wondered if it was possible.
Yet I could find nothing about it at the time. But now I found one (!) lonely reference to it
 in all the google results.
So I can try it. If you can wait, I now have access to a 4K monitor and card, just not here.
I might be wrong but the top picture sure does look like an SVG image (smooth).

MusE still uses a lot of bitmaps.
But gradually they are being replaced by SVG versions. (Mixer strips, some others etc.)
For now, I will assume that those particular **bitmap** icons, and the SVG icons, look OK for you.
(It would not surprise me because they're all drawn with QPainter and so on.)

Thanks.

**Comment by hfiguiere** [comment]
Some dialog still use a font that is small. I'll file another issue
