### ISSUE TITLE
wavecanvas.cpp issue

### ISSUE THREAD

**Issue by aquilarubra** [muse-sequencer/muse#640]
Hi, muse/waveedit/wavecanvas.cpp was using QProcess. Now it was changed to use fork(). Please, use QProcess again. As I am trying to port MusE to Windows, adding more *nix specific code makes the effort more difficult. Thanks

**Comment by terminator356** [comment]
I don't recall it ever using QProcess, been like that for years now ;-)
Fixed in master now!

Please note, both the old and new methods make MusE freeze until
 the external editor returns. This is normal. But I've put a note in the code
 to perhaps try an asynchronous solution instead (where MusE continues to run).
But this would be hard - it would be more like inter-app 'live collaboration' support :-)

Thanks for the report.

**Comment by spamatica** [comment]
Closing as it has been taken care of
