### ISSUE TITLE
Feature Request: Assign color per track. 

### ISSUE THREAD

**Issue by alextone** [muse-sequencer/muse#651]
This is an FR asking for the ability to assign a color per track that will use that color for all the items in the selected track, existing and yet to be created.

We currently have a limited number of available color slots for things like guitar, saxophone, etc. The color doesn't continue on in the same track for each new item created/recorded. We have to do this manually.

**Comment by kybos** [comment]
I would prefer it that way too, but from what I understand, the concept in MusE is quite different and probably not really compatible.
This concept is based on current colour (which is the default gold at the beginning). If you change the colour for a part, then the new colour becomes current and all new parts will be created with it, independent of the track.
A good thing is that you can shift-click a part to select all parts of a track and thus easily set the same colour to them. But it can be quite a nuisance if you e.g. import a MIDI file with many tracks and have to do that manually per track...
You can also customize the colours and even their descriptions (guitar, piano...) in Appearance settings.

What I would like:
1. A fixed default colour attribute per track (any colour selectable from the standard dialog, not only a limited set).
2. Optional: A possibility to override that default per part. That should be less of a problem, since parts already possess the colour attribute now.

But let the experts judge on that... ;-)

**Comment by terminator356** [comment]
Apologies to Alex for no reply from me. It's tricky.

Things I've thought about several times over the years:

1: There is a desire to show something... anything... other than the yellow,
 when a new track is created. I wanted to at least start with a different colour
 for different tracks - the same colour as the track icon.
For example a new wave track would start with purple coloured parts,
 and a new midi track would start with blue coloured parts.
But... this doesn't jive with the 'current colour' concept.
Also, I wanted to match those starting colours with the 'named' ones that are listed.
But a few of the desired colours don't quite jive with the names we have given them.
For example purple, the desired wave part colour, is named 'keyboard' in our list.

2: I really wanted to put a 'current colour' custom control up on the toolbar.
The control is a drop-down colour selector combobox, containing all our available colours
 shown in the part's right-click.
Each combobox item has a name and an icon - just a small coloured square.
In addition, there is a small coloured square beside the combobox such that when
 the box is closed it shows the current colour.

**Comment by kybos** [comment]
Change log:

    - New: Ability to assign custom colors to individual tracks.
    - New: Part colors follow the track color if not overridden individually.
           Old behavior can be restored in Appearance->Arranger. 
    - New: Part color toolbar. Drop-down to select current part color,
            button to assign current color (or track color) to selected parts. 
    - Fix: Parts created by double-click in range ignoring current part color.

Please check and let me know if there are any issues.
