### ISSUE TITLE
Feature Request: Quantize to grid.

### ISSUE THREAD

**Issue by alextone** [muse-sequencer/muse#653]
This is an FR suggesting a function that allows us to quantize to fill a specified grid space, including extending or adjusting either end of a note. So if a note is just after a beat, and extends slightly beyond the end of that beat,  we can quantize to automatically adjust position and length to fit and fill that beat, with some sort of quantize to grid.

Alex.

**Comment by drautzburg** [comment]
I remember some Atari sequencer ("Creator"?) had such a feature. Basically you could quantize to a given "groove" and it was called "groove-quantize". Today "goove-quantize" still gets 1/4 million matches on google, so I believe it is still a thing.

In this old sequencer, quantization was a thing applied during playback. This way, your original recording was never altered and you could change the quantization several times or even go back to unquantized. I liked this a lot. 

This was a pattern-based sequencer and you could have different quantization for different patterns. This does not translate easily into MusE, because here are no patterns, but parts and today's playback settings are per-track and not per-part.

**Comment by kybos** [comment]
Quantize to grid: What is the difference to the existing quantize function (Functions->Quantize)? It does exactly that IMO.

Groove quantize (like e.g. in Cubase) is a completely different thing I would say, and a very complex one. Includes analysing a piece of music (midi or audio), trying to extract the groove/feel and transfer it to another piece of music. Quite a big project to implement IMO.

On-the-fly quantizing: I think that was more relevant in the "old days" when there was no Undo function in the sequencers.

**Comment by kybos** [comment]
Request unclear and no reaction, closing.
