### ISSUE TITLE
Parallel make fails

### ISSUE THREAD

**Issue by nick87720z** [muse-sequencer/muse#659]
I have museseq-3.1.0_pre2 under gentoo - in my local overlay. I don't remember, when I had such problem before, but when I try to build with make flags -j2, it sticks at copy_on_write_base.h" due to missing "ui_copy_on_write_base.h". With -j1 it is ok.
Problem appears with both release 3.1.0_pre2 and fresh git trunk.

I have no patches applied, affecting 'muse/components' dir.

Build system:
cmake version 3.14.3
GNU Make 4.2.1
Python 3.6.5 (for cmake - who knows wether it doesn't make sence)

Since all of this has patches to satisfy gentoo requirements for quality and other specifics, I would not state it is definitely muse bug.

**Comment by terminator356** [comment]
Hi, there should not be any trouble with -j, I use -j4 all the time.
However, if there is already an existing build directory, sometimes a re-build can be
 notoriously fussy especially if major code changes come down the line via a pull.

Deleting the build directory and starting from scratch usually solves this.

If not, I'll have to try to replicate this problem and re-arrange the build sequence to get it right.
Hm, that will be hard to replicate, since both -j1 and -j4 work for me :-(

If all else fails, you can try another option: Build MusE as a static, (mostly) monolithic app.
To do this, supply the
`-DMODULES_BUILD_STATIC` cmake option.
Some packagers also like to add this, to ensure integrity, but it should not be required:
`-DCMAKE_SHARED_LINKER_FLAGS=-Wl,--no-undefined`

There's no harm in building MusE as static, it just means the main app is a
 very large self-contained executable with many internal libraries built-in,
 instead of a small executable with many separate internal library files.

Tim.

**Comment by nick87720z** [comment]
I get it stable with -j2.

But -j4 is ok for me too. As well as with -j50 - as test for parallel make to cause all available jobs to be done at the same time. Though -j50 seems to be not complete for muse. I tried before completely ridiculous -j200, but it eventually made my system irresponsible (after interruption I found it was in swap, so I had to get it back with swapoff/swapon). When I interrupted it, it was at 20%, without any mentions of 'ui_copy_on_write', so no idea wether it would fail or not, but at least %50 passed - I interrupted it after it  processed 'copy_on_write.ui'.

According to docs, passing -j without arguments means unlimited jobs number (anyway, my system would not do it).

Before even setting -j2 as global make options, I tried better approach like -j3 -l1.8 (i.e. max 3 jobs, but limiting load... could be just -j -l1.8). Which causes even more applications to fail to build, comparing to -j2 (or just any -jN without -l). This also make it reproducing with muse.

**Comment by nick87720z** [comment]
It seems, problem appears in waveedit, where "copy_on_write_base.h" is included.
More reliable way to reproduce is like this:
`$ make -jN -f muse/waveedit/Makefile` - this time I get it even with -j4 and just -j (I had to switch to console, shutdown my desktop session and display server with all remaining processes from my session, to free all possible memory, and still with default usage 200Mb it took 13Gb of full memory to complete, while my RAM is 8Gb).

Before this attempt I tried:
`$ make -jN -f muse/components/Makefile`
which was ok with any jobs - in any way all qt pre-generations were done before compilations.

If cmake allowes, it could be solved by adding dependency on `ui_copy_on_write_base.h`.
Something like:  
```
ui_copy_on_write_base.h: copy_on_write_base.ui
    uic ...

wavecanvas.o: ui_copy_on_write_base.h
     $(CXX) ...
```

**Comment by terminator356** [comment]
> $ make -jN -f muse/waveedit/Makefile
What directory are you executing this command from?
There is no Makefile in muse/waveedit, only in the build tree.
This suggests you are not creating a separate build directory
 to keep the build files from polluting the source tree.
Please follow the directions in README.
Otherwise the source tree may be polluted with build files.

And, apologies, as I had to point out recently, there is a mistake in README,
 these old instructions say:
`
      - To compile MusE, run the following commands from the 
         top level directory where the source code was unpacked
         (the directory where THIS README FILE is found): 
`
It should say:
`
      - To compile MusE, run the following commands from the 
         directory where THIS README FILE is found: 
`

**Comment by nick87720z** [comment]
> > $ make -jN -f muse/waveedit/Makefile
> What directory are you executing this command from?

I meaned build dir. I use it separate from source dir (for above experiments it is just 'build', placed in same dir as toplevel CMakeLists.txt.

**Comment by kybos** [comment]
I added the required dependency to the cmake file.
Please reopen if the problem persists.
