### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by moebius1** [muse-sequencer/muse#660]
Bonjour,
I'm absolutely unable to find what's wrong ; I've got this message when trying compiling : 
CMake Error at muse/CMakeLists.txt:389 (install):
  install TARGETS given target "lv2host_module" which does not exist.

-- Configuring incomplete, errors occurred!

What am I supposed to do ?
cordialement,

**Comment by terminator356** [comment]
Which version is being compiled? The current git master?
Other users have compiled it without error.
Try pulling a fresh git copy and start from scratch, if that has not already been done.
Or, delete the 'build' directory and try again.
Be sure to follow README instructions or simply use 'compile_muse.sh'
 to be sure that the build directory is correct.

**Comment by moebius1** [comment]
Bonjour,

Thank you for your fast answer.

Yes, it's the current git master ; I've tried a fresh installation too 
with same result

When trying 'compile_muse.sh' instead of  './compile_muse.sh' I get the 
error :

bash: compile_muse.sh : commande introuvable (-> command not found)

well , the strange thing is that everything worked fine before ; I'm 
running Debian testing, could it be the reason why ?

cordialement,


Le 24/07/2019 à 19:18, Tim a écrit :

**Comment by spamatica** [comment]
Hello,

I think I just experienced this error with lv2host_module.
The reason seems to be that MusE now defaults to using the systems LV2
libraries. There was a line in the configuration output about setting
ENABLE_LV2_SUPPLIED as a last resort. I did this and it compiled.
I suppose there is a reason for using system libraries instead of our own
so probably it's better to make sure all LV2 dev packages exist on your
system.

/Robert

Den tors 25 juli 2019 kl 17:40 skrev moebius1 <notifications@github.com>:

**Comment by terminator356** [comment]
Oh, yes! Sorry I forgot to mention, I have now completely removed
 all internal LV2 support (too hard to maintain).
Therefore ENABLE_LV2_SUPPLIED is not an option any more.
That is why I suggested pulling a fresh copy from git and starting from scratch.
Because it might be possible that an existing build would become confused
 about these changes. Instructions in README  were updated.

**Comment by spamatica** [comment]
Closing as there has been no further communcation. If there still is a problem to build, make a new ticket or ask on our forum.
