### ISSUE TITLE
aux does not work for synth tracks

### ISSUE THREAD

**Issue by spamatica** [muse-sequencer/muse#681]
Been doing some testing with the latest release and finally came around to reporting this issue, the problem is actually not that new.
Had a look at the code but there's a lot going on so I have no real clue how to figure this out.

**Comment by terminator356** [comment]
Hi. I'm testing a synth track outputting through an Aux track outputting to an Audio Out.
Seems to be working. Give a test file?
Was this with multichannel synth channels beyond 1 + 2?
Was latency correction on?
Still, should work, should have sound, hopefully.

**Comment by spamatica** [comment]
Ah, yes, bad testing again, sorry. It appears it is not the synths, as I got a generic synth to work now too.

I use Addictive Drums regularly and I've tried adding a reverb on it with an Aux without success. I see now it is likely the cause is that it is multi channel, as you were sorta suggesting.

I tried now with Black Pearl Drumkit Multi and it behaves the same. The Aux does not get any audio regardless which outputs I enable. I guess multis are a special case and misbehave in this scenario?

I was thinking it affected all synths, now that it looks like it's only multis it does not seem terribly important to fix, it can be worked around by routing through a group track.

**Comment by terminator356** [comment]
Hm. Tested. You're right! No audio from aux when fed from a multichannel synth.
It ain't workin'.
The audio that comes outta those first two channels, which you can clearly see
 activating the synth track meters, should be the very same audio sent to the aux.
Yet there's nothing there. Blimey!
Meanwhile it works OK with the non-multichannel version. Hmmm...

**Comment by terminator356** [comment]
D'oh! Hence my comment in the aux section of AudioTrack::copyData():
"FIXME TODO Need multichannel changes here? Yes"
Yes, I see that it only handles 1 or 2 channel sources and completely ignores
 if there are more source channels available than that.
Thanks! Sorry 'bout that. I'll getcha' up and runnin'..  Will try to fix, hang in there...

**Comment by terminator356** [comment]
OK Here ya go bro! Fixed in git master.
Tested OK with various multichannel synths and aux and group configurations.
Both mono and stereo.
Do keep in mind that when using route channels (not omni), switching a track
 from stereo to mono and then back to stereo may cause the loss of the second route.
You just have to reconnect that second channel route again.
(Same as it's always been in MusE like with Audio in/out tracks and Jack routes.)
And remember that what you see on a mixer strip applies ONLY to the
first two channels. Any further channels need to be routed separately to other strips.
In know, it's not obvious to the user sometimes...

**Comment by terminator356** [comment]
Hey Robert, I must ask: How in the heck are you running A.D.?
Are you going to tell me you actually have dssi-vst running?
On 64 bits? Nah, you must be running 32 bits? How'd you do it?

**Comment by spamatica** [comment]
Great with the fix, will check later!

Regarding WinVST, right, maybe I should write it up somewhere public..
I believe it's 32-bit AD but the tool supports 64-bit too. That the OS is 64-bit is actually not of any consequence as WINE has libs for supporting both architectures (to my understanding, there is quite a lot of black magic here).

DSSI-VST was a long time since I got working. And it's a bit sad since I think it had better performance than the one I use now..

I know of atleast two alternative VST compatibility tools:
Airwave - https://github.com/psycha0s/airwave
LinVst - https://github.com/osxmidi/LinVst

I use Airwave as it has worked better for me, it was a real hassle to setup though..
I see now that LinVst seems very actively developed so might be an idea to try it again.

**Comment by terminator356** [comment]
Psst! I just tried once and for all to build dssi-vst again.
It worked! It was much **easier** than my previous attempts.
A simple edit to the makefile, and of course make sure the 32-bit versions of
 gcc and jack etc. are installed, et voila!
I am seriously considering stripping the un-needed vst-host part away
 and building the source right into MusE using our cmake instead of a makefile.
It's do-able! Take a look:
![dss-vst-screenshot_1](https://user-images.githubusercontent.com/5422362/69169942-37d99f00-0ac7-11ea-8b7f-d84ac22ceaed.jpeg)

**Comment by terminator356** [comment]
Hey man! Read your post from 2015 here:
[https://www.linuxmusicians.com/viewtopic.php?f=47&t=14817&sid=81abc243ed9d906840b37f5b24cd9d5a](url)

> What happens is that discovery of VST plugins works fine but instantiation leads to this (to me) wierd error message being spewed out by jack over and over again:
JackEngine::XRun: client = dssi-vst was not finished, state = Triggered
JackAudioDriver::ProcessGraphAsyncMaster: Process error

Yep. Exact same slew of continuous xruns here as well.

> To my understanding jack shouldn't really be aware of dssi-vst so I don't know how the connection has been set up. Tried with both MusE and Qtractor, same result, so I believe the host is not the source.
Anyone know if there is a work around or whereabout to dig deeper?

Ehm... Jack was linked in here:
[https://github.com/falkTX/dssi-vst/commit/5f984818e51ebf377e721a0d4b649983cb628d5e](url)
There's a very good reason for that. To provide transport information to the vst.
Without it, some plugins refuse to make sound.
And what better way to get that realtime information than Jack transport.
Actually there is no other way. Host cannot pass accurate and reliably timely transport info
 through a delayed client-server path.
Unfortunately, I found that simply because it opens a Jack client, Jack makes dssi-vst
 transport **master**, stealing master away from MusE or other host.
Then useless (no) info is displayed in QJackCtl's time window.
If you observe that a vst plugin is not producing sound, look at QJackCtl's time window.
You'll notice there's no Bar Beat and Tick even when MusE is playing.
**Cure:** Simply open Settings > Midi Sync and make MusE the master again (**toggle** it !).
**I will try to do that in code when MusE starts as I noticed we don't do it.**
(I never wanted to **force** MusE to be the transport master, but now we'll have to do it.)

Sooo... about that continuous stream of xruns:
I am guessing but I can only think of one thing that might be trouble:
Usage of both Jack 64 bit and 32 bit libraries at the same time?
Jack is having trouble completing the graph process because of it?
I am checking the dssi-vst code... will try removing the Jack client to see
 if it at least cures it.    Stay tooned... Cheers.

**Comment by terminator356** [comment]
> Actually there is no other way. Host cannot pass accurate and reliably timely transport info
through a delayed client-server path.

Hm, really? What about the audio shm then?
I should have written there's no **mechanism** available that all hosts could use,
 other than say, midi sysex or something.
However, if we include dssi-vst with MusE, then we can do whatever we want.
Because... we're freakin' MusE, eh ;-)
For example add a small extra shm to hold the live realtime transport info.
Then we should be able to **eliminate** Jack from dssi-vst!

**Comment by terminator356** [comment]
Meh, instead of going backwards, let's go forward.
dssi-vst is dead and the maintainers say it's because there are much better tools now.

Now, I've never used Carla. I thought it was just a plugin host.
But here's what it says:

> Carla currently supports LADSPA (including LRDF), DSSI, LV2, VST2, VST3 and AU plugin formats, plus SF2 and SFZ file support.

> Carla should make it possible for others to use it within their projects.
This is achieved by means of a simple API, plus Carla itself as a plugin. 

Well then. Let us look more closely this...

**Comment by terminator356** [comment]
(Sorry if I'm rambling on. But well, this is important interesting stuff.)

Great:
---------------
Carla is **way cool**. It loads as an LV2 plugin right in MusE.
From there you can load all them formats listed above.
There's also a router and more.

Sucks:
---------------
Caveat. On my distro, and I'm guessing a lotta others due to licensing, Carla was built
 **without** the necessary windows bridges. I was unable to test. Apparently **Arch Linux** does?
To build Carla with that, you need among other things, the **mingw** compiler.
Not sure why mingw, but yeah. I looked and don't think it's on my distro.
There are only 'experimental' packages available. So I'm not gonna go that route.

Bottom line: Relax. If users have Carla (+/-win) it means in theory we need do nothing more.
Leave it up to them and let Carla mature.

---------------------

Sooo... The depressing lack of Carla Win support on my distro got me thinking, seriously:

1: To **get rid of Jack** in dssi-vst (Tested: Yes, that **IS CAUSING** the xrun problem above),
 we need to replace its calls to Jack **transport** with **something**...
 ...something else where **we** pass that info.

2: That something is **LV2**.
What have I been yapping about for the last few days in the other 'fixed' thread?
LV2 TimePosition (transport).

3: Therefore I propose that we strip away the DSSI part of dssi-vst and modernize it with:
Drum roll...
**lv2-vst**.

A quick google seems to reveal no such thing.
I'm thinking it should be relatively trivial to replace the dssi wrapper with lv2.
Come on, how 'bout one last kick at the vst can, R.J. ? _You_ helped on that thing! He he.
I'd love to try it.
I'll wager FalkTX would be pleased. This bug goes waaaay back now.

**Comment by terminator356** [comment]
LinVST does exactly that last bit! I built it months ago but never used it or studied it.
It was made from dssi-vst. It makes the plugins appear as LinuxVST plugins.
Ah... I understand now. LinVST **had** to be different because VST2
 does not support multiple plugins in one library I believe. So LinVST cannot
 do the same trick dssi-vst (and ladspa and dssi) did - only **one** library file.
Yeah, that certainly was a nice trick to have eh?
So instead LinVST must essentially make a bunch of copies of itself all over the place.
Thus sadly you must convert all the plugins first.

Turning to an LV2 version then: Er, well, I'm studying it and I'm not sure but it 
 appears there was not such a thing until recently. Manifest ttl's and all that.
drobilla has added something called 'Dynamic Manifests' which might be the answer.
Which leaves the question, how does Carla do it then?
I think it only loads them in an 'effects chain' style, not as separate plugins.
Still, Carla has a feature to export to a single LV2.
Maybe that answers my question - no multiple plugins in one plugin like ladspa/dssi?
Cheers.

**Comment by spamatica** [comment]
Hi Tim, wow that's a lot of messages :D

I see the thread I wrote in 2015. There was a crucial message missing
though (someone must have deleted their user or something) that the origin
of the xruns was known. It was due to a low level change in the kernel. If
I recall correctly it had to do with futexes. The interprocess
communication used by dssi-vst would break down due to a block that was
never lifted.
Maybe it is still the same and the mechanism used by dssi-vst only worked
by coincidence (or it is actually a long standing bug in the kernel)? I
don't know but it seems a lot of work to get it to work then.. and as you
say it is an old solution and has necessary drawbacks in that transport has
to be hacked on, probably other stuff too.

The good part of dssi-vst is that it can dynamically make an inventory of
plugins, I didn't realize that the reason for the change to not do it
dynamically was because VST does not support multiple plugins, makes sense
now.

As to hacking up an LV2 version of one of the current solutions. Cool
thing, but as I understand you the reason is to get rid of or simplify the
conversion phase as above? Then there must be easier solutions?

Now, I don't remember how LinVST did the conversion but Airwave has a
little gui where you explicitly pick each plugin you want converted. It
can't be that hard to make it pick a folder instead and make it convert all
contained plugins instead. That it produces individual .so files is a side
effect, but they hardly take any space, it would not bother me.
Maybe there are already tickets on these projects to provide batch
conversion. I would prefer for someone else (other project)  to take
ownership of the problem, so to speak ;)

Cheers.


Den ons 20 nov. 2019 kl 07:03 skrev Tim <notifications@github.com>:

**Comment by terminator356** [comment]
Thanks for the clarification.
My enthusiasm was because one does not have to manually convert plugins with dssi-vst.
These other solutions seem to require that. So if we could make an LV2 version that'd be cool.

**Comment by spamatica** [comment]
Yeah, I realized after I wrote that that is a big part of it. And that I guess can't easily be fixed with the VST solutions. 
Would be a nice improvement, still seems a lot of work..

**Comment by terminator356** [comment]
More reading confirmed that this is exactly the kind of thing LV2 Dynamic Manifests is for.
Where LinVST cannot make one single plugin file like ladspa/dssi/dss-vst, LV2 can:

> The LV2 API, on its own, cannot be used to write plugin libraries where data is dynamically generated at runtime (e.g. API wrappers), since LV2 requires needed information to be provided in one or more static data (RDF) files. This API addresses this limitation by extending the LV2 API.

I should at least provide the support for it in MusE first before attempting anything ;-)
We have the header but no further code for it.
Some suites like NASPRO use this feature to house all the plugins
 instead of multiple ttl manifests and so on.

**Comment by spamatica** [comment]
Hehe, true. 
I'll close this ticket btw as I've tested it as working :)

**Comment by terminator356** [comment]
Aww, I wanted to ramble on some more, he he.
Just kidding. Time to move on...

**Comment by spamatica** [comment]
Hehe, rambling is allowed in other forums :D
