### ISSUE TITLE
Soft synths and HiDPI

### ISSUE THREAD

**Issue by kybos** [muse-sequencer/muse#697]
Most of the native plugin GUIs open a window that is much too big, normally twice the height/width of the real GUI. I suppose this is caused by Qt scaling the complete UI for HiDPI, so it expects that the content of all windows will be scaled as well. This is even the case with Helm, despite its scaling capabilities.
With Calf plugins the problem is a little different, they open a huge window over the whole screen, which they do fill out, but the content is scaled in a weird way. It takes a couple of seconds before the window comes up.
I assume this is a difficult topic, Ardour and QTractor show similar problems (and more crashes for that matter), only Carla gets it right in most cases.

![image](https://user-images.githubusercontent.com/10009541/69359367-bd587d00-0c88-11ea-91d2-ca51926e5201.png)

![image](https://user-images.githubusercontent.com/10009541/69359493-f98bdd80-0c88-11ea-9944-14769e9beb2d.png)

**Comment by spamatica** [comment]
I have access to a few different computers that I sometimes run muse on. All kubuntu but different releases, which means different qt versions. I find that there are sometimes issues on one of them but not on others, nothing that I have bothered looking deeper at yet.
I don't have access to any HiDPI screens but one of the computers has an NVIDIA card with their proprietary drivers and the rendering shows similarities to this.

**Comment by terminator356** [comment]
Ouch! Man that's fugly! Look away children!
Question: Can you scale the windows back to their normal size?

My apologies. I borrowed some cards from an employer and my neighbor 
 offered to let me use his display, but things kind dragged on and I gave the cards back.

**Comment by kybos** [comment]
No, the windows are not resizable.

**Comment by terminator356** [comment]
Seems to suggest we could fix that on our side since we make the container window.
But... I think we ask the plugin UI for the minimum size.
So maybe it is the plugin's fault after all. It seems to look like that with Calf.
Should we do a hack and scale what it tells us by using say, the hidpi device pixel ratio?
I'm not sure. Looks like Calf might not even allow itself to be resized below what's shown,
 seems to make up its own mind. Should all the plugins be fixed if it's their fault? Big task.

**Comment by terminator356** [comment]
@spamatica Interesting point about the drivers, good question.
@kybos What card and drivers are used? Sorry if already stated.

**Comment by kybos** [comment]
Yes, I am sure it's the plugins' fault. Many of them are quite old and the UIs certainly not state-of-the-art.
When I find time, I will perhaps have a look how Carla does it.

**Comment by kybos** [comment]
I have NVIDIA with the proprietary driver. And I mostly use Cinnamon and XFCE as DE.
That's one point I will check.
But I still think it's more the Qt state-of-the-art scaling vs. incompatible UIs/frameworks issue.

**Comment by terminator356** [comment]
I just checked Calf and was reminded that it dynamically lays out its controls
 to the window size, unlike the others.
This suggests that perhaps applying the hack (device pixel ratio?) I mentioned 
would fix Calf as well.
Lemme find the place in the LV2 code so that you can try if you like...

**Comment by kybos** [comment]
Yes, Calf is different and very special.
Thanks for looking into it.

**Comment by terminator356** [comment]
"The place in the LV2 code..." Oops, sorry it's worse than that.
Search the word 'minimum' (as in size) in lv2host.cpp
There are several places and techniques depending on the UI type (gtk or Qt or X11 etc.)
You'd have to apply a hack to each section. maybe try one at a time for each UI type.
But clearly you can see that each section asks the plugin for the minimum size
 that we set our container window to, and if the plugin has no such values we supply our own.

**Comment by kybos** [comment]
Yes, that's exactly what I expected.
Qt multiplies the plugin's minimum size with the device pixel ratio (=2 in my case) and then you get this big window...

**Comment by terminator356** [comment]
I wonder... Perhaps the plugins **are** reporting their correct size to us,
 and we are dutifully setting those 'correct' values on our container window minimum size,
 but really it is Qt that is messing with the final result.
You'd have to step in there or turn on some debugging messages or
 add some fprintf checkpoints to really see exactly what values are being given to us
 by the plugins. Maybe we're simply not turning on a setting on our container window.
Maybe the more specific hidpi Qt functions would help rather than the application-wide
 hidpi fix that user 'hfiguire' added a few months ago. See main.cpp I think.

**Comment by terminator356** [comment]
Here is the fix from hfiguire in main.cpp, version check by me:
`
        // Now create the application, and let Qt remove recognized arguments.
#if QT_VERSION >= 0x050600
        QCoreApplication::setAttribute(Qt::AA_EnableHighDpiScaling);
        QCoreApplication::setAttribute(Qt::AA_UseHighDpiPixmaps);
#endif
`
Would I be correct in stating that this fix is having a negative impact
 on the plugin UIs, since many were not designed for hidpi?
How about we turn off that setting just for our container windows? 
Let the window be the 'natural' size since the plugin can't handle hidpi?
If it is the case where **modern** Uis have no problem, and we cannot
 find a way to automatically determine whether to use the hidpi setting or not,
 then as a last resort we can add a button to the new 'Quirks' section on the generic UI :-)

**Comment by terminator356** [comment]
BTW At some point I am planning to finally get around to adding said buttons
 at the top of the **native** UI container windows, just like Ardour and almost every other DAW.

**Comment by terminator356** [comment]
Oh I see now. There is no per-widget hidpi setting. It's only application-wide.
Ew... Yes, a difficult situation. Here we have mixed content in one application.
Looks like that minimum size adjustment hack might be required?

**Comment by kybos** [comment]
Exactly.
Qt::AA_EnableHighDpiScaling must be set before the actual app object is created and it is application-wide. 
By the way, the typical problem with this settings is that it does not work with all (HiDPI) monitors and in VMs, so from my experience it's better to deactivate it and set the scaling explicitly in the system environment (e.g. in ~/.profile), like this:
export QT_AUTO_SCREEN_SCALE_FACTOR=false
export QT_SCREEN_SCALE_FACTORS=2[;2..., one for each monitor]
More on this here: https://doc.qt.io/qt-5/highdpi.html

So yes, special hacks would be necessary.
I would say Qt-based plugins (like synthv1) scale correctly, probably also GTK3 (don't know about any plugin using it), but that would be a dangerous assumption to implement... I know that FLTK4 works well, as I compiled a HiDPI version of Yoshimi against it and it scales well in all DAWs.

**Comment by terminator356** [comment]
If MusE would benefit from the hidpi setting being in some way user-selectable, feel free to add it.
I noticed a few apps have such a setting.
Also if the proposed plugin window hack ultimately needs user decision and intervention,
 the new Quirks buttons section awaits with open arms.

**Comment by kybos** [comment]
No that's not possible, the HiDPI setting is always application-wide, no matter in which way you set it.
The apps that have such setting usually use a framework with no support for HiDPI (prominent example GTK2), so they have to implement the UI scaling "manually", which can be a considerable effort and is mostly incomplete or broken (Ardour, Inkscape, Gimp...). But then they can make it switchable, obviously.

**Comment by kybos** [comment]
Now that looks better:
![image](https://user-images.githubusercontent.com/10009541/69483572-41e20180-0e29-11ea-832a-aaa88322153f.png)

I will provide a PR. 
The fix does not even seem as critical and dangerous as I originally thought.

I will check the VST plugins as well, they have exactly the same problem.

**Comment by kybos** [comment]
> Also if the proposed plugin window hack ultimately needs user decision and intervention,
> the new Quirks buttons section awaits with open arms.

After some testing, I think it would be good to have an individual setting for each available plugin (to reset the hidpi scaling).
I tried to implement this using the Quirks, but noticed then that these settings are song and even track specific, so this is not what is needed here (a global and permanent setting for each plugin). Is there functionality to support that? (Not sure, but I wonder if the other settings you have in Quirks should not be global as well?)
If it's not possible, then I would create only one generic setting in the GUI options for this, since the window size adjustment is working well with most plugins, some can get too small at first display, but the window is resizable in that case, so that's not a big issue.
All that only affects HiDPI, of course, I'm taking care not to touch the normal screen resolution handling.

**Comment by terminator356** [comment]
Yes I mentioned that I really wanted to make the Quirks global (set and forget).
But there wasn't enough time. I would need to construct a global 'quirks editor'.
That's tricky since plugins are housed in two different places: A plugin list and synth list,
 and each is accessed from different dialogs.
I suppose consider these quirks 'local overrides' until we get actual global settings,
 then these can override the global settings. Or something like that.
