### ISSUE TITLE
Second instance of MusE hangs on start

### ISSUE THREAD

**Issue by kybos** [muse-sequencer/muse#701]
Just noticed that, when I forgot that MusE was already running:
The second started MusE instance keeps hanging with the splash screen and has to be killed.
If it's not possible to run several instances in parallel, there should probably be an explicit check and and an error popup informing the user.

**Comment by kybos** [comment]
Still worse, even if I close the first session, then MusE does not start any more.
In debugger I can see that it always stops at the following (jack.cpp):

      jack_client_t* client = jack_client_open("MusE", (jack_options_t)opts, &status);

I then have to restart Jack to make it work again.

**Comment by kybos** [comment]
Seems to be a local, problem not always reproducible, closing...

**Comment by terminator356** [comment]
Hi. Should be no problem running multiple instances.
I do it sometimes to test our own inter-app features if there's
 'nobody else to talk to with that feature'.

Hanging with Jack is always a problem. It usually means that:
A: You've been debugging an instance and at some point breaked on a breakpoint,
 even though you continued. Well, Jack does not like that sometimes and you will find
 that you must kill Jack and QJackCtl etc. Otherwise MusE may not quit correctly
 and/or may not start again. I asked about avoiding that once on Jack devel lists,
 but the response was that it's just the way it is - tricky.

B: Make sure Pulse is working correctly and that you have the PulseAudio-Jack sink
 working correctly and that your system can fall back to either one properly when the
 other is not in use. Otherwise all manner of hanging can occur with MusE.
If you can watch YouTube with either Jack or Pulse running, or both, then you're probably OK.
