### ISSUE TITLE
Surge VST soft synth crashes

### ISSUE THREAD

**Issue by kybos** [muse-sequencer/muse#708]
When I try to insert a track for the VST version of Surge, there is a segmentation fault.
It should be easily reproducible, if not, I will provide more details.

**Comment by terminator356** [comment]
And easily fixed. Thanks!
The one vst that decides to call our pluginHostCallback() immediately from
 VstNativeSynth::instantiate() before we stored the pointer.
Added VstNativeSynth::openPlugin() which is called later.

If I may add: Very nice UI. Has a professional pedigree, as I read.
Within 2 minutes of using it I stumbled upon this patch:
"Canadians".
Ha! Funny, I don't feel like that sound. Must be an 'up north' or 'prairie wilderness' thing.
I'm thinking the plugin is Canadian. Why else would that be there? No one ever thinks of us.

**Comment by spamatica** [comment]
>
> "Canadians".
> Ha! Funny, I don't feel like that sound. Must be an 'up north' or 'prairie
> wilderness' thing.
> I'm thinking the plugin is Canadian. Why else would that be there? No one
> ever thinks of us.
>

:D could be... but we're thinking of you :)

**Comment by kybos** [comment]
;-).
Fix works, the crash is gone, thanks.
There are no patches to be selected in the mixer strip, the sounds can only be switched from the native UI, is that correct? Surge does seem to be somewhat special, it does not respect my new native GUI size setting either, it resizes itself quite uncontrollably...

**Comment by terminator356** [comment]
I noticed that too. There is only one vst patch called Init.
And there are no LV2 presets or patches. Many other plugins don't as well.
That's usually the plugin's fault. All we do is query and list.
We know that it is working because it finds patch Init.
I mean, I don't think we're doing anything wrong.
It's a very simple vst discovery mechanism.
PS: Don't mind the 'sawdust on the floor', work in progress,
 some printouts left in there while I'm working on something...
