### ISSUE TITLE
Qt Stylesheets: Dead? Dying?

### ISSUE THREAD

**Issue by terminator356** [muse-sequencer/muse#721]
Just to start a conversation about this, especially in reference to future Qt6:

Ever since Qt stylesheets appeared and folks started adding it to MusE, I've
 been worried. It's like voodoo. It feels invasive, foreign, 'icky' to a C++ widgets API.
There are things I really don't like about it that caused headaches.
Whenever more and more stylesheet code is added to MusE,
 sometimes even necessary as demonstrated by the 'scrolling menus'
 and so on, I worry about the future.
But we are told not to mix widget code and stylesheets.
I try to stay away from them and only try to 'support' them in my code when needed,
 so my code is mostly all about the widget API.
One MusE fork used them a lot. It was mostly all about the huge master stylesheet.
There appears to be no 'stylesheet editor application' like QtDesigner.
I am weary of the idea of hand-editing huge stylesheets.
The interplay between them and C++ is kind of poor.

What do you all think about it? Anyone keeping up with Qt6 plans?
There was talk of deprecating stylesheets. But some positive talk here:
[https://bugreports.qt.io/browse/QTBUG-68671](url)

Thanks.
Tim.

**Comment by spamatica** [comment]
We should have a developers forum for these types of discussion :) The
devel-mailinglist wasn't that reliable right?

As for the question at hand. I don't have that much input, don't know much
about coming Qt versions...
I've always had the fear that using it (the dynamic nature of it) would
have a big performance impact..
I sometimes need to parse other style sheets (not very often though) and I
think it's a hassle.. very powerful but not a /fun/ technology.

So, I guess, keeping the use to a minimum is probably my stance.

Den tors 5 dec. 2019 kl 00:18 skrev Tim <notifications@github.com>:

**Comment by kybos** [comment]
As I see it now, it's difficult to find sufficient information on how the style concept is going to develop in Qt6, and how exactly it is supposed to replace the current one.
The current concept has its drawbacks, but it's very powerful (you can do things with it that are not possible with other means), and, once you start using it, there is no way back, because the style sheets take precedence over the Widget attributes, so every UI adjustment must be done with a style sheet as well to be visible at all...

**Comment by kybos** [comment]
Sorry, did not mean to close...
