### ISSUE TITLE
Source file missing

### ISSUE THREAD

**Issue by plinkplinkfizz** [muse-sequencer/muse#759]
I ran into an issue building muse from git:

> /var/tmp/pamac-build-gaurav/muse-git/src/muse/muse3/muse/components/copy_on_write.h:26:10: fatal error: ui_copy_on_write_base.h: No such file or directory
>    26 | #include "ui_copy_on_write_base.h"

The file is apparently missing

**Comment by terminator356** [comment]
Hello. This sometimes happens when major changes occur, such as when major
 folder or file movements occur, which recently happened.

Was this a fresh build or an update of an existing build?
An existing build folder can become confused, giving the error.
If your existing build was simply updated from git master, you should wipe out your build folder
 and rebuild from scratch. Or, wipe out the entire tree and pull a fresh copy from git and
 build from scratch.
Usually this solves that problem. Let me know how it goes, if any trouble.
Thanks.

**Comment by plinkplinkfizz** [comment]
> Hello. This sometimes happens when major changes occur, such as when major
> folder or file movements occur, which recently happened.
> 
> Was this a fresh build or an update of an existing build?
> An existing build folder can become confused, giving the error.
> If your existing build was simply updated from git master, you should wipe out your build folder
> and rebuild from scratch. Or, wipe out the entire tree and pull a fresh copy from git and
> build from scratch.
> Usually this solves that problem. Let me know how it goes, if any trouble.
> Thanks.

HI terminator,

This was a fresh build with a fresh `git clone` from hub.

Nothing turns up when searching for the file on github.

**Comment by plinkplinkfizz** [comment]
Duplicate of [Parallel make fails](https://github.com/muse-sequencer/muse/issues/659) #659

This problem is the same as in the issue mentioned above. Building with option -j1 worked properly. There is a possible race condition which may not really be triggering on all the machines.

**Comment by terminator356** [comment]
Thanks very much for the report. Glad you were able to build it.
I will try to reproduce the error here but I could not reproduce it before.
Looking at the cmake file for waveedit (for wavecanvas.cpp), it seems to indicate
 that I could try adding the components module to the target_link_libraries section.
Kick me again if I have not responded in a while... We're supposed to be releasing soon.

**Comment by kybos** [comment]
I added the required dependency to the cmake file.
Please reopen if the problem persists.
