### ISSUE TITLE
Plugin cache updated on each startup

### ISSUE THREAD

**Issue by spamatica** [muse-sequencer/muse#763]
As I understand it the plugin cache should only be updated when something has changed. On my system it seems to update on every startup of MusE.
Just putting a reminder here to check it out.

**Comment by terminator356** [comment]
Yes, I know. That's why I added the -C option (do not rescan cache).
Normally it is not supposed to rescan unless the plugin's date/time stamp changed.
It works fine normally. However that is the golden question - did something change?
It turns out that plugin wrappers such as dssi-vst and Carla present MusE
 with 'new' discovery information each time MusE is started.
In other words, it appears as if each discovered plugin within the wrapper
 is brand new with a new date different than the last time scanned!
This is not good. I'm not sure how we're going to handle this, except to 
 provide a special 'hack' do-not-scan blacklist for dssi-vst and Carla.
I've not had much time to look into it further, but that's the story in a nutshell.
I'm willing to bet you have one or both of those wrappers installed? Thanks.

**Comment by spamatica** [comment]
Hmm, not sure that is the case. dssi-vst is dead so I should not have any
of those and I'm pretty sure I'm not using Carla.
I will look deeper one of these days.



Den ons 29 jan. 2020 kl 22:46 skrev Tim <notifications@github.com>:

**Comment by terminator356** [comment]
Also, be aware that the scan check includes our own MESS synths.
When you code MusE, if anything affects the MESS synths, which you might not realize,
 they will be recompiled and reinstalled, meaning they trigger a complete rescan.
This can happen sometimes by innocently changing something that affects MESS.

**Comment by spamatica** [comment]
Quick test.
It's this test that triggers

    // Any remaining items in fpset must be 'new' plugins.

    if(!cache_dirty && !fpset.empty())

      cache_dirty = true;


fpset contains 8 additional items, some lv2 plugs from /usr/lib/lv2


	fpset	<8 items>	MusEPlugin::filepath_set
		[0] "/usr/lib/lv2/beatslash...]	1441704589000	
			first	"/usr/lib/lv2/beatslash.lv2/beatrepeater_mono.so"	QString
			second	1441704589000	long
		[1] "/usr/lib/lv2/beatslash...]	1441704589000	
			first	"/usr/lib/lv2/beatslash.lv2/beatrepeater_stereo.so"	QString
			second	1441704589000	long
		[2] "/usr/lib/lv2/beatslash...]	1441704589000	
			first	"/usr/lib/lv2/beatslash.lv2/beatslicer_mono.so"	QString
			second	1441704589000	long
		[3] "/usr/lib/lv2/beatslash...]	1441704589000	
			first	"/usr/lib/lv2/beatslash.lv2/beatslicer_stereo.so"	QString
			second	1441704589000	long
		[4] "/usr/lib/lv2/deteriora...]	1441702410000	
			first	"/usr/lib/lv2/deteriorate.lv2/downsampler_mono.so"	QString
			second	1441702410000	long
		[5] "/usr/lib/lv2/deteriora...]	1441702410000	
			first	"/usr/lib/lv2/deteriorate.lv2/downsampler_stereo.so"	QString
			second	1441702410000	long
		[6] "/usr/lib/lv2/deteriora...]	1441702410000	
			first	"/usr/lib/lv2/deteriorate.lv2/granulator_mono.so"	QString
			second	1441702410000	long
		[7] "/usr/lib/lv2/deteriora...]	1441702410000	
			first	"/usr/lib/lv2/deteriorate.lv2/granulator_stereo.so"	QString
			second	1441702410000	long


Some further checking reveals that atleast the first plugin exists in
two packages.

		[263] "/usr/lib/lv2/avw.lv2...]	1438971614000	
			first	"/usr/lib/lv2/avw.lv2/beatrepeater_mono.so"	QString

		[308] "/usr/lib/lv2/beatsla...]	1441704589000	

			first	"/usr/lib/lv2/beatslash.lv2/beatrepeater_mono.so"	QString


Could it be that the cache does not keep the path so both instances
will be stored as the same in the cache?

I'm tired and not up to debugging so I'll leave it at that for tonight..



Den tors 30 jan. 2020 kl 19:02 skrev Tim <notifications@github.com>:

**Comment by terminator356** [comment]
Checked it out today. The dssi-vst problems are not due to the time stamps after all.
I can see there are at least two problems with my code, likely requiring a rewrite
 of the cache file and intermediate temp file xml structure.
I believe I'll have to arrange the xml differently - as shells followed by contained plugins,
 instead of a flat list of plugins.
Because it is possible the shell may not report any plugins (empty VST folder etc.),
 so the scan checker finds no cache entry that corresponds to what it is seeing
 on the system, so it recreates the caches over and over again.
I observed this in the many debug runs today.

I will also try your plugins to investigate what's going on there.
Looking at your info is puzzling, should not happen I think.

Hang in there...

**Comment by terminator356** [comment]
Major fixes in master now.
Please see ChangeLog for heavy details.
Try it out, lemme know if any trouble.
Since this is important, I mentioned it on the team discussion board as well.

**Comment by spamatica** [comment]
I have an installation where there are some plugins that consistently give errors. Not sure I'm interpreting the result correctly but it seems to me that the caching is not satisfied with this and thus tries again on the next startup.
I could remove these plugins on my end but it would be good if muse could handle this issue, blacklisting these plugins as tested-nonworking. And the way to get past this is would be to initiate a full rescan.

**Comment by terminator356** [comment]
But that is what it is supposed to do. The cache blacklists plugins that fail a full scan,
 so that they aren't attempted to load upon next start.
More info please, what kind of errors? Which plugins?

Note that the scan includes all .so files found.
This means some .so files which aren't even plugins are included in the cache
 but are marked as 'unknown' so that they don't retrigger a full scan. IOW Some plugins
  have 'data' .so files and these are included in the 'unknown' cache file.
The cache system is supposed to account for all of this, and NOT trigger a rescan.

**Comment by spamatica** [comment]
Den mån 10 feb. 2020 kl 18:19 skrev Tim <notifications@github.com>:

> But that is what it is supposed to do. The cache blacklists plugins that
> fail a full scan,
> so that they aren't attempted to load upon next start.
> More info please, what kind of errors? Which plugins?
>
> Note that the scan includes all .so files found.
> This means some .so files which aren't even plugins are included in the
> cache
> but are marked as 'unknown' so that they don't retrigger a full scan. IOW
> Some plugins
> have 'data' .so files and these are included in the 'unknown' cache file.
> The cache system is supposed to account for all of this, and NOT trigger a
> rescan.
>
Alright, great, I'll make more tests.

**Comment by spamatica** [comment]
I think I found the problem I was having. 
It was one (possibly several) vst plugins that muse_plugin_scan could detect as vst but when trying to scan them it failed, this case went through the cracks, so to speak, generating an empty xml in return, instead of an "unknown plugin" kind.
Looks like it's working on my machine now.

**Comment by terminator356** [comment]
I see. Can you tell me the name of those vsts?
Maybe I can fix that... Thanks.

**Comment by spamatica** [comment]
As you saw I managed to make a fix that worked on my machine.
Atleast one of the plugs was not working, but I realize that the others maybe do work. I'll see if I can get a list and at least try them in another host.

**Comment by terminator356** [comment]
Yes and as per my comments I will review my code to see if I should not
 even be attempting to open dlls...
