### ISSUE TITLE
Downmix crackling

### ISSUE THREAD

**Issue by spamatica** [muse-sequencer/muse#765]
Did a downmix and the resulting file was full of clicks.
This was the first time I tried to do a downmix after updating to the release with time-stretch so this would be my primary suspect.

**Comment by terminator356** [comment]
What is your sound hardware? This is important, there are issues with certain hardware,
 that are not MusE's fault.
Also, can you upload an example of the downmix?

**Comment by spamatica** [comment]
Den mån 10 feb. 2020 kl 18:22 skrev Tim <notifications@github.com>:

> What is your sound hardware? This is important, there are issues with
> certain hardware,
> that are not MusE's fault.
> Also, can you upload an example of the downmix?
>
It's not a hardware thing as it was not audible during the mixdown but the
resulting wav file was compromised.
I will perform more tests though, as there could probably be numerous
reasons, I just wanted to write the ticket down so I wouldn't forget.

**Comment by spamatica** [comment]
[test4.zip](https://github.com/muse-sequencer/muse/files/4183039/test4.zip)
Here's a sample, simplest project I could make, an audio track with a wave file and a mixdown of a few seconds of that.
Running with jack at 44100 period 1024. Though as I said, it's not audible from MusEs playback, only the resulting wave file so the backend is probably not important. 
I can do more tests later if it's not reproducible.

**Comment by terminator356** [comment]
OK That's a constant crackling sound. It's definitely not a 'per-1024-cycle' dropout thing.

The reason I mentioned hardware:
Some ice1712-based cards may suffer from a problem with multiple CPU cores.
They may suffer from a constant crackling sound with more than one CPU core.
This was tested and verified extensively on two different machines under Windows and Linux.
It was also verifed by another user on LAD/LAU, and the solution (use one core) verified as well.
My card for example, a delta-1010, has this problem. It took me months to figure it out !
Believe me I get constant crackling if I don't run just one CPU core.
You may not hear it all the time - it drifts in and out.
The bounce may have just revealed the problem more.

If you have such a card, go to a website with a pure test tone and just listen for several minutes.
Eventually the crackling may appear.
Another way to test: Bounce a long, pure test tone, then listen to it and observe it in the wave editor.
You may see little spikes all along the way.

My point is the crackling in your test file does not _seem_ to be caused by the bounce.
It's seems too frequent and random to be related to 'per-cycle block transfers'.

Now, with all that said, I am aware of another problem related to bouncing:
Ironically, with just one CPU core, there's a problem with wholesale dropouts in the bounce.
Definitely not crackling, no, but mass dropouts along the way.
I identified the exact line causing this but I cannot recall if I fixed it. I must check again...

**Comment by terminator356** [comment]
Recall that you once told me, a few years ago, that you observed that
 a recorded or bounced file did not appear to be exactly the same as the original,
 that a comparison of the files revealed the sound was not quite the same, having
 little fluctuations or distortion or something like that...
I explained about the cards and CPU cores then as well.

**Comment by spamatica** [comment]
Ah, yeah, I do remember that, wow, that was a long time ago. It's even
possible that I was affected as I used to run one of those envy cards
(Delta 66)  =)

What I'm experiencing now is however not that issue.
This is on my audio computer and I do mixdowns all the time with good
results. It started happening after I installed the latest master release
(previous was before the timestretch was added).

It is absolutely muse doing something (as the timestretch was just added I
figured that was the likeliest candidate, some weird corner case with
stretch 0.0000005% maybe...)
As I wrote, playback through jack sounds just fine, even when doing
mixdown, but the resulting audio file has these very audible crackles.
I can work around it easily by doing the mixdown outside of MusE but it
would of course be best to find the source of the issue.

The hardware is a core i7 laptop (two cores I think) with an usb audio
interface Scarlett 2i2.
I'll try more, including to build without timestretch, and maybe try to
force single core somehow, hopefully tomorrow night.

Den mån 10 feb. 2020 kl 22:53 skrev Tim <notifications@github.com>:

**Comment by spamatica** [comment]
Seems it does not have to do with resampling, not the new infrastructure
anyway as disabling it, the best I could, did not make any difference.
Running on another computer now but downmix behaves the same.

Tried setting the core affinity with: taskset -c 0 muse3
but it does not make a difference.

Now, looking at the wave file I noticed that it IS actually periodic,
here's a screenshot
[image: image.png]
The spikes are exactly 12ms apart which is very close to the buffer length
in ms I have now (512).
It's just that the spike seemingly goes to a random value so it's not
immediately evident.

Some buffer copy that copies one sample too little maybe? Actually, looking
again at the screenshot above, every new spike goes back to a value very
close to the previous buffer start, so there might be something there.


Den mån 10 feb. 2020 kl 23:35 skrev Robert Jonsson <spamatica@gmail.com>:

**Comment by terminator356** [comment]
Bummer! Hm, I'll have to check. Maybe I didn't fix that offending line.
Maybe that's not even the problem...
Hang in there, I'm just finishing up some heavy work...
BTW I tried all that affinity stuff, I couldn't make it work. I carefully monitored the
 CPU 'hit counters' and the other cores were still being used.
The only way is to physically shut off the other cores either via BIOS or with:
 echo 0 | sudo tee /sys/devices/system/cpu/cpu1/online
 echo 0 | sudo tee /sys/devices/system/cpu/cpu2/online
etc.

**Comment by spamatica** [comment]
No rush, I can work around it for now. Maybe I'll even get to the point to
try and debug it.. or maybe not ;)

Den tis 11 feb. 2020 kl 19:04 skrev Tim <notifications@github.com>:

**Comment by terminator356** [comment]
We must knock this one out. Bad bug.
Question: Your bounce: Is it to a file or to a track?
I recall that bounce to file was OK I believe, during extensive testing.
* Some details on what I saw with bouncing and dropouts:
While bouncing to a track, there is a soundfile handle open (via one of our Wave)
 in write mode and writing the data to the file **in the realtime thread**.
But meanwhile, the ui code wants to display the wave as it being created - 
 **in the graphics thread** !
According to libsndfile, if I read correctly, it is a no-no to access a handle from
 different threads.
I concluded that this was causing the dropouts - the handle was being seek'd
 by two different threads, the one writing and the one drawing the wave.
In the resulting wave could be seen varying-size droputs at random times.
Forgive me I can't locate the offending line(s) - it's a on-two punch involving
 the writing code and the wave drawing code which sees that a wave is being
 created and wants to draw it.
I think Andrew either added or fixed the live wave drawing, remember?
My solution would be to **turn off** all 'live' wave drawing of recorded waves,
 until a solution can be found. Let's face it, this sndfile handle thread contention
 may be ruining our waves !
Note that I believe this only happens with bounce. With an actual live recording
 the live wave drawing seems to work OK because if I recall there are two 
 separate sndfile handles working there - the realtime and ui. With bounce it is attempting to
 use just one handle (since when opened for write it doesn't want or need a ui handle).
I think that's the story... Maybe not... need to re-verify if even recording is working.

It is possible that on other hardware that scenario is indeed the cause of something
 like your issue - even with all cores running, something that doesn't **seem** to
 happen here. (See the irony? I must turn off all cores to avoid my hardware crackling,
 but that induces the bounce dropouts! Oh, what is one to do...)

**Comment by spamatica** [comment]
Den ons 12 feb. 2020 kl 00:35 skrev Tim <notifications@github.com>:

> We must knock this one out. Bad bug.
> Question: Your bounce: Is it to a file or to a track?
> I recall that bounce to file was OK I believe, during extensive testing.
>

I do bounce to file, essentially to make a downmix. I've never learned the
habit of bouncing to tracks even though I probably should, for performance
reasons.


>
>    - Some details on what I saw with bouncing and dropouts:
>    While bouncing to a track, there is a soundfile handle open (via one
>    of our Wave)
>    in write mode and writing the data to the file *in the realtime thread*
>    .
>    But meanwhile, the ui code wants to display the wave as it being
>    created -
>    *in the graphics thread* !
>    According to libsndfile, if I read correctly, it is a no-no to access
>    a handle from
>    different threads.
>    I concluded that this was causing the dropouts - the handle was being
>    seek'd
>    by two different threads, the one writing and the one drawing the wave.
>    In the resulting wave could be seen varying-size droputs at random
>    times.
>    Forgive me I can't locate the offending line(s) - it's a on-two punch
>    involving
>    the writing code and the wave drawing code which sees that a wave is
>    being
>    created and wants to draw it.
>    I think Andrew either added or fixed the live wave drawing, remember?
>    My solution would be to *turn off* all 'live' wave drawing of recorded
>    waves,
>    until a solution can be found. Let's face it, this sndfile handle
>    thread contention
>    may be ruining our waves !
>    Note that I believe this only happens with bounce. With an actual live
>    recording
>    the live wave drawing seems to work OK because if I recall there are
>    two
>    separate sndfile handles working there - the realtime and ui. With
>    bounce it is attempting to
>    use just one handle (since when opened for write it doesn't want or
>    need a ui handle).
>    I think that's the story... Maybe not... need to re-verify if even
>    recording is working.
>
> Interesting, yeah, I guess it still could be due to concurrency, all I'm
really sure of is that the behaviour I'm seeing now is new. I'm prepairing
some new songs and I do downmixes all the time, it's only after the update
of MusE that I can hear these artifacts.

**Comment by terminator356** [comment]
Hm, bouncing to file?
I think I can wager it's **not** MusE's fault directly, per se. I will be very surprised if it is.
In this case there's no interaction with a UI thread. The file is just written and that's it.
I saw no trouble brewing there during testing.

Question: Is this with or without latency correction enabled?
This matters because the number of periods is taken into account.
I have read suggestions to use 3 periods with USB devices.

A quick search of "Scarlett 2i2 crackling" reveals a ton of problems.
I am seeing many, many complaints about this.
Here's just one example  - from our very own user funkmuscle:
[https://www.linuxmusicians.com/viewtopic.php?t=16423](url)
Maybe get in touch with him?
There are all sorts of suggestions, chiefly the choice of USB port,
 which did solve funkmuscle's issue, according to him.

**Comment by spamatica** [comment]
Sadly I'm 100% certain it has nothing to do with the sound card. I have reproduced it on several computers with different hardware. All running Kubuntu but I would be very surprised if it had to do with the operating system.
I can reproduce it without latency correction too.

@kybos would you mind checking if you can reproduce this issue?
1. add a sound file to a wave track.
2. add a left and right marker with a few seconds in between
3. perform a Audio->Bounce to File, default settings just put in a file name.
4. listen to the resulting audio file. Does it sound good or is there noise in it?

**Comment by spamatica** [comment]
Tried downgrading ti git tag muse_3_1_0_pre3 and the output is correct, without any noise.
I'll go deeper and try to narrow it down where it happened

**Comment by kybos** [comment]
I tried too, but I can hear no crackling. No special sound hardware though, only an internal sound chip.
I have an Edirol USB interface on another PC, but no current MusE there, would require some setup to test.

**Comment by terminator356** [comment]
@spamatica Wow. Bummer. Sorry for this hassle, man. Hope we can sort this out.

Question: Was all the audio hardware USB? Or were some internal cards or chips?
Question: Can I assume that none of the audio converter stuff kicked in,
 ie. project sample rate is the same as system sample rate so no sample rate converters
 of any kind are on, and you're not using stretching and so on?

Weird. Only thing I can think of is maybe there's a problem with our wave pre-fetch thread?
I mean, the only thing we do is pull data from it via the bounce's Audio Output track
 (and all routes connected to it), then write to the external bounce file. Pretty straightforward.

**Comment by spamatica** [comment]
that is very odd, as Tim suspected earlier, it might be something with libsndfile.
I would be very surprised if the sound hardware has anything to do with it as I have tried it on three or four different configurations..
Only one of them was usb-sound, the others were internal standard intel audio.
I'll try without audio (-a), hang on.

**Comment by terminator356** [comment]
1... 2... 3... Ehm, you might observe a few random crashes with dummy audio.
I have been observing frequent dead crashes in the dummy thread loop.
Keeping my eye on it. Strange since the dummy loop is realtime priority...

**Comment by spamatica** [comment]
[dmix_master_noaudio_no_resampling.zip](https://github.com/muse-sequencer/muse/files/4200828/dmix_master_noaudio_no_resampling.zip)

The noise is still there so the problem is definitely in software. (might need to normalize the file to hear more clearly)
The original audio is 44100 and MusE is set to 44100 512 frames but -a so no soundcard is connected. I see no evidence that any resampling has occured.

Re: Crashing - wierd, can't recall having seen that. No crashing now either. (not that I run dummy audio that often)

**Comment by terminator356** [comment]
Tip: It is best to test these things with a long, pure sine wave.
Grab a long test file from the net. Use it and look for spikes.
Post if you like, I'll take a look.

**Comment by spamatica** [comment]
Going backwards in the git history it is as I sorta suspected, the big commit that introduces the noise
https://github.com/muse-sequencer/muse/commit/39f55d1185426c0e97ba00236e5078f38c7e79e8

Realized I always installed librubberband so I tried now without but didn't seem to help.
If that is infact used. Is there a way to completely disable the resampling feature?
libsamplerate is always installed so maybe it is active?

There's a lot of code in that commit so it will take a while to go through. Think I'll try to go backwards in the original branch, but another day..

**Comment by terminator356** [comment]
Oh crap. Stop the presses! I have confirmed it here - even with a single CPU core !
Here is your file:
![bounce rj with spikes 1](https://user-images.githubusercontent.com/5422362/74481845-69bd9000-4e81-11ea-82b2-268d56991f03.png)
Here is mine:
![bounce mine with spikes all cores 1](https://user-images.githubusercontent.com/5422362/74481864-7346f800-4e81-11ea-8b9a-4a65a7ff36c8.png)

Mine gives identical results no matter one core or all.
I even offset the wave to start at a different phase and the dropouts
 occurred at the exact same locations.
Notice that the dropouts/spikes are apparently evenly spaced !
This seems to suggest something really stupid, like we forgot to copy
 the very last sample in a block !

**Comment by terminator356** [comment]
Don't worry about rubberband.
It and the other converters are not even engaged at this point.
No, this seems something purely with wave gathering/copying/writing.

**Comment by terminator356** [comment]
I bounced at dummy period size = 32 and whoa! Ugly!
Every 32 samples there is a huge spike all the way to the top.
Without a doubt, this is periodic in nature. This ain't crackling, it's periodic spikes.

Some ugly test results: Bounced a net-generated **mono** 440Hz wave file
 to a stereo file and a mono file:
Here are the original (top), the stereo bounce, and the mono bounce:

The blue highlighted sections are the very first data pair (16-bits) in the data.
It is 0x00 0x00 in the original.
* Ugly 1: Notice that the stereo bounce's first data pair (one data pair of two channels)
 is not the one in the original. We have **skipped** a sample! This raises eyebrows.
When both waves are compared in MusE's very handy transparent wave viewer,
 the **entire** bounce file is seen to be shifted to the **left** by one sample.
Possibly this is occurring for each block of MusE period data, thus giving the spikes.
Notice how in the wave pictures the spike is random garbage data, **not** just missing data.
That's a big clue. It suggest each block of MusE period data is shifted to the left,
 missing one sample, and the very last sample in each block is **not** filled, leaving garbage.

* Ugly 2: Notice in the mono bounce of this mono file, the data is shifted left by one
 just like the stereo bounce, but even worse, the data is multiplied by two!
The resulting bounce file is twice the amplitude and severely clipped.
This is unrelated to the current problem and possibly has been there for years...
Or maybe I broke it, again...    What we doin' wrong there... we'll see.
![bounce comparison 1](https://user-images.githubusercontent.com/5422362/74490490-acd62e00-4e96-11ea-8987-7a3a8c12a45e.png)

**Comment by terminator356** [comment]
Me thinks this may turn out to be an accidental  mixup of our use of postscript and prescript
 increment operators within the several **sample block copying routines** we use.
As in   *dst = *(++src)   vs.   *dst = *(src++).
It could not be a loop copy where we check in the loop line for end
 because the worst that could happen is that someone put:
   for(i = 0; i <= size; ++i)   instead of   < size
 which would either crash or make 'fuller' sounding data, I think...

**Comment by terminator356** [comment]
And the dubious distinction of the idiot that caused this is... Me.
- Oops! Fix bug 765: Crackling in recorded files. Caused by 01.01.2020 commit.
Changed SndFile::write(): wrFrames = realWrite(srcChannels, src, n, liveWaveUpdate);
 to wrFrames = realWrite(srcChannels, src, n, wrFrames, liveWaveUpdate);

It looks like this may have affected more than just bouncing 'cause that's
 the place where wave file are truly, finally written.

And... The weird mono track to 2x amplitude mono bounce thing (above)?
That was simply because the Audio Output track was in stereo,
 and the bounce mixed the two channels together! (Hm, maybe should we halve it?)
Phht. I don't even remember our own software (ol' brain starts to go after 10 years...)

@Robert I owe you a beer (a case).
Thanks for catching this. I need to record more often.

**Comment by spamatica** [comment]
> @robert <https://github.com/robert> I owe you a beer (a case).
> Thanks for catching this. I need to record more often.
>

Yay, great, will test.
And sad it is such a long way over the pond... hard to share a beer.

And you should absolutely record more often. I hope that time is starting
to arrive when you can prioritize it over coding, MusE will always have
bugs but it's actually very usable =)

**Comment by spamatica** [comment]
Ah, forgot to write I tested this successfully
