### ISSUE TITLE
Compile fails due to undefined references

### ISSUE THREAD

**Issue by schnitzeltony** [muse-sequencer/muse#772]
Have this for a while but did not find the time to write here. Now with 3.1 released I tried building but same so I kindly ask for support

Configure log is:
[log.do_configure.txt](https://github.com/muse-sequencer/muse/files/4246529/log.do_configure.txt)

Compile log is:
[log.do_compile.txt](https://github.com/muse-sequencer/muse/files/4246540/log.do_compile.txt)

If I read compile log correctly, linker has problems to find symbols:

> ld: muse/driver/libmuse_driver.so: undefined reference to `MusECore::MidiDevice::latencyCompWriteOffsetMidi(bool) const'
> ld: muse/libmuse_lv2host_module.so: undefined reference to `MusECore::SynthIF::fileName() const'
> ld: muse/driver/libmuse_driver.so: undefined reference to `MusECore::MidiDevice::canDominateOutputLatencyMidi(bool) const'
> ld: muse/driver/libmuse_driver.so: undefined reference to `MusECore::MidiDevice::canDominateEndPointLatencyMidi(bool) const'
> ld: muse/libmuse_lv2host_module.so: undefined reference to `MusECore::SynthIF::pluginID()'
> ld: muse/libmuse_lv2host_module.so: undefined reference to `MusECore::SynthIF::lib() const'
> ld: muse/libmuse_lv2host_module.so: undefined reference to `MusECore::SynthIF::readConfiguration(MusECore::Xml&, bool)'
> ld: muse/libmuse_lv2host_module.so: undefined reference to `MusECore::SynthIF::setOn(bool)'
> ld: muse/libmuse_lv2host_module.so: undefined reference to `MusECore::SynthIF::requiredFeatures() const'
> ld: muse/libmuse_lv2host_module.so: undefined reference to `MusECore::SynthIF::titlePrefix() const'
> ld: muse/libmuse_lv2host_module.so: undefined reference to `MusECore::SynthIF::pluginLabel() const'
> ld: muse/libmuse_lv2host_module.so: undefined reference to `MusECore::SynthIF::dirPath() const'
> ld: muse/libmuse_lv2host_module.so: undefined reference to `MusECore::SynthIF::writeConfiguration(int, MusECore::Xml&)'
> ld: muse/libmuse_lv2host_module.so: undefined reference to `MusECore::SynthIF::track()'
> ld: muse/driver/libmuse_driver.so: undefined reference to `MusECore::MidiDevice::canPassThruLatencyMidi(bool) const'
> ld: muse/driver/libmuse_driver.so: undefined reference to `MusECore::MidiDevice::canDominateInputLatencyMidi(bool) const'
> ld: muse/libmuse_lv2host_module.so: undefined reference to `MusECore::SynthIF::hasBypass() const'
> ld: muse/libmuse_lv2host_module.so: undefined reference to `MusECore::SynthIF::on() const'
> ld: muse/libmuse_lv2host_module.so: undefined reference to `MusECore::SynthIF::name() const'
> ld: muse/libmuse_lv2host_module.so: undefined reference to `MusECore::SynthIF::uri() const'
> 

Would be thankful for suggestions...

**Comment by terminator356** [comment]
Hello. Sorry for the trouble.
See [https://github.com/muse-sequencer/muse/issues/659](url)
 for others having similar problems.

The quick solution for the moment may be to adjust the number 
of parallel build threads with -jN, where N is typically 4, but others have reported
 that adjusting it to say N=2 or N=1 solves this.
Meanwhile I will look into this... We seem to be missing dependencies...

**Comment by schnitzeltony** [comment]
> See https://github.com/muse-sequencer/muse/issues/659
> for others having similar problems.
> 
With one task compile still fails with same error - it just takes longer :grin:

Have looked into a bit. Think it is not easy to fix because if you add 'core' to 'driver''s target_link_libraries (that one failed), a cyclic dependency is created.

Don't know the code so my suggestion might be stupid: Is it possible to split out the code 'driver' requires from 'core' into another base library and link 'core' and 'driver' against it?

**Comment by terminator356** [comment]
Looking at your logs, something is wrong here. At line 1 and every line we have:
`cmake --build /home/superandy/tmp/oe-core-glibc/work/cortexa7t2hf-neon-vfpv4-mortsgna-linux-gnueabi/muse/3.1.0-r0/build`

By chance did you download a release from our releases page called 'muse-3.1.tar.gz' ?
**Don't use that one**. Robert put that there I think to try and solve some problems.
I'm not sure what's going on there. But that file is **wrong**.
Use the one called 'Source code (zip)' or 'Source code (tar.gz)' 

But **if you did** use either of those two correct files, your configuration is wrong.
Your build folder should be under the '**muse3**' folder.
So the your building lines should look something like this:
`cmake --build /home/superandy/tmp/oe-core-glibc/work/cortexa7t2hf-neon-vfpv4-mortsgna-linux-gnueabi/muse/3.1.0-r0/muse3/build`
Or 
`cmake --build /home/superandy/tmp/oe-core-glibc/work/cortexa7t2hf-neon-vfpv4-mortsgna-linux-gnueabi/muse-muse_3_1_0/muse3/build`

Also one more clue that something is wrong: In your config log you have this:
`** WARNING: Native VST was enabled, but development files were not found.`
That's a big clue that the build setup is not correct.
Because it should have found 'aeffectx.h' under our 'vestige' folder.
Did you by chance purposely alter the user-adjustable path to the 'aeffectx.h' file?
If not, then yes, this whole build is not correct and messed up.
Try the correct release files then...

HTH
Tim.

**Comment by spamatica** [comment]
By chance did you download a release from our releases page called
'muse-3.1.tar.gz' ?

> *Don't use that one*. Robert put that there I think to try and solve some
> problems.
> I'm not sure what's going on there. But that file is *wrong*.
> Use the one called 'Source code (zip)' or 'Source code (tar.gz)'
>
There is some miscommunication here or there is a problem I don't know
about.
The muse-3.1.tar.gz should be the correct file, tried it now and it works
for me, even with -j5.

What distro are you on, looks ARM based?

**Comment by schnitzeltony** [comment]
Am at the office - so just short answer: I build from git (was the guy that asked at announcement @ linuxmusicians) - and I build with Yocto/Openembedded for RaspberryPi 4.

**Comment by schnitzeltony** [comment]
Ahh and don't worry about muse3 folder: I start build from within muse3 folder. That's where topmost CMakeLists.txt is.

**Comment by spamatica** [comment]
Den tis 25 feb. 2020 kl 10:56 skrev Andreas Müller <notifications@github.com
>:

> Am at the office - so just short answer: I build from git (was the guy
> that asked at announcement @ linuxmusicians) - and I build with
> Yocto/Openembedded for RaspberryPi 4.
>

I see, is there an vm image for such a thing that we could try to build in
the same environment?

**Comment by terminator356** [comment]
> Ahh and don't worry about muse3 folder: I start build from within muse3 folder. That's where topmost CMakeLists.txt is.

No, that is incorrect.
You must create the build folder below muse3 folder and build **from that folder**.
Please see the README file for proper build instructions.

**Comment by spamatica** [comment]
We changed some things with the release process this time, formostly moving to github for hosting, and this has led to some confusion as to what files were actually the releases and add some general confusion to that.. 
In short, we discussed this a bit elsewhere and the placement of the build folder is unlikely to be the problem.
I tried to follow one of the undefined references in the compile history but I can't spot why it can't be found. The paths aren't exactly the same as when I build on my system but I'm guessing that is due to placing the build folder on different places.
As this is with a tool chain that we generally do not build with (and I'm not really sure how to go about doing it either), my primary suspect would be that there is some difference in how the ARM toolchain searches libraries for symbols.

The final link command in the log, on line 3238, starting with :
/home/superandy/tmp/oe-core-glibc/work/cortexa7t2hf-neon-vfpv4-mortsgna-linux-gnueabi/muse/3.1.0-r0/recipe-sysroot-native/usr/bin/arm-mortsgna-linux-gnueabi/arm-mortsgna-linux-gnueabi-g++
You could copy that whole thing and run it in a terminal and see if, for instance, moving the  libmuse_driver argument earlier or later makes any difference.
I will stare at it some more, but is literally a wall of text..

**Comment by schnitzeltony** [comment]
I've set the build path as written, played around with build / source path - no success.

So I followed suggestion for packager's added:

-DMODULES_BUILD_STATIC=1 \
-DCMAKE_SHARED_LINKER_FLAGS=-Wl,--no-undefined \

and that did the trick!

I am happy to have Muse back in my image. Thanks everybody for taking your time (and doing this strong piece of software)!

**Comment by spamatica** [comment]
That's awesome. 
This solution was lingering somewhere in the back of my head, anyway I couldn't remember how it was done. Had done a test at porting to windows one time and this exact fix was needed there.

I actually got an raspberrypi image up and running in Qemu and have gotten to the point where I can compile MusE! It's just started and looks like it will take forever. Gonna leave it running though, see what happens.
I already see it's reporting some warnings that seem new for arm.
