### ISSUE TITLE
Punch problem bis

### ISSUE THREAD

**Issue by moebius1** [muse-sequencer/muse#789]
Bonjour,
Well I must confess it's a duplicated issue of one I've posted in may 2019.
But, since this time, I've searched everywhere but I still don't know how to punch correctly both audio and midi. And it's very very annoying for my use.
Well, when I was working with cubase and atari falcon, punch worked like that, 
    1 setting left and right locator according to the place where you want to replace the record by another one then clicking on "punch in" and "punch out"
    2  setting the transport locator a little bit before left locator
    3 beginning recording.
   4 when transport locator reached the left locator, the previous record was not heard and replaced by the new one ; when reaching right locator recording stopped and turned to listen mode until you stop.
    Problem in Muse :
    Even I select "replace" for "record mode" in the transport window the previous record is heard and not deleted ; only a new part is created between the left and right locators and the initial part is left unchanged. The result is two parts on same track.
    Well I don't know what to do to obtain a real punch action ; I surely miss something but don't know what it is...I really need some help ! :-)
    cordialement,

**Comment by terminator356** [comment]
Hello, sorry for the late reply.
I have known for about ten years that the punch was not fully correct.
It used to be worse. Then we fixed it so that it was mostly working. Sort of.
But as you can see, the punch has problems.

I am now reviewing punch operation, identifying problems, and looking at possible solutions.
I cannot promise anything soon, but I will at least see how we might fix it and move forward.
It will not be a trivial fix.

Your question:
> what is the meaning of this icon in the transport window, a red triangle with something like a jack plug in the middle ?

That is the 'Use Jack Transport' button.
[https://jackaudio.org/api/transport-design.html](url)
When the button is on MusE will use Jack Transport.
When the button is off, MusE will not use Jack Transport, instead using a built-in transport.

**Comment by moebius1** [comment]
Bonjour,
Nice news ! I began to think that noone would be interested by fixing this problem. Even if you cannot promise anything soon, I keep confident, Muse is a great job and, except available time you can get to do that, you surely can do something ; and that is not just flattery :-)
Thank you again to look into this punch feature.

cordialement,

PS : for the icon thank for your answer ; I've already understood this function because in the new versions of Muse it has been more evident...

**Comment by moebius1** [comment]
I've closed the issue by error !!

**Comment by kybos** [comment]
The midi part should be fixed now in master, please check.
Leaving this open as the audio part is still to be done.
