### ISSUE TITLE
Latency compensation

### ISSUE THREAD

**Issue by lpgasparotto** [muse-sequencer/muse#792]
Hi, 
I'd like to know if Muse is capable of doing latency compensation when recording audio tracks using previously recorded tracks as a reference. I had no luck trying to do it
![MuseTracks](https://user-images.githubusercontent.com/22053235/77932113-78ba9f00-7283-11ea-8282-5db40566ff9f.png)
I did this for testing purposes, I imported a click track and recorded a new track using a loopback cable, and despite setting the amount of frames to compensate in Jack -I and -O parameters the latency is easily noticeable. 
Is there something I'm doing wrong? I used jack_iodelay for getting the values for -I and -O.
Thank you very much in advance and best regards,
Luis Pablo Gasparotto

**Comment by terminator356** [comment]
Hello. See the Global Settings dialog, Latency tab, in recent MusE releases.
Click the 'Enable latency correction/compensation' button.
We disable the setting by default because there a couple of bugs to work out still.

When this is enabled, MusE should be able to compensate for your situation.
The latency correction/compensation feature is very comprehensive and sweeping,
 and many unusual scenarios were tested.
(Your screen shot resembles my many tests during development !)

You were quite correct to set up the Jack IO delay using jack_iodelay.
That is the last bit of small hardware latency MusE does **not** correct for - yet.
I am planning to build jack_iodelay into MusE and provide entry boxes for
 where users can enter extra values if required.
But for now, use of Jack -I and -O are required, to cure that last small bit of latency.
Meanwhile, MusE will take care of all the other latency - Jack buffers, plugins etc.
It will attempt to **correct** latency where possible (for ex. wave files). Otherwise
 it will **compensate** so that signals are at least aligned properly - but with some delay.

Caveats: Here are the couple of bugs to work out:
1) You may notice a few milliseconds of missing audio or midi notes
 at the start of playback or record.
The advice to workaround this for now is to 'back up' the play head cursor by
 a few beats (to the left) before hitting 'play' to ensure MusE plays those first few milliseconds.
Avoid writing parts all the way to the left at bar zero - leave say, one blank 'setup bar'
 and start playback from just before the second bar, to allow MusE to
 play those first few moments.
(The real solution is likely going to involve playing a few milliseconds just before
 we allow the transport to actually start rolling, using Jack's slow-sync feature).
2) Currently when using looping with audio tracks, the latency correction causes
 errors in the processing. Avoid using looping with audio tracks for now :-(

**Comment by lpgasparotto** [comment]
Thank you very much for your reply! I realized I was using an old version of MusE (3.0) so I downloaded and compiled the latest stable version and worked like a charm, latency is perfectly compensated. 
Best regards!

**Comment by terminator356** [comment]
You're very welcome. Ask if any more questions, I know it's a complex topic.

Some of the other check boxes in the Latency tab may or may not be fully working properly.
I know for sure the 'Monitoring affects latency' button works.
And the 'Unterminated branches' buttons _should_ work.
The 'Project latency' button I don't think works correctly at the moment.

**Comment by lpgasparotto** [comment]
Thank you very much again. I don't really know if this is related to the original post, if it doesn't please let me know and I'll open a different thread, I'm trying to sincronize MuSE and Hydrogen setting MuSE as master and Hydrogen as slave and Hydrogen is slighlty behind the audio track I imported to MuSE. I was able to confirm that exporting the Hydrogen song as wave file, importing that wave file and then playing Hydrogen and MuSE together, in this case the delay was even more noticeable, kinda "flam" all the time. I did the same experiment with Ardour and QTractor, it worked nicely on Ardour but with the same delay on QTractor, Is there something I could do to solve it? Or it's something to live with?
