### ISSUE TITLE
Feedback noise on audio channel

### ISSUE THREAD

**Issue by StaffanMelin** [muse-sequencer/muse#802]
When muting and unmuting audio channels I sometimes get a powerful feedback noise.

I think I have finally found a testing scenario that reproduces the error every time.

open project
unmute vocals and play two bars
press stop (playhead rewinds)
mute vocals
play
FEEDBACK - see VU-meter go up!

The file/song is 37MB so I can't attach it. Is there somewhere I can sent it using a service such a sprend?

**Comment by terminator356** [comment]
Hello, quick question:
Are you using the latest release?
If so, is the new latency correction feature (Global Settings - Latency tab) turned on or off?

**Comment by StaffanMelin** [comment]
Hello!

Global Settings > Latency tab > Enable latency correction/compensation is not checked.

MusE version 3.1.0.

**Comment by StaffanMelin** [comment]
Testing project sent to spamatica.

**Comment by terminator356** [comment]
Hi, sorry for the delay.
I briefly tried to recreate this but no luck.
You may post the song file (*.med), without the wave files, 
 so that I may look at the situation to see if I spot anything wrong...

**Comment by StaffanMelin** [comment]
[dreamplane01.med.zip](https://github.com/muse-sequencer/muse/files/4640774/dreamplane01.med.zip)

Here is the project! Thanks for looking into it! I have a hunch that the error does not appear with projects created with 3.1, this was and "old" 3.0 project that I picked up again. But I'm not sure...

**Comment by terminator356** [comment]
Eek! Verified! Thanks very much for the test file.
It's a looping problem. I removed all the plugins, same problem.
But if you manually relocate the transport while playing, it seems to have no problem.
I could swear I tested before, and even looping without latency correction enabled was working.
I probably broke something recently.

Looping is... well, kind of a tough thing technically, because the audio works in blocks
 which makes it hard to jump to/from specific frames each loop to give the same
 loop size being played each time. The Jack team likes to say it cannot be done (at all?).
And that's true. Synchronizing other clients in a loop scheme is pretty much impossible.
In one of my un-merged branches, I have fixed it so that from MusE's point of view,
 the loop size is 'correct' and that the stream of playing audio always sounds correctly
 as a continuous stream without interruption - even when looping. Things will 'just work'.
But working with other 'standard' Jack clients in this loop scheme? Forget it.
They will have to incur an artificial 'gap' to loop the same width as MusE.

You see, the scheme 'fools' the transport into thinking it is a continuous stream.
That's why other 'standard' Jack clients can't work with it.

However, theoretically other clients can use the same scheme and code as MusE,
 and they would be able to keep in sync. For example another instance of MusE
 should be able to keep in sync with the this instance, no gaps.
I think that was the conclusion I reached.
I'll see when I finally get around to revisiting the whole looping + latency issue.
I'm already working in the midi looping now.
But the loop + latency thing is another issue altogether requiring altering the design
 of the audio cache system. That's evolving in my other branch.

**Comment by StaffanMelin** [comment]
Thank you! I understand some of the technical side of this problem (but not all :) ).

**Comment by spamatica** [comment]
Here's the whole thing.. sorry for the delay.
http://spamatica.com/bug802/dreamplane_bug.zip
I haven't tried it but I know that I have experienced similar things with reverbs going absolutely crazy when unmuting. (to the point that I hesitate to unmute without removing my headphones)
If I were to venture a guess there is either random data or very big values sometimes injected when muting or unmuting.

**Comment by terminator356** [comment]
Hey ho!
    - Audio: Fixed bad feedback / pinned meters with muted tracks in play mode.
      Was problem near end of WaveTrack::getData(), what constitutes "have data" or not.
      Said "have data" when there was none when muted, causing AudioTrack::copyData()
       to build up feedback data in the buffers instead of clearing them.

Try it out. Lemme know if any more audio feedback trouble.
Serious things like this get **top priority** by me.
We want our audio and midi engines to run clean, before all the other wonderful stuff.

Thanks to user lpgasparotto for inadvertently providing reproduceable test files
 for a different issue, they helped recreate this problem.
And Robert was right, it was happening even without looping.

**Comment by StaffanMelin** [comment]
DLed, compiled and tested! Noise gone!

I tested my own reproducible test file and also some other projects. Feels great to be able to mute/unmute + solo/unsolo without worrying.

Thanks a lot Tim! Great work!
