### ISSUE TITLE
Looping over audio file only works with Jack Transport On

### ISSUE THREAD

**Issue by StaffanMelin** [muse-sequencer/muse#806]
See discussion on linuxmusicians: https://linuxmusicians.com/viewtopic.php?f=61&t=21398

**Comment by PlatinumLucario** [comment]
I can confirm looping over audio file data will only work when Jack Transport is switched On (which is by default, if jackd2 has been installed. Otherwise if jackd2 is not installed, Jack Transport button will be disabled (aka greyed out), and the audio data won't loop over.

I can confirm this bug is still present as of revision b0a549d (4.0). In the past, the end user was required to install jackd2 before it MusE could be used. But nowadays, there's an experimental attempt at supporting other audio drivers (such as ALSA Pulse Audio) natively, without requiring jackd2, but it shows there's still bugs that need to be fixed.

**Comment by kybos** [comment]
This is now fixed in master:
https://github.com/muse-sequencer/muse/commit/5b4abe1bc7a822eb1184e27e98a56f8ba25d374c

**Comment by StaffanMelin** [comment]
Great, thanks a lot @kybos!

**Comment by kybos** [comment]
It was Tim, not me in this case ;-).

**Comment by StaffanMelin** [comment]
Ah, then thank you @terminator356 ! :)
