### ISSUE TITLE
Mixer maximized problem

### ISSUE THREAD

**Issue by kybos** [muse-sequencer/muse#815]
I suppose this is desktop specific (Cinnamon), but when I maximize the mixer (there are 3 tracks), then it looks like that (current master):

![image](https://user-images.githubusercontent.com/10009541/83347227-e2a70180-a323-11ea-9992-0165ced30552.png)

The first 3 strips are not adjusted vertically, and then all 3 are duplicated and made wider to fit the screen.

Not sure how exactly it is supposed to behave correctly? Should it be possible to maximize the mixer at all?

**Comment by spamatica** [comment]
It doesn't go this bad for me but it does misbehave also in kde/kwin. The
width of the mixer is kept but the length of the strips is not always right.
Since we impose restrictions on this window it might always behave
strange... maybe we should simply remove the maximise button?

Den sön 31 maj 2020 kl 09:49 skrev kybos <notifications@github.com>:

**Comment by terminator356** [comment]
We allow maximize up to the maximum width of all the strips and the maximum
 screen height. It uses some custom code for that. Clearly that strategy is being defeated here.
I can't recreate the problem here but I've noticed a few odd things happening lately as well.

From initial examination, it seems that if we are going to be forced to accept a full width,
 if the system is not going to accept our restrictions, then perhaps a horizontal spacer
 should be added at the end of the strips, because the full width **appears** to be
 forcing the strips at the end to expand - very odd, I don't think they should even be doing that.

**Comment by terminator356** [comment]
Hm, I wonder if it's your HiDpi screen - something in our mixer code needs to be scaled?
Can you try with different (standard) screen sizes?

**Comment by kybos** [comment]
I will do more testing later, but it does not seem to be HiDPI. I tried it in KDE VM (also HiDPI), and there it's working as you describe.

I noticed another issue on my system: If the mixer is maximized and then un-maximized again, it does not return to the previous size, it gets very small, like that:
![image](https://user-images.githubusercontent.com/10009541/83360679-5b897600-a383-11ea-98b3-eebd7ec6a748.png)

**Comment by kybos** [comment]
I could reproduce the second issue (window too small after un-maximizing") also on KDE.

**Comment by kybos** [comment]
> We allow maximize up to the maximum width of all the strips and the maximum
> screen height. It uses some custom code for that.

Where is this custom code? I can't find anything special (looked in app.cpp and amixer.cpp...).

**Comment by terminator356** [comment]
I meant places like ScrollArea::viewportEvent() which emits layoutRequest()
 which the AudioMixerApp ctor connects with
 connect(view, SIGNAL(layoutRequest()), SLOT(setSizing()))
 where setSizing() calls resize() to enforce the mixer size.

Maybe something funky going on there in setSizing() when you resize, if you step through?

**Comment by kybos** [comment]
setSizing() does the right thing, but cfg->geometry.size() has already been set to full screen before in resizeEvent:

```
  // Hack flag to prevent overwriting the config geometry when resizing.
  // Do NOT overwrite if we set the flag before calling.
  if(!_resizeFlag)
    cfg->geometry.setSize(e->size());
```

_resizeFlag is still false when this method is called for the first time (after pressing the Maximize button).

I tried to fix the max width in setSizing(), so the width passed to resize() is never bigger than the real mixer width:

```
      if (cfg->geometry.size().width() > w)
          cfg->geometry.setWidth(w);
```

But even then the mixer is set to fullscreen! So it seems once you press Maximize, it's passed to the window manager as such and overrides everything else.

So I guess we must either remove the maximize button, or ensure the strips are left-aligned in the fullscreen. In any case we should remove the _resizeFlag hack from the code, as it apparently causes other unwanted side-effects.

**Comment by terminator356** [comment]
Actually that hack was carefully added because of problems overwriting the
 configured sizes ;-) It solved the issues I was having. Removing it might cause big trouble.

I feel that surely there must be a way to make it work without removing the maximize button.
I got a new 500G drive. It's just begging for more partitions.
Can you tell me again what distro you have, and what flavour of desktop/wm you chose?
I'll try to make time to install. Thanks.

**Comment by spamatica** [comment]
>
> I feel that surely there must be a way to make it work without removing
> the maximize button.
> I got a new 500G drive. It's just begging for more partitions.
> Can you tell me again what distro you have, and what flavour of desktop/wm
> you chose?
> I'll try to make time to install. Thanks.
>
Haha, I heard there are two types of harddrives, new ones and full ones.
Seems you are at the first point and going for the second fast ;)

Now, I'm not arguing that hard but removing the maximize button is that
really a big deal? The mixer gets a bit unwieldy when fully maximized,
those overly long strips...
... maybe the older I get, I get more interested in limiting scope..

**Comment by kybos** [comment]
> Can you tell me again what distro you have, and what flavour of desktop/wm you chose?
> I'll try to make time to install. Thanks.

Sure.
I use Linux Mint 19.3 in the Cinnamon version.
Cinnamon is a Gnome derivative so with some luck a fix for it could solve the problem for other Gnome based desktops too (Ubuntu etc.). But there are others like xfce, which is also quite popular, and not Gnome based. These kind of low-level hacks can behave very differently on these, as we have seen, so I'm still a little sceptical ;-)...

**Comment by kybos** [comment]
> Now, I'm not arguing that hard but removing the maximize button is that really a big deal? The mixer gets a bit unwieldy when fully maximized, those overly long strips...

I fully agree. It seems obvious that it is not widely used anyway (if at all), since it's broken except for KDE and apparently nobody ever complained.

**Comment by terminator356** [comment]
Ha. Yeah my SSD was full, I could not go any further until a new drive.
So many distros on drives around here...

Full disclosure: I have this idea I've been meaning to implement, it relates
 to the thread on aligning the meter and slider, if I get time I'd like to try it:
Allow the user to choose a compact volume slider/knob slider and meter.
The volume and meter would become very short and compact like the other strip items.
It'd be a great way to compact the strip if desired.
