### ISSUE TITLE
[Feature Request] Grid configuration in wave editor

### ISSUE THREAD

**Issue by Gnlfz007** [muse-sequencer/muse#825]
The wave editor should allow the configuration of the editor grid like the piano roll editor does. Proper placement of selections is not possible without a finer grid. Also see [this](https://linuxmusicians.com/viewtopic.php?f=61&t=21648) entry in the Linuxmusicians forum.

As a workaround, the time signature can be changed temporarily (e.g. from 4/4 to 16/16), but this requires error-prone cleanup afterwards (mastertrack!).

**Comment by kybos** [comment]
@spamatica 
I unterstand you use MusE mainly for audio recording, it's quite surprising you never missed this what seems to be quite a basic function? Or is there another workaround?

**Comment by spamatica** [comment]
Den tis 23 juni 2020 kl 09:12 skrev kybos <notifications@github.com>:

> @spamatica <https://github.com/spamatica>
> I unterstand you use MusE mainly for audio recording, it's quite
> surprising you never missed this what seems to be quite a basic function?
> Or is there another workaround?
>

Haha, yeah... maybe it is surprising... I use MusE for everything, all the
way from song creation to mastering, usually with quite a lot of audio.

The wave editor is very basic, I guess I have grown used to it so it never
bothered me enough to do anything about it. I do use the wave editor, for
things like broad volume adjustments or fade in/outs. Anything more than
that I either make non-destructive changes in the arranger or I use another
wave editor..

**Comment by terminator356** [comment]
The question is about missing snap box in the wave editor?
Long story short: Yes, add 'snap to BBT' exactly like the midi editors.

Long story, if I may add some perspective:
Traditionally, wave stuff in MusE has been all about frames - linear time.
Traditionally, midi stuff in MusE is all about Bars, Beats, and Ticks (BBT) - musical time.
All the wave stuff is timed in frames, the basic unit of linear time position and length of wave events and parts.
All the midi stuff is timed in ticks, the basic unit of musical time of position and length of midi events and parts.
The actual corresponding real linear time value of a BBT depends on tempo.

Traditionally we have kept the two realms rather separate.
However, you can see in the Wave Editor we are displaying frame-based events on a musical time scale.

I have a branch, infrastruct_2_poc, where whole sweeping changes would happen.
For the interesting details, please see:
[https://github.com/muse-sequencer/muse/blob/infrastruct_2_poc/muse2/ABOUT_THIS_BRANCH](url)

My intention was to make MusE a full editor in **both** realms.
The time scales - in **both** the midi editors and wave editors - could be switched from BBT to frames.
In frames time scale mode, tempo has no effect.
Why would someone want that? Consider a TV or radio station editing material for a broadcast.
Things in that business operate strictly on linear time, not tempo-dependent BBTs.

One of the problems that came up was this: (Think back Robert, we had this discussion once, I can't find it)
If there is to be 'snap' box in these dual-mode editors, what shall be the snap values in frames mode?
It's weird, I proposed something like power-of-2 frames lengths like 2, 4, 8, 16, 32, 64, 128 frames etc.
There is nothing else to 'snap' to, really.

Anyway... the branch is long dead, sidetracked, unlikely to see the light of day now. Sad, actually.
In the meantime, my view on frame-based editing support has changed.
MusE is a **musical** application, for making music. So in the interest of sticking to that philosophy,
 in the interest of simplicity, we'll stick with BBT time scales for now.

Now here's where things get interesting: You all know that in MusE when you adjust tempo, your waves
 go slipping all over the place because their corresponding linear time frame positions and lengths change.

But recently, I have added time-stretching support.
This opens the door for wave events and parts to finally be changed to BBT-based position and length.
Thus, adjusting tempo would not affect the waves' positions and lengths.
The time-stretchers would kick in and do the magic required to make it align with all the midi stuff's BBTs.

So end of story: Yes, we can and should add a BBT-based snap to the Wave Editor.
It means slightly more work (automatic frames <-> BBT conversion actually) to snap
 when moving wave things around.

**Comment by Gnlfz007** [comment]
That's a lot of text...

From my point of view, just a finer optical grid is missing here, even if it is hard-coded to 16th. Note-on is auto-humanized in a real take anyway; no need to have perfect placement. No snap is necessary. Special handling of time-stretched audio data can also be ignored - too much fuss for the built-in wave editor, I suppose. 

Partly off-topic: In general I'd like to have a separate definition of snap and grid in the MIDI editor, like I had with Cubase 2.x on Atari-ST1024 ~30 years ago ;-) But this is not a feature request because I suppose that there are more important things on the list and I'm not paying a cent.

**Comment by kybos** [comment]
@terminator356 

Tim, if I understand correctly, you added the snap box also to the wave editor with your recent changes. In the midi editors the snap is bound to the grid display (or vice versa), but in the wave editor the grid seems to be fixed. It there a technical reason for it or is it still a todo?

**Comment by terminator356** [comment]
Wave Editor snapping is bound to the new snap box.
Snap should obey the box now.
But as I noted elsewhere, Wave Editor finer grid line painting has a bit of trouble, not drawn correctly.
But the major darker lines should be OK.
