### ISSUE TITLE
MIDI recording: Previous recording played in "replace" mode

### ISSUE THREAD

**Issue by Gnlfz007** [muse-sequencer/muse#836]
Scenario:
- MusE 3.1master, (git: master - 48451f3d - 2020-06-27 16:19:34 -0400)
- Create MIDI track and connect in and out to ALSA device; external stage piano connected.
- Record a bar or two, playing some notes
- Switch record mode to "Replace"
- Record the same track and part again, playing some different notes

Expected: Only the new recording is audible.

Observed: The first / overwritten recording is played (sent via MIDI) while recording and hearing the new notes. After recording, only the new notes are present (correct).

Workaround: Mute existing part while re-recording or remove part an record a new one.

This overlaps partly with #649 and #789, but these are related to punch in / punch out.

**Comment by terminator356** [comment]
I am working hard on a fix at the moment. Been promising something soon but had delays.
Now I am back on it. It's tricky, there are three areas: The graphics drawing of the looping notes,
 the playback of the looping notes, and finally the processing of the notes when recording stops.

There is a bonus waiting in all of this: It should no longer be required to choose a custom instrument
 in order to record from devices that do not send note-offs, it will 'just work'.
Recall there was an issue about that, which I can't find now, a user was attempting to use a Wii Drums set,
 which does not send note-offs most of the time. The solution required creating your own custom instrument
 with the 'no note-offs' setting. Hopefully this will be no longer required.

**Comment by Gnlfz007** [comment]
I'm not expecting immediate fixing, there is a workaround. I think that these major usability issues should have far more priority than some layout issues.

I'm not actually pleased with the number of such major issues I found in the near past, but I'm aware that unfunded open source projects need testing + reporting by the users. I WONDER why there is nobody else reporting such obvious bugs; anybody else actually using MusE?!

**Comment by spamatica** [comment]
Oh, there are dozens of us, dozens!

Joking aside, making audio in Linux is a niche within a niche and there are
many applications to choose from. It's hard to give numbers as MusE is open
source, but it is not the biggest application in the Linux audio echo
system that is certainly true.

Speaking for myself, coming mostly from an audio background, play guitar,
recorded on cassette back in the day - I never missed these midi recording
mechanics.
This might be naive and misinformed on my part but I can imagine people
moving away from in-place midi editing (even if it worked better) as I find
it quite complicated to set up.
When I need to redo something I cut out the bad part and press ctrl+shift+D
to duplicate the current track and do the retake on this fresh place.
These days tracks are basically for free so I find this workflow gives me
control and a sense of where changes have occured. Sometimes I merge the
changes back, often I do not and the project grows to a lot of tracks.

So, I think there are alternative ways of working which has caused this to
not be a priority... still we should of course get it working again.

Den ons 1 juli 2020 kl 08:42 skrev Gnlfz007 <notifications@github.com>:
