### ISSUE TITLE
No sound from midi

### ISSUE THREAD

**Issue by QEDan** [muse-sequencer/muse#837]
I am a first-time Muse user and new to working with MIDI. I'm having trouble getting Muse configured properly. I'm using Ubuntu 18.04.

I compiled, installed and configured Muse according to the directions in the README file. It launches and I can interact with the GUI. If I import a wav file, it will play and I can hear the audio. Unfortunately, when I try to play MIDI, I see the audio indicator moving, but I do not hear any sound at all. I tried turning on the metronome during playback, but I don't hear this either.

What are some troubleshooting steps I can take for this scenario? I realize I haven't provided much information, but I'm not sure what is relevant. Please let me know what information I should add.

Thanks!

**Comment by spamatica** [comment]
Hi Dan,
Nothing jumps out directly, is it 3.1 version that you have compiled? 3.1.1
is available since yesterday, it should however not change anything
regarding this.
Did you add any synth? The midi track by itself will not generate any
audio, it needs to be sent to a synth.

Did you watch any of the startup tutorial videos?
https://github.com/muse-sequencer/muse/wiki/Tutorials

They are mostly for older versions of MusE but the basic functionality
should still be valid.



Den sön 19 juli 2020 kl 01:36 skrev Dan Mazur <notifications@github.com>:

**Comment by QEDan** [comment]
Thank you for your response. I didn't understand that I needed to send the midi signal to a synth. I watched the tutorial videos and then got it playing sound correctly. Cheers!
