### ISSUE TITLE
Midi export can be erroneous

### ISSUE THREAD

**Issue by farvardin** [muse-sequencer/muse#841]
hello,

I've made a fews songs in MuseScore. Now I need to transpose them and I found it's easier with the Muse Sequencer. So I've exported them to midi in musescore, and opened them with Muse3 (latest version 3.1 and I've also tried with 3.1.1 with the same behavior). I works ok, but now when I export them to midi again, it works fine for some files, but some others are not correct, when I open the exported files again in muse3 or another sequencer, some midi evens are misplaced.

You can find one example file in attachment, if you open it in muse, it will display OK for every tracks. But if you export it to midi, the first 2 tracks will be correct, but the 3rd one will have the problem, as you can see on this screenshot:

![image](https://user-images.githubusercontent.com/477243/88770188-b7069300-d17d-11ea-99df-a3510f83ed2e.png)

Do you have an idea of the reason for this problem?

[reprise_buitelesyr_sta_elbilu_ay.med.zip](https://github.com/muse-sequencer/muse/files/4993272/reprise_buitelesyr_sta_elbilu_ay.med.zip)

**Comment by terminator356** [comment]
Hello. In the supplied MusE song file, all events except the first are shifted forward by 1 tick.
For example many notes in the Piano Roll appear to be placed at BBT xx:xx:001, but they should be at xx:xx:000.
Are you sure the song was entered and/or exported properly from MuseScore?

Then, due to slight rounding errors, when this song is exported from MusE as midi, the resulting times are again
 shifted forward by 1 tick, and many of the notes are placed at xx:xx:002.

However, after that, repeated exporting and re-importing did not change the tick positions any further.
They remained at xx:xx:002.

The picture you supplied shows quite a large shift of perhaps roughly 4 or 5 ticks or more.
I am not able to reproduce this large shift.
Importing any other midi files work fine, no notes are shifted, even after exporting and re-importing.

This suggests some timing scaling and imprecise rounding going on in this case.
Can you please post the following info:
1) Sample rate (This is listed in Help > About MusE > Internals tab)
2) Settings > Global Settings > Midi tab > 'Midi Resolution (ticks per quarter note)'
3) Settings > Midi File Import / Export > Export tab > 'Division' and 'Format'

If possible it would be good to post the original MuseScore file as well.


Finally, a word about 'key signature' midi meta events:
I found such events in your MusE song but the length of the meta events are incorrect.
These meta sequences are supposed to be 'FF 59 02 mm nn', where 2 indicates the length of the following 2 bytes.
In your file, it says 'FF 59 03 mm nn ??', where 3 indicates 3 valid bytes following which is **incorrect**.
For MusE, it's OK - this is benign, MusE happily ignores that third byte.

Today, I have added some fixes and changes to the git master (see ChangeLog).
One such change is that midi importing/exporting of **key signatures** is now fully **supported**, including minor keys.
You no longer have to manipulate them awkwardly as events within each track.
You manipulate them via the Master Track List Editor (View > Master Track > List).
MusE will import and export them now.
You will notice they are gone now from each track when exporting/importing - 
 they are intercepted and properly placed in our key list.

Bonus: The Score Editor now shows these keys above the staff.

Thanks.
Tim.

**Comment by farvardin** [comment]
thanks a lot for your detailed answer Tim.

I believe MuseScore export is not perfect. Maybe it depends on the instruments used (some might end notes earlier than others, to avoid unwanted sound effects). What was strange was the first two tracks were correct (visually), while the 3rd one was not, after the export.

I've seen in the event list the problem with the 2 extra ticks, from the musescore export.

In my midi export settings (I haven't noticed this part, I only browsed through the global midi options), I've seen the division was set to 96 (I don't think I've even changed this, maybe it was by default from a previous installation).

Because of this low resolution, the export from muse was even worse. This is a screenshot of the 3rd track:

![image](https://user-images.githubusercontent.com/477243/88859484-1d30fb80-d1fa-11ea-8e7d-d5a13c5e05d9.png)



On the first 2 tracks, on the other hand, the export "corrected" everything: 

![image](https://user-images.githubusercontent.com/477243/88860198-86653e80-d1fb-11ea-9c37-7d907910ac5f.png)

But anyway, when I've changed the division to 384, after export, the midi file is good enough, with no further shifting! I could import it elsewhere with no problem.

Global Midi Resolution was already set to 384. And file format is 1.

For my part the problem is solved. I missed the division option. I suppose you can close this issue. Thanks again.

**Comment by terminator356** [comment]
Good to hear! Yes, the default midi export resolution is supposed to be 384.
You can put it even higher for more resolution.

You can also put the Global Settings resolution higher than 384 for more accurate importing.
However... there are some odd visual effects - more divisions per quarter note, and hard to zoom in.
I am investigating this as it _seems_ to be incorrect.
I note that we have a Global Setting 'displayed resolution' as well, which I _think_ is supposed to help correct the problem,
 but an extensive search revealed it has never ever been used in MusE even from version 0.6.1, 20 years ago !
Hm, I could swear it used to work at one time. Checking ...
Thanks.
Tim.
