### ISSUE TITLE
Finding automation parameters in the arranger

### ISSUE THREAD

**Issue by MyLoFy** [muse-sequencer/muse#933]
Arranger: 
It is very difficult to find the right automation parameter for a synth with hundreds of parameters. They are not sorted in alphabetical order and names are often not the same as in the synth GUI. On the generic GUI the order is also different. 
To resolve this the parameters could be in alphabetical order or even better: searchable. 
![Parameters](https://user-images.githubusercontent.com/70516194/103308093-e877d900-4a11-11eb-8c4f-9eca26660cea.png)

**Comment by kybos** [comment]
Controls are sorted alphabetically now in the menu. 
Next step would be a nice dialog with search function etc., to get rid of these huge menus in the long term...

The order on the generic GUI is defined by the plugin and must remain so, because with many plugins the order is well-defined (incl. grouping) and thus significant.
