### ISSUE TITLE
Unsolo all tracks

### ISSUE THREAD

**Issue by MyLoFy** [muse-sequencer/muse#935]
I haven't found an option to un-solo all tracks at once. With a huge number of tracks it is difficult to find and un-solo the concerned tracks.

**Comment by kybos** [comment]
I think CTRL+click on the symbol is supposed to toggle solo (or mute) on all tracks (except there are the proxy solo/mute special states, and output tracks are excluded from the mass processing...).
But the behaviour is weird, it inverts the state of each track instead of setting all to the desired state. I hope this is not intended and will fix it (for input monitor/rec arm it's working as expected).

**Comment by terminator356** [comment]
Thanks. Behaviour was weird.

**Comment by MyLoFy** [comment]
Great, works like expected now, thanks!
