### ISSUE TITLE
midi input requires inital reset before working

### ISSUE THREAD

**Issue by spamatica** [muse-sequencer/muse#942]
Been using a bit more external keyboard lately and at least on my setup here, the midi input does not work until I disconnect and reconnect the midi-in device (an usb-dongle in this case) while MusE is running.

So MusE does know what device is setup for midi in but it isn't routed all the way until reconnected.

**Comment by kybos** [comment]
You mean it's not visible in the input routes for a midi track?
I don't have this problem, but I normally plug the USB keyboard directly into the PC (before I start MusE).

**Comment by terminator356** [comment]
Important question: Was this a MusE ALSA midi device/port or a Jack midi device/port?

The (my) handling of each one's re-plugging ability is vastly different.
Each, ahem, should work, although I'm probably more certain ATM about the Jack handling IIRC.
But there have been quite a few advancements quietly going on with the Jack software lately.
I hope nothing broke MusE... Will try to test tonight.

**Comment by terminator356** [comment]
Tested with my M-Audio Midisport 2x2 USB midi box: No fault found so far.

Unplugging and replugging the box while MusE is running worked fine with both ALSA and Jack midi MusE devices/ports.
Saving, restarting, then reloading the song worked.
Starting MusE with the box plugged in, then loading the song worked.
Unplugging the box, starting MusE, loading the song, then plugging the box worked.
More tests?


I'm proud of that unplugging/replugging ability with Jack midi devices.
It took quite a lot of effort to make that work.
The device ports get new IDs each time plugged in.
So it is nearly impossible to determine what MusE device ports they corresponded to before unplugging.
Nearly impossible... but accomplished using Jack's alias port names feature.
(That's why I've piped up a few times when it has been suggested on forums to remove those Jack aliases in favour
 of the newer meta data. Last I checked, the meta data doesn't have those convenient alias names pre-defined.)
The technique is so unique that I have always been skeptical of session managers, and have always doubted
 they could accomplish the same thing. It really had to be done within the app. Am I wrong these days?

**Comment by spamatica** [comment]
Hi guys, thanks for testing, seems it is my system misbehaving.

I actually did start to suspect yesterday that the problem was outside muse.

I think my USB-midi dongle crashes on the initial midi that muse can send
on startup.
Separate to this (I thought) I had an issue that journald went to
100percent CPU and upon examination it seems to be because because this USB
device misbehaves and causes logging storms.


Den lör 9 jan. 2021 02:44Tim <notifications@github.com> skrev:
