### ISSUE TITLE
GTK2 is EOL

### ISSUE THREAD

**Issue by dvzrv** [muse-sequencer/muse#973]
Hi! I maintain muse as a package for Arch Linux.
GTK2 is now EOL and distributions will start phasing it out in the coming months or years.

Do you have plans to port the application to a newer version of GTK (e.g. GTK3/GTK4)? If not yet, this would be a great time to consider it! :)

**Comment by terminator356** [comment]
Hi. The GTK2 stuff is **only** used for LV2 UIs that need it. Nowhere else in MusE is it used. (MusE is a Qt app.)
I borrowed some of that code from Rui's QTractor code ;-)
I (we) will have to see if he might have updated QTractor and, ahem, conveniently borrow the code again.
Otherwise we'll have to roll up our sleeves and try to upgrade our code ourselves to GTK3.
Keep this issue open as a reminder. Thanks.

**Comment by kybos** [comment]
Hi,
I don't really believe any distro will start phasing out GTK2 anytime soon. There are still too many apps relying on it, some of them pretty central.
As for the lv2 UIs (as Tim wrote already, this is the only area where MusE uses GTK, being a pure Qt application): To my knowledge, the only (relevant?) set of plugins that use GTK2 UIs are the Calf plugins. Currently it doesn't look like there will ever be a GTK3 version of them, mainly because GTK has gained a very bad reputation in connection with audio plugins (due to Ardour issues with them). I don't know of any existing GTK3 plugin anyway.
So I guess we will have to keep the GTK2 support as it is because of Calf, and it makes hardly any sense to port it to GTK3 or later in the current situation.

**Comment by dvzrv** [comment]
> I don't really believe any distro will start phasing out GTK2 anytime soon

On Arch we have already started looking into adapting software relying on gtk2 in a first iteration.
Eventually though we will remove any gtk2-only applications from the repository (if there are not many relevant left). Note, that there is no fixed date on that yet.
Currently there are still quite a few gtk2 dependants: https://archlinux.org/packages/extra/x86_64/gtk2/

> To my knowledge, the only (relevant?) set of plugins that use GTK2 UIs are the Calf plugins. Currently it doesn't look like there will ever be a GTK3 version of them, mainly because GTK has gained a very bad reputation in connection with audio plugins (due to Ardour issues with them). I don't know of any existing GTK3 plugin anyway.

Yes, calf is one of the major users of gtk2 in regards to audio plugins. I would argue, that it has lost relevance in comparison to e.g. lsp-plugins or x42-plugins though (both in quality and popularity).
The issues with GTK* and host applications is, that when running those plugins on a system that uses non-matching GTK versions for host and plugin, there *will be* symbol clashes, leading to the crashing of the host. This is why many hosts started to block the use of plugins, that rely on non-self-contained toolkits such as GTK or Qt.

Ideally plugins should use self-contained UI toolkits (e.g. [pugl](https://gitlab.com/lv2/pugl/)).

Back to the topic: Muse already [provides a switch to disable the use of GTK2 for LV2](https://github.com/muse-sequencer/muse/blob/cfd0a252519d2a6cdbd59507a94a5d00d735cfcf/src/CMakeLists.txt#L171), so all is good (for me)! :)

**Comment by kybos** [comment]
> The issues with GTK* and host applications is, that when running those plugins on a system that uses non-matching GTK versions for host and plugin, there _will be_ symbol clashes, leading to the crashing of the host. This is why many hosts started to block the use of plugins, that rely on non-self-contained toolkits such as GTK or Qt.

Yes, that's the reason why Ardour (being GTK itself) has been struggling with Calf most, and not so QTractor or MusE. Interestingly, there doesn't seem to be so many problems with the Qt plugins like synthv1 and friends... But sure, the future is in self-contained, small and efficient UI frameworks.

**Comment by terminator356** [comment]
> Muse already provides a switch to disable the use of GTK2 for LV2, so all is good (for me)! :)

Yup. GTK is such a 'foreign' oddity to be including in a Qt app, it just felt too odd to require,
 so that's why I added that option. I knew it would come in handy at some point.

> Interestingly, there doesn't seem to be so many problems with the Qt plugins like synthv1 and friends

All of them had to upgrade when Qt5 came out. There was a period of uncomfortable awkwardness with lingering Qt4.
Likely the same when Qt6 becomes mainstream.
