### ISSUE TITLE
If a track is selected, unselect any selected parts

### ISSUE THREAD

**Issue by fpesari** [muse-sequencer/muse#998]
i selected a track to delete it with the Del key but it deleted a MIDI part I selected previously.

Selecting a track without Ctrl should unselect all other selections, including parts.

To replicate it:
1. Crate 2 tracks, one Wave (Track 1) one MIDI (Track 2)
2. Draw a random MIDI clip with the Draw tool
3. Left-click on the MIDI clip
4. Left click on the audio track
5. Press the Del key
6. The MIDI part in Track 2 will be deleted, even if the last action the user did is explicitly select Track 1

**Comment by kybos** [comment]
I don't think selecting a track should change the part selections, AFAICS this is not how it is designed to work (and it wouldn't solve the problem anyway).

The real problem IMO is the erratic semantics of the DEL shortcut in the Arranger. It deletes the part if one is selected, if not then it deletes the track. Not sure if it's a bug or intention, but the user clearly shouldn't be expected to check if there is a selected part somewhere before pressing DEL, just to know what it will do in the given moment.

It can't be solved by checking the current focus, because the user normally cannot see if the focus is in the track list or in the part canvas.

So inside the Arranger scope, the DEL shortcut would better be restricted to exactly one action - deleting parts. For deleting Tracks another, dedicated shortcut should be introduced (e.g. Ctrl+DEL, customizable if possible).

**Comment by fpesari** [comment]
> So inside the Arranger scope, the DEL shortcut would better be restricted to exactly one action - deleting parts. For deleting Tracks another, dedicated shortcut should be introduced (e.g. Ctrl+DEL, customizable if possible).

I agree with this solution - it would be much more consistent!

**Comment by spamatica** [comment]
>So inside the Arranger scope, the DEL shortcut would better be restricted to exactly one action - deleting parts. For deleting Tracks another, dedicated shortcut should be introduced (e.g. Ctrl+DEL, customizable if possible).

I concurr ctrl+del is unused as far as I know so it is a good candidate
